### ISSUE TITLE
Stream logs to UI console

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#1193]
**What problem or use case are you trying to solve?**
When OD runs a long command, like `apt-get install foo`, it kind of just hangs for a while, and the user can't see what's happening

**Describe the UX of the solution you'd like**
I'd love to see the logs stream in

**Do you have thoughts on the technical implementation?**
This will probably be hard to do. Currently the websocket sends events in chunks...we might need to change that

**Comment by amanape** [comment]
Maybe we can stream it to another terminal instance? I've already seen remnants of a custom addon that uses the existing WS class, so it may be worth exploring this approach (just need to extend the refactored refactor of the terminal hook to accept addons).

There is also an [official `attach` addon](https://xtermjs.org/docs/api/addons/attach/) from XTerm, but I'm not sure how compatible it is with a custom WS class (if relevant at all to this case).

**Comment by tobitege** [comment]
Hello @xingyaoww if you have a few minutes to give a cursory look (not a full review) at #2818 which tries to achieve this.
Still working on some issues.
