### ISSUE TITLE
Pause and Restart controls are often unresponsive

### ISSUE THREAD

**Issue by arose26** [All-Hands-AI/OpenHands#1427]
**What problem or use case are you trying to solve?**
Many times the AI will get stuck trying to do a futile task. The user must currently wait for it to finish.
**Describe the UX of the solution you'd like**
An ABORT button that cancels the current task.
**Do you have thoughts on the technical implementation?**
Kill current process and return input to user.

**Comment by zhonggegege** [comment]
Are you not used to the "MonologueAgent" monologue mode? A code reply that is easy to complete in the dialogue mode is difficult to complete after dozens of rounds in the monologue mode. It always has various errors, such as repeating without action in the monologue mode, Problems such as writing only part of the code, repeating multiple pieces of the same code, etc. In this case, using the chat mode can directly reply to the complete code in 2-5 rounds of conversations. Scenarios like this feel like simple things become complicated. Yes, I think there is a problem with the logic. Of course, I don’t mean that the monologue logic is unnecessary, but I think it still has a lot of room for optimization.

**Comment by enyst** [comment]
@arose26 We have added a 'pause' button and a 'restart a new agent task' button under the chat box in the UI. Do those address this issue? You may need to upgrade, it's fairly recent I believe.

@zhonggegege You may see better results with state of the art models (like GPT-4, Claude-3), but this is indeed work in progress. As far as we know, monologue agent is still the most used, SWE agent might be better on some specific actions, although that's not enough to do well with GPT-3.5. There is a lot of work on CodeActAgent with conversation mode, that you may see results of, either now or soon. You can also take a look at the current PRs on CodeAct and try them out if you wish.

**Comment by zhonggegege** [comment]
When using local agent LLM, when the agent starts running, in many cases the "Pause" and "Restart" buttons are invalid (no response when clicked). If you observe "Terminal", "WEB-UI", and "LLM Proxy Server (Response Information)" at the same time, you will feel that the response of the front-end WEB-UI is very uncoordinated and cannot respond in time. It feels like there is a huge delay. The picture suddenly returned to normal.

**Comment by rbren** [comment]
Agree--the controls often become unresponsive. I think that's the bigger issue here, so I've changed the title to reflect it

**Comment by SmartManoj** [comment]
@tobitege, #2602 `async` feature will solve this issue. right?

**Comment by tobitege** [comment]
Yes.

**Comment by amanape** [comment]
Not entirely, some of it may be async-related since these state changes wait for previous events to complete before pushing

**Comment by tobitege** [comment]
> Not entirely, some of it may be async-related since these state changes wait for previous events to complete before pushing

I had something pretty much working, but had to bin it due to all the refactors (dockersshbox gone etc):
https://github.com/All-Hands-AI/OpenHands/pull/2602

**Comment by mamoodi** [comment]
This has been resolved as part of the 0.15.0 release.
