### ISSUE TITLE
[Frontend] Short info to the user when there's an error

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#1451]
**What problem or use case are you trying to solve?**
There are system errors that backend encounters, and the user should know the system isn't working right or they can change something. The easiest example is authentication errors, when I pick a non-existent model or have no access to it or my settings are otherwise wrong.

**Describe the UX of the solution you'd like**
A system status field, maybe to the left of the Settings wheel, where we can display 'Authentication unsuccessful, please check settings' or some other clue about what went wrong. On backend, we can send some specific messages.

**Do you have thoughts on the technical implementation?**
On backend we can try to use the task stop/reset feature on at least some exceptions.

**Describe alternatives you've considered**
Maybe the field currently displaying info about the task (task has stopped, etc) could be used for this? I imagine we will also say the task is stopped though, so it seems like we need some other place for the reasons we can inform about. It doesn't have to be large (at all).

**Additional context**
Auth is the easiest example, but maybe not the best: there are other suggestions on it discussed in other issues, like some sort of ping before starting the actual task, I'm not sure what that would imply, but I think there can be errors that we cannot know before they happen, like failing to condense despite best efforts and stopping on context window exceeded.

Related:
- https://github.com/OpenDevin/OpenDevin/pull/1445
- https://github.com/OpenDevin/OpenDevin/pull/1296

**Comment by sahiix1** [comment]
https://github.com/OpenDevin/OpenDevin/pull/1445

**Comment by mamoodi** [comment]
@enyst there is a status now in the bottom middle of OpenDevin that shows high level status and I've seen some errors there. Is this what you were looking for?

**Comment by enyst** [comment]
Yes, it's fine as it is! Thanks for the heads-up, this can be closed.

**Comment by enyst** [comment]
I'm reopening this, because lately there have been multiple requests for important messages to be in a more accessible or visible way than in the logs, specially with docker app. Users request that relevant errors are more readily available or visible _somehow_. And we are listening, but we have started to make some changes to the UI adding some system / error messages in the chat box instead, since that's the ready place. Frankly, I think that doesn't look great, exceptions and raw code in-between natural language chat with the agent. Maybe there is a better way?

Perhaps we do need an actual "system status" after all, where the user can see the most important stuff (like budget exceeded).

**Comment by tobitege** [comment]
Great idea! 
Maybe next to the settings cog wheel a "Notifications" indicator that on click opens pop-out sidebar from the right that shows those collected messages, with a clear list button?
Everywhere where "toast.error" occurs, should also use that.

**Comment by enyst** [comment]
For example https://github.com/OpenDevin/OpenDevin/issues/2494

**Comment by mamoodi** [comment]
Going to use this as a catch all for better errors to the users going forward since you have some eyes on it.

**Comment by SmartManoj** [comment]
https://github.com/OpenDevin/OpenDevin/pull/2657#issuecomment-2226781143

**Comment by neubig** [comment]
I encountered another instance of this. This time my request was blocked by cloudflare, causing API calls to fail over and over again:

```
litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" /><![endif]-->
<style>body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!-->
<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>
<!--<![endif]-->


</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> onrender.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8d48d4151f7e425b</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">128.237.82.204</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script>
  window._cf_translation = {};
  
  
</script>

</body>
</html>
```

I think we should try to fix this soon!
