### ISSUE TITLE
frontend: Support displaying images/videos/pdfs in the workspace

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#1491]
**What problem or use case are you trying to solve?**

Images are not properly rendered in the Code Editor (though maybe it is not supposed to do that... -- I'm open to discussion about this).

<img width="597" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/e41ab643-bd23-41d4-aeee-ae818dd31a95">

**Describe the UX of the solution you'd like**

I kind of expect a VSCode-like experience that it can display some simple media file (jpg, png, or even mp4 and pdf) and show an error message when it encounters a binary file type (e.g., `.exe`) that it does not support.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by amanape** [comment]
For images and videos it may be as simple as rendering an `img` or `video` element given the extension/path.

**Comment by neubig** [comment]
Voting +1 on wanting to fix this.

**Comment by JanumalaAkhilendra** [comment]
i want to work on this , assign it to me :)

**Comment by itzpa1** [comment]
### I'd love to tackle this issue. Assignment request, please. : )

**Comment by neubig** [comment]
Hi @JanumalaAkhilendra and @itzpa1 , thanks a bunch for volunteering! It's great to have both of you interested, so maybe whichever one of you is able to take a stab at it first could go ahead? Or you could coordinate somehow (e.g. through the OpenHands slack frontend channel.

**Comment by sahilborse** [comment]
/@attempt #1491

**Comment by sahilborse** [comment]
@neubig  assign me this issue

**Comment by malhotra5** [comment]
Fixed by #4898
