### ISSUE TITLE
Integrate VSCode Web into OpenDevin to Support File Editing

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#1606]
**What problem or use case are you trying to solve?**

See https://opendevin.slack.com/archives/C06QT0AGY4W/p1715007881546429 for context.

**Describe the UX of the solution you'd like**

Allowing the user to potentially (1) pause the agent, (2) edit workspace code whatever they like in a separate VScode window, then (3) resume the agent (need to inform the agent in a certain way that the file has been modified).

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by xingyaoww** [comment]
More examples: https://opendevin.slack.com/archives/C06QT0AGY4W/p1715546627857459?thread_ts=1715007881.546429&cid=C06QT0AGY4W

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/552f84d0-0a2d-4b69-a1d2-4a6e194839a8)

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/0d99bd02-74ca-441c-a57d-dbeca46c0411)


> This allows me to edit stuff there and then the tooltip is saying to **tell Devin what I have done**

We also need to support a way to tell OpenDevin **what user have done**

**Comment by mamoodi** [comment]
Going to close this because VSCode is implemented now in OpenHands. #3 isn't quite happening but a new issue can be opened if it's important.
