### ISSUE TITLE
Run evaluation on full SWE-Bench

### ISSUE THREAD

**Issue by rezzie-rich** [All-Hands-AI/OpenHands#1693]
Love the progress so far!

Will you guys test and publish the full swe-bench and the 25% subset test besides just the swe-bench lite?

On auto-code-rover repo, it says 22% on swe-bench lite and 16% on full swe-bench. However, you guys have ACR at 16% on swe-bench lite. Is that the result you guys got or a typo?

**Comment by rbren** [comment]
Thanks for pointing that out! Not sure if it was a typo, or if we were using an old result of theirs.

Let's remove the graph until we can generate a better one

**Comment by neubig** [comment]
This number is from the most recent version of the paper! I think we should clarify this in the graph.

**Comment by frankxu2004** [comment]
From the ACR paper, it shows: 
![image](https://github.com/OpenDevin/OpenDevin/assets/6738274/4562455d-04cc-4d4a-a8e4-4fc471a4572f)

Note that ACR-avg is the comparable number here, as it's the average of multiple runs (meaning that it's pass@1 rate). I see that the 22.33% number inside the repo is the ACR-all, which is the union of multiple runs ( meaning that it's pass@k rate). I think it's still valid number comparison that for pass@1

**Comment by rbren** [comment]
Ahh thank you for the clarification! I will remove my PR

**Comment by neubig** [comment]
So I think the AutoCodeRover is fine as-is, but I agree we should still run on all of SWE-Bench. The main bottleneck for this is time and cost, it costs about $6,000 to run on all of SWE-Bench with GPT-4

**Comment by libowen2121** [comment]
@rezzie-rich Thank you for the question! As @frankxu2004 clarified, we only report the pass@1 results in the graph. Our evaluation containerization only supports SWE-bench-lite for now and we will extend it to support the full test set!

**Comment by rezzie-rich** [comment]
Gpt-4 is expensive. I think it would be cool if you guys could run the full bench using llama3 70b and 8b as it would give a unique and realistic expectation of running with open llm. 

It's hard to compare swe-bench with humans, but as a rule of thumb, an average jr. developer should be able to complete 10-25% while an average sr. developer can 20-40%. 

If we can have opendevin complete 25%+ using an open llm (preferably with less than 34b parameters), it's a game changer!

**Comment by rezzie-rich** [comment]
https://evalplus.github.io/leaderboard.html

Leaderboard for open code llm is kinda diluted. However, i found this up to date leaderboard that seems pretty legit. 

It has codeQwen-1.5-7b-chat listed above Claude-3-opus right next to gpt-4. Small llm like this should be able to run the bench faster and lot cheaper compared to gpt-4. 

If the leaderboard is accurate, it makes codeQwen a valid replacement for gpt-4. 

If opendevin can complete 20-25% of the full swe-bench using a 7b model, that would prove the practically and real use case of ai agents in software development.

**Comment by rezzie-rich** [comment]
https://chat.lmsys.org/?leaderboard


llama3-70b-instruct is performing better than half of GPT-4 versions. I think it would be great to have benchmarks done using llama3 in the spirit of open-source community while keeping the usage practical.

**Comment by xingyaoww** [comment]
@rezzie-rich Good point -- However, Llama-3 only has 8k context window which means it is hardly useful in our agent usecases. I just tested the recent deepseek-V2 MoE - Check results here: https://huggingface.co/spaces/OpenDevin/evaluation

It got ~5% on SWE-Bench lite, and from what i can tell qualitatively, a lot of error cases are due to limited context window (32k) of their API.

**Comment by rezzie-rich** [comment]
https://huggingface.co/gradientai/Llama-3-70B-Instruct-Gradient-1048k


This version has a million context window.

**Comment by xingyaoww** [comment]
@rezzie-rich Thanks a ton for sharing!!! Will try to get some GPU and test it right away!!!

**Comment by BradKML** [comment]
Seconding this but not just switching models like @rezzie-rich does (great idea BTW if it can be included into Ollama or some other tool), but also are there any alternative benchmarks for seeing how good they can solve competitive coding problems (or data science problems) for confirmation of quality over mere LLM?

**Comment by 0xdevalias** [comment]
Shouldn't be stale IMO

**Comment by xingyaoww** [comment]
Some updates: we are making some progresses on the infrastructure side - hopefully we can resolve this in ~2 weeks!

**Comment by BradKML** [comment]
Looking forward to this TBH, if only there is a way to decentralize evaluation between multiple volunteers... But replicability is also an issue

**Comment by xingyaoww** [comment]
Hopefully, we may be able to do this soon for https://github.com/All-Hands-AI/OpenHands/pull/4537 🙏  (with some budget constraint)

**Comment by xingyaoww** [comment]
I believe this one is already solved: https://github.com/swe-bench/experiments/pull/107
