### ISSUE TITLE
[Feature]: Enable linting to check arguments mentioned in docstrings

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#1698]
**What problem or use case are you trying to solve?**

In some cases, arguments mentioned in docstrings have become stale, and no longer match the actual function signature. It would be better if we checked docstrings through linting so this doesn't happen.

Here is one example of an out-of-date docstring: https://github.com/OpenDevin/OpenDevin/blob/b4cdebec06715c98827256ab01caf4fc513f670f/opendevin/llm/llm.py#L44
(at least `llm_top_p` is not documented)

**Do you have thoughts on the technical implementation?**

This can probably be enabled by adding the following to `pyproject.toml`

```
[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
```

We might want to then disable the conventions that require docstrings for every function (at least for now) because that would be too much work to add docstrings to every missing function.

**Comment by li-boxuan** [comment]
Would be exciting if anyone can use OpenDevin to fix this

**Comment by nlauchande** [comment]
@neubig @li-boxuan : I am keen to try my luck on this . Any tips from where to start ?

**Comment by neubig** [comment]
I tried to give some direction in the issue description above, but if you have any additional questions I'm happy to help

**Comment by nlauchande** [comment]
@neubig: Cool, I am fancying the idea of using  OpenDevin to fix OpenDevin and see how it goes.

**Comment by tobitege** [comment]
> @neubig: Cool, I am fancying the idea of using OpenDevin to fix OpenDevin and see how it goes.

Hello @nlauchande,
have you had the time yet to take a look into this enhancement?

**Comment by anushkumarv** [comment]
Hello, I would love to start contributing to OpenDevin. Since this is labeled as a "small effort", can I take a look at it if no one else is?

**Comment by tobitege** [comment]
> Hello, I would love to start contributing to OpenDevin. Since this is labeled as a "small effort", can I take a look at it if no one else is?

Hello,
since we haven't heard from the previous poster, we'd be happy for your contribution! 😃

**Comment by tobitege** [comment]
Please don't let `ruff` make the dev's life harder with docstring issues. 😬 
Not that upon trying to commit the whole codebase will be checked and comes back with 200 warnings.

IF could ruff fix smaller docstring issues by itself, with simple re-formatting them, lets try that first.
You might also look into the "dev_config/python" folder, which is important when building from source and committing (pre-commit)

**Comment by anushkumarv** [comment]
There are about 383 docstring-related issues, with 208 of them as safe fixes and 116 as unsafe fixes.
I have been trying to check `ruff`'s documentation to isolate unsafe fixes to have a look at them but haven't had any luck. Any ideas there? I could save the safe fixes and later look at the unsafe fixes.

Additionally, do we want to consider including docstring-related issues as part of pre-commit checks sometime in the future?

**Comment by neubig** [comment]
We could start out by sending a PR with all the safe fixes. For other docstring related issues we might want to decide whether it's with the effort to fix them (maybe there are better uses of our time now?)

**Comment by anushkumarv** [comment]
sure I can create the PR

**Comment by anushkumarv** [comment]
`pyproject-fmt` seem to fail continuously fail when I try to commit the above changes to `pyproject.toml`
It tries to add a new line after `swebench = { git = "https://github.com/OpenDevin/SWE-bench.git" }` each time I try to commit. 

I tried revising the version of `pyproject-fmt` from `1.7.0` to `2.0.4` and that seems to work

**Comment by tobitege** [comment]
> `pyproject-fmt` seem to fail continuously fail when I try to commit the above changes to `pyproject.toml` It tries to add a new line after `swebench = { git = "https://github.com/OpenDevin/SWE-bench.git" }` each time I try to commit.
> 
> I tried revising the version of `pyproject-fmt` from `1.7.0` to `2.0.4` and that seems to work

It does love to wrap long lines, that's for sure. 😃 I just let it do it and commit that change.

@iFurySt could you look into the version bump of that package, if there'd be breaking changes if we went with v2.0.4?

**Comment by mamoodi** [comment]
@tobitege or @neubig can this issue be closed with the PR being merged now?
