### ISSUE TITLE
Prompt remotely via API

### ISSUE THREAD

**Issue by jeffscottward** [All-Hands-AI/OpenHands#1716]
**What problem or use case are you trying to solve?**

Want to have an external AI Agent feeding it prompts.

**Describe the UX of the solution you'd like**

/prompt POST "build me XYZ"

**Do you have thoughts on the technical implementation?**

No.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by jeffscottward** [comment]
Not stale

**Comment by SmartManoj** [comment]
> /prompt POST "build me XYZ"

Could you provide the expected output?

**Comment by jeffscottward** [comment]
On second thought it probably would not be /prompt POST "build XYZ"

It would be started on one machine as a local server that has port and proxy options as flags. And then it logs out its addresses when started for access like

localhost:1234
192.168.1.1234
345.234.8.1234

And then you can use the CLI or a chat web interface on another machine that is doing post requests to a specified address you fed in as a flag and everything is posting to that address. Just how like OpenAI chat probably works.

The web ui would obviously parse in the UI for clarity although you can turn on verbose and see all the status codes and headers and responses etc. CLI would log verbosely by default.

**Comment by SmartManoj** [comment]
Why not accessing the front end on the other machine?

**Comment by jeffscottward** [comment]
Because I want all the spare CPU/GPU cycles I can get because I am testing
something else.

**Comment by SmartManoj** [comment]
Are you using local LLM?
If so, how about running LLM only in one system?

**Comment by jeffscottward** [comment]
I do that and many other things.
My computer would not be able to handle that addition.

Why is there resistance to this? I just want to offload the compute and try
to let the thing code autonomously.

Starting a server that can accept incoming requests is software dev 101.

I’ve made my request clear.
If you don’t want to add it I will move on to another project.

**Comment by mamoodi** [comment]
Hi Jeff. Thanks for keeping this issue up to date. I've removed the stale label.

**Comment by yufansong** [comment]
We may release the cloud version in the future. But it still need more efforts to achieve it.

**Comment by Obs01ete** [comment]
I am also highly interested in the API access to the Devin server. Please let me know if the capability is already there. I have asked this in the discussions as well:
https://github.com/All-Hands-AI/OpenHands/discussions/3532
