### ISSUE TITLE
Support running with multiple parallel sessions

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#1744]
**What problem or use case are you trying to solve?**

Context: https://opendevin.slack.com/archives/C06QT0AGY4W/p1715546336329329?thread_ts=1715007881.546429&cid=C06QT0AGY4W

**Describe the UX of the solution you'd like**

Allowing multiple parallel sessions to be ran. Probably need to wait after (and build into) https://github.com/OpenDevin/OpenDevin/issues/1086.

![image](https://github.com/OpenDevin/OpenDevin/assets/38853559/ae0aae29-8533-4061-991f-09b38fdfc2fd)

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamoodi** [comment]
This is a really old issue so might need some clarification now that this has changed a bit.
We added multi tab support in version 0.15.0. But I believe this means completely two separate instances of OpenHands. A bit of clarification on this issue would be nice.

**Comment by xingyaoww** [comment]
If so, let's close this one and use #4606 to track it?

**Comment by mamoodi** [comment]
Going to close in favor of 4606.
