### ISSUE TITLE
[Feature]: Allow setting of `SANDBOX_ENV` variables from config.toml

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#1781]
**What problem or use case are you trying to solve?**

It is possible to set environmental variables in the sandbox through environmental variables in the environment, pre-pended with `SANDBOX_ENV`: https://github.com/OpenDevin/OpenDevin/blob/beb74a19f607e7fa2d1c2581373fc7ec1409ffeb/opendevin/runtime/sandbox.py#L12-L16

I expected that I would also be able to set the same variables through `config.toml`, but apparently this does not work.

**Describe the UX of the solution you'd like**

It would be good if we could set the variables through `config.toml` as well. This can be done by modifying the code above, or possibly modifying the file `opendevin/core/config.py`

**Comment by enyst** [comment]
There's a PR that reworks sandbox config https://github.com/OpenDevin/OpenDevin/pull/2336. It doesn't address this currently, but I'll include this.

**Comment by mamoodi** [comment]
Oh interesting. I didn't know this is a thing. Meaning if we append "SANDBOX_ENV" to any environment variable and use it in the docker command, it will set it in the sandbox?

**Comment by neubig** [comment]
Hey @mamoodi , yes it's a thing. It could definitely be documented better.

**Comment by SmartManoj** [comment]
Loading the .env file in the workspace folder is not suitable for this?
