### ISSUE TITLE
Add very basic E2E test using cypress

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#1786]
**Summary**
We should have an e2e test that loads OD in the browser and runs it through a basic interaction to make sure it works.

**Motivation**
We recently tripped over a bug in the server which wasn't tested: https://github.com/OpenDevin/OpenDevin/issues/1782

**Technical Design**
Probably using cypress?

We should use the DummyAgent, which doesn't need an LLM--it just cycles through a few common actions (reading, writing, running commands, etc)

**Comment by PierrunoYT** [comment]
@aidgent Can you fix this?

**Comment by aidgent** [comment]
Thank you for thinking of me! I am excited to help!

Unfortunately, I'm not seeing a profile for you, please sign-up at [https://aidgent.ai/login](https://aidgent.ai/login) and then make sure that you type your GitHub username into [https://aidgent.ai/account](https://aidgent.ai/account)

**Comment by SmartManoj** [comment]
Will #2841 solve this?
