### ISSUE TITLE
[Feature]: Implement and test speculative editing

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#1854]
**What problem or use case are you trying to solve?**

File editing is not perfect with our current method using SWE-Agent style actions.

**Do you have thoughts on the technical implementation?**

Cursor has recently published work on speculative editing, that we could possibly incorporate into our agent workflows: https://cursor.sh/blog/instant-apply

We would want to implement a prototype and benchmark it against SWE-Bench.

This would be a good issue for new contributors who have significant experience with LLMs and agents!

**Comment by JeffKatzy** [comment]
@neubig I'm interested in this, can take a look at this, this weekend.

**Comment by JeffKatzy** [comment]
@neubig Ok, so I think the easiest approach would be to implement this with huggingface's assistant model feature.  

I found some references to this [with whisper](https://huggingface.co/blog/whisper-speculative-decoding), and another hf blog [here](https://huggingface.co/blog/assisted-generation).

So would a valid implementation be to use a hf model, with an assistant model, and then update the `do_completion` call [here](https://github.com/OpenDevin/OpenDevin/blob/main/agenthub/SWE_agent/agent.py#L39), so that it can use the assistant.  And then benchmark against using without an assistant?

> One downside of using hf is it does not look there's a way to make it compatible with non-hf models like gpt-4, etc.   I looked to see if there was a way to implement a hf model wrapper, but didn't see a solution.

**Comment by JeffKatzy** [comment]
Ok, that helps.  I was looking at the implementation portion, where they talk about speculative decoding in the blog post.

> "Our biggest win comes from our custom speculative decoding algorithm called “speculative edits”. It is equivalent to a full-file-rewrite, while being up to 9x faster."

And the assistant model is how speculative decoding works with huggingface.  

Ok, so now I get that you are talking about generating edits in a diff format.  I'll look into this.

**Comment by anushkumarv** [comment]
Can I take a look at this if no one else is? I do not have much of an experience with agents, but would like to learn.
Also happy to collaborate with others on this.

**Comment by neubig** [comment]
Hi @anushkumarv , you're welcome to take a look at this! A good place to start would be to look at our "edit file" functionality.

**Comment by anushkumarv** [comment]
Got some unexpected work for a couple of weeks. I should be able to come back to this after that. Happy if someone else wants to look at this in the meantime.

**Comment by francistotle** [comment]
Anyone have advice for ramping up on current file editing capabilities in open devin?

**Comment by zkx06111** [comment]
https://www.reddit.com/r/cursor/comments/1ga26rx/introducing_fast_apply_replicate_cursors_instant/

This could be useful for implementing spec editing.

**Comment by mamoodi** [comment]
@neubig with the new changes is this issue still needed? Or can we consider it resolved?
