### ISSUE TITLE
[Bug]: Groq error 400

### ISSUE THREAD

**Issue by sparkmobi** [All-Hands-AI/OpenHands#1902]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

hello I am getting this error
 I think Opendevin should reduce the amount of length that can be sent in each request

> 11:37:53 - opendevin:ERROR: agent_controller.py:109 - Error while running the agent: GroqException - Error code: 400 - {'error': {'message': 'Please reduce the length of the messages or completion.', 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Current Version

```bash
latest
```

### Installation and Configuration

```bash
docker, groq/llama3-70b-814
```

**Comment by SmartManoj** [comment]
At which step?

**Comment by SmartManoj** [comment]
Not stale.

**Comment by mamoodi** [comment]
@SmartManoj or @enyst is this not achievable through max_input_tokens? My apologies if not.

**Comment by SmartManoj** [comment]
Yes after #2021. Currently, it is a dummy var.
