### ISSUE TITLE
[Bug]: Rendered API doc contains wrong/incomplete info

### ISSUE THREAD

**Issue by li-boxuan** [All-Hands-AI/OpenHands#2074]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The rendered API doc seems wrong: https://opendevin.github.io/OpenDevin/modules/python/opendevin/core/config

<img width="1040" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/25746010/6963f339-b23c-4391-a956-50779e96a40e">

In the codebase, they are

```
num_retries: The number of retries to attempt.
        retry_min_wait: The minimum time to wait between retries, in seconds. This is exponential backoff minimum. For models with very low limits, this can be set to 15-20.
        retry_max_wait: The maximum time to wait between retries, in seconds. This is exponential backoff maximum.
```

I have no idea how this happened. C.C. @Sparkier 

### Current OpenDevin version

```bash
https://github.com/OpenDevin/OpenDevin/commit/18d07bda891b323aac5b2ca484291c307669f2fe
```

### Installation and Configuration

```bash
N/A
```

**Comment by SmartManoj** [comment]
first 10 only have names
