### ISSUE TITLE
Better instructions for running SWE_BENCH

### ISSUE THREAD

**Issue by renxida** [All-Hands-AI/OpenHands#2239]
**What problem or use case are you trying to solve?**
rn https://github.com/OpenDevin/OpenDevin/tree/main/evaluation/swe_bench

has a lot of details about how swebench words etc. and is frankly annoying and confusing to read

**Describe the UX of the solution you'd like**
1. prominently include estimated token counts / cost for running swe bench
2. a bash file / py file / something to copy into my terminal that would:
- clone my fork of OpenDevin
- run swe bench either on my local machine / a docker container / a huggingface space
- report the results and compare to the current main branch results

**Comment by li-boxuan** [comment]
We intentionally make it detailed (and annoying to read!). Running swe-bench is very very costly and we don't want to make it too easy for people to burn their money.

**Comment by renxida** [comment]
@li-boxuan hm in that case maybe we should base64 encode the markdown file, just to add another layer of indirection.

**Comment by li-boxuan** [comment]
We do have a plan to make the evaluation repro smoother. At least we could combine some manual steps, and at the same time, remind people to be vigilant about the potential cost.

**Comment by li-boxuan** [comment]
If you would like to help on this issue, that would be great!

**Comment by neubig** [comment]
I think this is mostly fixed, the README looks OK with me. Please re-open if any issues remain!
