### ISSUE TITLE
Display on the main view botton selected agent type next to agent status

### ISSUE THREAD

**Issue by 4tal** [All-Hands-AI/OpenHands#2291]
**What problem or use case are you trying to solve?**
Running different agent that what I thought I was running

**Describe the UX of the solution you'd like**
Running different agent that what I thought I'm running

**Do you have thoughts on the technical implementation?**
Add tag on the main display maybe on the bottom with agent status agent_type

**Comment by enyst** [comment]
There is only one agent by default now, one has to choose specifically advanced settings to be able to choose another. Even if this issue isn't addressed specifically, I think I haven't seen other reports and the UI is clearer, so I'll close this issue. Please feel free to re-open if you think this is necessary.
