### ISSUE TITLE
[Enhancement]: Better handle observations for PIP install in two separate environment

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#2401]
**What problem or use case are you trying to solve?**

See example here: https://github.com/OpenDevin/OpenDevin/pull/2377#pullrequestreview-2111168085

There are some issues with `test_ipython_module` we need to think about improving - basically, when `pip install` is run on bash, the jupyter kernel won't get automatically rebooted. Ideally, we can throw a reminder suggesting, "If you think the package is installed for your jupyter kernel env, please reboot your jupyter kernel, etc".

But in the long run, we will probably have two separate Python environments for OpenDevin:
1. Python environment used for IPython kernel, which is mainly used for `agentskills` tools
2. Bash terminal, where the agent can switch between different virtual environments - In SWE-Bench, the agent is `conda activate` into a different environment. We probably need to think of a way for agent to know this better (e.g., keep the `(base)` environment PS1 prefix for the agent).

_Originally posted by @xingyaoww in https://github.com/OpenDevin/OpenDevin/pull/2377#pullrequestreview-2111168085_

Also related to https://github.com/OpenDevin/OpenDevin/issues/1739
**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by li-boxuan** [comment]
This seems transient - or, maybe only reproducible on @yufansong 's machine.

**Comment by tobitege** [comment]
Just to add my observation: I've seen the issue during regenerate on my WSL as well, at least once (the `ModuleNotFoundError: No module named 'pymsgbox'` message as well as `...already installed...`).
Is this maybe related to us switching branches with different dependency versions of packages?

**Comment by tobitege** [comment]
Related question: should the "`test_browse_internet`" be run outside of CI if TEST_ONLY=true is present?
It errors in WSL with `file not found` probably because it didn't start the http server?

**Comment by li-boxuan** [comment]
> should the "test_browse_internet" be run outside of CI if TEST_ONLY=true is present?

Mind elaborating? what do you mean by "run outside of CI"?

**Comment by tobitege** [comment]
Oh, I just meant when not run on GitHub, cause locally I'd usually not run with CI param

**Comment by li-boxuan** [comment]
> should the "test_browse_internet" be run outside of CI if TEST_ONLY=true is present?

@tobitege I still don't understand. The test should be able to run on both local environment, and on CI, if that's what you are asking.

> It errors in WSL with file not found probably because it didn't start the http server?

Probably. We do start the http server in the test, but I never tested WSL. It works on my macbook, and works on CI (ubuntu environment).

**Comment by tobitege** [comment]
Yes, you understood me correctly. I'll look into that test failing on my WSL and will keep you posted (or open a Bug report), if need be. Thanks!

**Comment by tobitege** [comment]
I _think_ I found the issue in my case when using `TEST_ONLY=true` for the integration tests.

In `regenerate.sh` the call to start the http server via `launch_http_server` is only in `regenerate_with_llm` but not `regenerate_without_llm`.

Just for testing I added around line 214 in regenerate the below lines:
```bash
    if [[ "$test_name" = "test_browse_internet" ]]; then
      echo -e "\n\n\n\n========Starting test http server========\n\n\n\n"
      launch_http_server
    fi
```
I hope this helps (above change is not part of my commits).

**Comment by li-boxuan** [comment]
> In regenerate.sh the call to start the http server via launch_http_server is only in regenerate_with_llm but not regenerate_without_llm

That's intentional. In `regenerate_with_llm` mode, we use OpenDevin the normal way by calling main method. We need to start the http server to facilitate the testing scenario. In  `regenerate_without_llm` mode, we use pytest to run OpenDevin. The http server part is handled by pytest (see conftest.py).
