### ISSUE TITLE
[Bug]: AgentSkills should not be globally stateful

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#2466]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Currently, there are places in agentskills that store the current line and current file in global variables: https://github.com/OpenDevin/OpenDevin/blob/b5e6ba8239907ef093c75cb7ba9bca93a2016349/opendevin/runtime/plugins/agent_skills/agentskills.py#L33-L35

This will not work well if we want to have different sessions within one running instance of OpenDevin (e.g. to have two separate windows open doing different things with the same server running).

To fix this issue, we should remove all these globally stateful variables from agentskills and instead store them in the agent state.

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
na
```

**Comment by tobitege** [comment]
Can take care of this after the next round of agentskills updates.
Since we now have path parameters, I'd almost go as far as to say, we could remove them altogether.
Even the WINDOW one has a default value and the LLM can decide to use it or not, but happy to hear counterarguments to keep them.

**Comment by tobitege** [comment]
@neubig I lost track of this completely, assigned myself now

**Comment by neubig** [comment]
Thanks @tobitege !
