### ISSUE TITLE
[Bug]: "browser environment took too long" error Everytime I use the browser

### ISSUE THREAD

**Issue by Volko61** [All-Hands-AI/OpenHands#2587]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I get "browser environment took too long" error everytime I try to use the browser (for exemple by asking the LLM to open Google in the browser)

A Friend also tried OpenDevin and faced the same issue

### Current OpenDevin version

```bash
Docker : opendevin latest version
```

### Installation and Configuration

```bash
The docker command one provided in the README.md
```

### Model and Agent

CodeActAgent (or any other agent in fact)

### Operating System

Linux

### Reproduction Steps

Just install normally and Ask him to search something on the browser

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/147256076/075c7e33-64b5-4d7f-abe9-b92f082e01d3)
![image-1](https://github.com/OpenDevin/OpenDevin/assets/147256076/bb3bd72b-7fec-412b-b932-e1aa36dce932)

**Comment by mamoodi** [comment]
Interesting. Which LLM. Using MacOS with GPT as the backend I can't reproduce. 
![Screenshot 2024-06-22 at 1 10 21 PM](https://github.com/OpenDevin/OpenDevin/assets/169627366/12705eee-1f8b-4944-a850-661777484a48)

**Comment by assertion** [comment]
It seems more likely to be your local network issue. Can you try to curl google in the container started by OpenDevin, to check if related to network problem? @Volko61

**Comment by Volko61** [comment]
![image](https://github.com/OpenDevin/OpenDevin/assets/147256076/a0f4fa3b-949c-4f9a-813a-f8012b6a99ac)
@assertion @mamoodi

**Comment by mamoodi** [comment]
Very strange. Could be something with your environment as I've checked this multiple times.
Also click the "thumbs" down button on OpenDevin when this happens just in case there is something that can be fixed for OpenDevin side.

**Comment by charliez0** [comment]
> Very strange. Could be something with your environment as I've checked this multiple times. Also click the "thumbs" down button on OpenDevin when this happens just in case there is something that can be fixed for OpenDevin side.

I'm happening this, maybe system memory insufficient? I have 2GB ram and 4GB swap and
```plain
root@speedtest:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       1.6Gi       103Mi        56Ki       376Mi       297Mi
Swap:          4.9Gi       1.6Gi       3.3Gi
```

**Comment by charliez0** [comment]
is there any chance to change the timeout value?

**Comment by tobitege** [comment]
err... are you running this on a mobile phone? 😂

**Comment by SmartManoj** [comment]
> is there any chance to change the timeout value?

https://github.com/OpenDevin/OpenDevin/blob/eb182f492e82acb7f28907de4482ba89bd97d67a/opendevin/runtime/browser/browser_env.py#L161
