### ISSUE TITLE
[Bug]: conda environment may differ from the jupyter and ipython environment when running the SWE-bench tasks, and it throws the package NotFound Error

### ISSUE THREAD

**Issue by sinsauzero** [All-Hands-AI/OpenHands#2733]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I try to run the SWE-bench tasks using CodeActAgent, found that when agent deal with the task and run the code with ipython, the observation will forever throw the package not found error. This package is directly related to the task, e.g. astropy. 
Then the agent try to install it with `pip install`, however, the output seems the package already installed. So the agent gets confused now. 

And I login to the sandbox manually, seems that the conda environment to the task differs from the ipython and jupyter environment, so it cannot find the target package. 

I wonder if that's the problem, if so, how can I fix it??

### Current OpenDevin version

```bash
0.6.2
```

### Installation and Configuration

```bash
I install the environment directly followed the README in evaluation/swe_bench
```

### Model and Agent

CodeActAgent

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/OpenDevin/OpenDevin/assets/73391106/974b8ec7-45c3-4f99-b692-1a905555d01b)
![image](https://github.com/OpenDevin/OpenDevin/assets/73391106/ce175a5f-074e-4b72-bf2f-2d613b503511)

**Comment by sinsauzero** [comment]
found reason.
OpenDevin/opendevin/runtime/plugins/jupyter/setup.sh line 46.  

The ss command not found in image, causing the jupyter server python not corresponded with $OPENDEVIN_PYTHON_INTERPRETER

**Comment by tobitege** [comment]
> found reason. OpenDevin/opendevin/runtime/plugins/jupyter/setup.sh line 46.
> 
> The ss command not found in image, causing the jupyter server python not corresponded with $OPENDEVIN_PYTHON_INTERPRETER

Hmm I thought "ss" (part of iproute2?) would be commonly installed by default?
Would you mind trying to install it manually, if available, please?
```
sudo apt-get update
sudo apt-get install iproute2
```

**Comment by sinsauzero** [comment]
> > found reason. OpenDevin/opendevin/runtime/plugins/jupyter/setup.sh line 46.
> > The ss command not found in image, causing the jupyter server python not corresponded with $OPENDEVIN_PYTHON_INTERPRETER
> 
> Hmm I thought "ss" (part of iproute2?) would be commonly installed by default? Would you mind trying to install it manually, if available, please?
> 
> ```
> sudo apt-get update
> sudo apt-get install iproute2
> ```

yes, i manually add it to the od_sandbox image now

**Comment by tobitege** [comment]
@sinsauzero is that a custom image or from the OpenDevin side?

@Shimada666 is that a package we'd need to look into adding to our scripts?

**Comment by sinsauzero** [comment]
I solve it by running the jupyter setup.sh again
![image](https://github.com/OpenDevin/OpenDevin/assets/73391106/48964961-98da-436e-8f58-014ef305a9ed)

**Comment by tobitege** [comment]
Ok, great feedback, thanks!

**Comment by sinsauzero** [comment]
Hope this bug can be solved soon...

**Comment by Shimada666** [comment]
@sinsauzero 
Hi! The agnostic image has not been tested with the swe bench yet. I am not sure if running swe bench requires configuring sandbox_container_image. If the sandbox image uses the default `ghcr.io/opendevin/sandbox:main`, it will not trigger the build of the agnostic image. If you are sure this is a bug, you can create a PR to fix it! Or I can create a PR to fix it later. The purpose of the agnostic image is to allow the sandbox to run on any user-provided image, so we hope to minimize system-level dependencies. However, you can still install it if needed, that's okay.

**Comment by sinsauzero** [comment]
> @sinsauzero Hi! The agnostic image has not been tested with the swe bench yet. I am not sure if running swe bench requires configuring sandbox_container_image. If the sandbox image uses the default `ghcr.io/opendevin/sandbox:main`, it will not trigger the build of the agnostic image. If you are sure this is a bug, you can create a PR to fix it! Or I can create a PR to fix it later. The purpose of the agnostic image is to allow the sandbox to run on any user-provided image, so we hope to minimize system-level dependencies. However, you can still install it if needed, that's okay.

But when I run the `/evaluation/swe_bench/scripts/run_infer.sh` by default, it seems trigger the od_sandbox_image because of the image name not beiing `ghcr.io/opendevin/sandbox:main`. I found that the container name of swe-bench default is 
`SWE_BENCH_CONTAINER_IMAGE = 'ghcr.io/opendevin/eval-swe-bench:full-v1.2.1'` as defined in `evaluation/swe_bench/swe_env_box.py`

**Comment by sinsauzero** [comment]
> @sinsauzero Hi! The agnostic image has not been tested with the swe bench yet. I am not sure if running swe bench requires configuring sandbox_container_image. If the sandbox image uses the default `ghcr.io/opendevin/sandbox:main`, it will not trigger the build of the agnostic image. If you are sure this is a bug, you can create a PR to fix it! Or I can create a PR to fix it later. The purpose of the agnostic image is to allow the sandbox to run on any user-provided image, so we hope to minimize system-level dependencies. However, you can still install it if needed, that's okay.

That's ok, the image is not the main problem. I think the main problem is to associate the jupyter server python to the instance python so that when model wants to import the package(e.g. astropy, scikit-learn),   the correct version will be found.
Right now, it seems jupyter server python is `/usr/bin/python` which will not have any installed packages

**Comment by tobitege** [comment]
Hello @xingyaoww and @neubig - this issue needs your feedback as it touches evals.

**Comment by xingyaoww** [comment]
I think this is a known issue: https://github.com/OpenDevin/OpenDevin/issues/2401

We don't yet have a very good idea of how to fix it, but right now, the workaround would be telling the agent only to modify files using IPython (and `agentskills`) and running the program using bash (where the correct SWE-Bench instance environment is activated) - which seems to be effective at solving SWE-Bench to some extent.

**Comment by xingyaoww** [comment]
This should already be resolved in https://github.com/All-Hands-AI/OpenHands/pull/3448
