### ISSUE TITLE
Enhance code agent's search ability with ACR's context search API

### ISSUE THREAD

**Issue by ryanhoangt** [All-Hands-AI/OpenHands#2798]
**What problem or use case are you trying to solve?**

The current search skills available to the agent is:
```python
- search_dir(search_term, dir_path='./'): # Searches for a term in all files in the specified directory.
- search_file(search_term, file_path=None): # Searches for a term in the specified file or the currently open file.
```
This is versatile but quite coarse-grained, and sometimes the agent doesn't use the skill at all but `grep` or `find` instead. (e.g. [1](https://huggingface.co/spaces/OpenDevin/evaluation?filepaths=outputs%2Fswe_bench_lite%2FCodeActAgent%2Fgpt-4o-2024-05-13_maxiter_30_N_v1.6-no-hint%2Foutput.jsonl&row_idx=5), [2](https://huggingface.co/spaces/OpenDevin/evaluation?filepaths=outputs%2Fswe_bench_lite%2FCodeActAgent%2Fgpt-4o-2024-05-13_maxiter_30_N_v1.6-no-hint%2Foutput.jsonl&row_idx=6))
 
**Describe the UX of the solution you'd like**

We could try to implement some more fine-grained search tools for the agent, which may help the agent to quickly locate the necessary code and possibly increase the possibility that the agent ends up use tools. [ACR](https://github.com/nus-apr/auto-code-rover) has defined some:

```python
- search_class(class_name: str): # Search for a class in the codebase
- search_method_in_file(method_name: str, file_path: str): # Search for a method in a given file
- search_method_in_class(method_name: str, class_name: str): # Search for a method in a given class
- search_method(method_name: str): # Search for a method in the entire codebase
- search_code(code_str: str): # Search for a code snippet in the entire codebase
- search_code_in_file(code_str: str, file_path: str): # Search for a code snippet in a given file file
```

*However, because these skills are for coding-oriented tasks, it may be more preferable to only use them in agents specific for coding, instead of generalist agents.*

**Do you have thoughts on the technical implementation?**

The implementation from `ACR` is well-written and documented so we can reference from there. However, we will need to make some modifications to:

- Enable line number for these tools

**Describe alternatives you've considered**

None.

**Additional context**

- With this API as a baseline, we can try to improve further by implementing new tools if needed. (e.g. `tree` command to get the repository structure)
- Some works on `swe-bench-lite` that achieve good scores like [CodeR](https://arxiv.org/abs/2406.01304) or [RepoUnderstander](https://arxiv.org/abs/2406.01422) also utilize this API, so implement this can be a prerequisite to support these agents if we would like to in the future.

---
P/s: I'm not 100% sure that this is needed, any thoughts are welcome!

**Comment by neubig** [comment]
Hey @ryanhoangt , since we have a reference implementation this looks interesting to try out!

**Comment by ryanhoangt** [comment]
> This may or may not have some licensing restrictions. Since ACR is under GPL-3.0

Oh I didn't notice this, maybe it's not desirable to use the original code as is? We can still discuss if we can come up with some ideas inspired by ACR that are useful for OpenDevin though

**Comment by ryanhoangt** [comment]
> Instead of ACR, how about implementing 'mentat auto context'.

I think this issue and Mentat's auto context serve different purposes. This issue aims to provide the agent with tools more tailored for coding tasks, improving upon the available search tools OpenDevin already has (using it or not depends on the agent). Mentat's auto context, if I understand correctly, is a way to automatically append the retrieved code snippets for the last user message into the prompt before sending to the LLM. This may be a useful feature we want to incorporate and try out for normal agent usage (I can have a closer look into the implementation), but I'm afraid it may not always help for the swe-bench evaluation of the agent:
- The retrieved code may not be useful for the issue, which negatively affect how the agent behaves accordingly (similarly to how the score decreases #2248)
- Their `MentatBot` use another approach, not this one, is that correct?

**Comment by JeffKatzy** [comment]
Ok, didn't realize the licensing issues.  

@neubig I can take another shot at this, and was exploring using the [Jedi pip package](https://github.com/davidhalter/jedi), which has an MIT license [here](https://github.com/davidhalter/jedi/blob/master/LICENSE.txt).  Is that approach worth exploring?

**Comment by neubig** [comment]
This looks interesting! Although I haven't taken a very close look.

One thing is that now that we already have treesitter integrated into OpenDevin it actually wouldn't be too hard to implement many of the functionalities by just using the ASTs that TreeSitter provides us (which would reduce our dependencies, maintenance burden, etc.).

However, if other tools are better for the job it's still fine to introduce new tools of course!
