### ISSUE TITLE
[Feature Request] OpenDevin to read files/folders contents of Workspace before starting tasks, esp. to avoir restarting a project that is in progress

### ISSUE THREAD

**Issue by MarArMar** [All-Hands-AI/OpenHands#2838]
**What problem or use case are you trying to solve?**

OpenDevin tries to create a project from scratch even when the project is started

**Describe the UX of the solution you'd like**

No UX, backend should simply list /workspace folder contents & inform Devin before Devin starts to build a project from scratch, it should be sufficient for the AI to understand the project is started

**Do you have thoughts on the technical implementation?**

Yes as seen before a simple os.walk and a list of folder / files currently in the workspace folder should be enough

**Describe alternatives you've considered**

Doing it manually each time, tell devin to manually list the fils before starting

**Additional context**

**Comment by SmartManoj** [comment]
Could you share a sample prompt?

**Comment by FellowTraveler** [comment]
Should fix this by putting the current directory ls listing into the context. I've seen this problem myself countless times, and not only with OpenDevin but in other agent projects.

**Comment by enyst** [comment]
> Workaround : explicitly tell OpenDevin that the project is ready / where to start
> 
> This worked :
> 
> ```
> This project is already set up
> 
> You can start by editing the `src/routes/+page.svelte` file to start coding.
> 
> Run the dev server with:
> `
> bunx run dev
> `
> ```

@MarArMar I agree that running a `ls` is useful, but I'm not sure about more than that: if your task says "Your mission : _create_ an interval timer website", the LLM can decide anyway to ignore the workspace and start to "create".

If the prompt would say to continue, like the example quoted above, what if the user doesn't want to continue what is in the workspace, or they have multiple projects or tasks within a project, in progress?
For example, I usually use a workspace with a project (opendevin itself) set up, but might do unrelated or partially related things at times. The agent shouldn't then expect to continue the existing project.

I think this request might be addressed better by:
- https://github.com/OpenDevin/OpenDevin/issues/1529
- https://github.com/OpenDevin/OpenDevin/issues/2843
