### ISSUE TITLE
[Feature Request] Allow to provide a startup command (be able to run a command at the startup of OpenDevin for example to be able to install requirements for its shell context)

### ISSUE THREAD

**Issue by MarArMar** [All-Hands-AI/OpenHands#2843]
**What problem or use case are you trying to solve?**

Initially, OpenDevin generally has to install dependencies to run commands, in my case it was bun, but it could be python, poetry, node, rust...

Ideally, the user should be able to provide a command to setup the environment

A typical startup command could be "./setup_env.sh", basically running a bash command in the OpenDevin context. Here a script to setup a development environment and avoid paying / waiting for OpenDevin to try & find out all the things that are missing for him to setup 

Additionally, OpenDevin tends to use outdated versions, in my case it installed Node v16 (current LTS is v20) even when explicitly instructed to use Bun v1.1 in my given task

**Describe the UX of the solution you'd like**

In the settings, allow to provide a "startup command"

If empty, do nothing

If provided, run it in the bash of OpenDevin

**Do you have thoughts on the technical implementation?**

- Allow a new setting in the settings page
- If the command is provided, at Devin startup, run it in the Devin bash context 

**Describe alternatives you've considered**

I guess tell devin to run a command before it starts developing ?

**Additional context**

**Comment by mamoodi** [comment]
I'm not sure if you could circumvent the entire setting up if you use OpenDevin. 
In this very case, it seems the best case would be to create or use a custom docker as your sandbox which already has everything installed. That way OpenDevin can get straight to business :) 
https://docs.all-hands.dev/modules/usage/custom_sandbox_guide
