### ISSUE TITLE
[Feature] Pre-build a list of OpenDevin supported sandbox images

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#2845]
**What problem or use case are you trying to solve?**

Relavant discussion: https://github.com/OpenDevin/OpenDevin/pull/2658#issuecomment-2212544525

User may have diverse environment needs (e.g., some need `python 3.10`, `3.11`, some need `nodejs`, etc). We already supported [custom sandbox images](https://docs.all-hands.dev/modules/usage/custom_sandbox_guide) that allow the user to specify a sandbox image they want to use in OpenDevin (e.g., `nodejs`), and OpenDevin can locally build it to be compatible with OpenDevin.

**Describe the UX of the solution you'd like**

- [ ] Instead of user need to build their custom image locally, maybe we can support a list of commonly used docker images (e.g., prevalent python/nodejs version, etc) as "officially build and supported" images. This will get re-build when a new version is released to save CI time.
- [ ] Select from a drop-down list on the frontend interface on which image you want to start the session with

**Do you have thoughts on the technical implementation?**

Maybe we can create a `.txt` file, where each line is an upstream docker image, e.g., https://hub.docker.com/r/ubuntu/python.
And we add a Github workflow to read this file and build the corresponding images at time of each release.

**Describe alternatives you've considered**

**Additional context**

**Comment by Shimada666** [comment]
Maybe we can start by supporting these common images: 
* python3.9 - 3.12
* node18/20.

Also, what is the naming convention for these images? How about `ghcr.io/opendevin/sandbox:${release_version}-${image_repo}__${image_tag}` ?
e.g. `ghcr.io/opendevin/sandbox:0.7.1-python__3.12`
