### ISSUE TITLE
[Bug]: Failed to share trajectories

### ISSUE THREAD

**Issue by shuyanzhou** [All-Hands-AI/OpenHands#2877]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

After rating the trajectory, I attempted to share the trajectory (both private and public), but it throws an `Internal Error`, which seems to be due to the length of the trajectory

```
18:25:12 - opendevin:INFO: feedback.py:31 - Got feedback: {'version': '1.0', 'email': 'my_email@gmail.com', 'token': 'elided', 'feedback': 'positive', 'permissions': 'private', 'trajectory': 'elided [length: 26'}
18:25:16 - opendevin:ERROR: listen.py:613 - Error submitting feedback: Failed to store feedback:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>413 Request Entity Too Large</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Request Entity Too Large</h1>
<h2>Your client issued a request that was too large.
</h2>
<h2></h2>
</body></html>

INFO:     172.26.113.158:54694 - "POST /api/submit-feedback HTTP/1.1" 500 Internal Server Error
```

### Current OpenDevin version

```bash
0.7.1
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Model and Agent

- Model: GPT-4o
- Agent: BrowserAgent

### Operating System

Linux

### Reproduction Steps

1. Perform an arbitrary intent
2. Rate
3. Share the trajectory

**Comment by SmartManoj** [comment]
If you need to share it, [copy the Payload](https://stackoverflow.com/a/77268453) and send it as a file.

CC: @neubig

**Comment by xingyaoww** [comment]
Yeah, I've encountered it, too - it typically involves web-browsing observations (i.e., the accessibility tree are just way too big).. We probably need a way to compress it?

**Comment by neubig** [comment]
Yeah, there's currently a limit on the size of trajectory that you can share at 10MB. We should try to figure out a way to fix this...

**Comment by xingyaoww** [comment]
I can try to take a look at this also.. maybe we can compress things on OD before we send it off to the server

**Comment by SmartManoj** [comment]
![image](https://github.com/user-attachments/assets/1bafeb8b-e6be-4164-8985-54f32a1c7927)

These 3 dicts are not needed. right?

[Event history](https://www.all-hands.dev/share-opendevin?share_id=e30af2c6c2f80827664577125c68fd75829d48a027d9f89c09fcddcea421ea41&password=93UdxxjfqFGWGHna)

**Comment by xingyaoww** [comment]
cc @frankxu2004 - i think we'd better keep those for documenting purpose?

**Comment by SmartManoj** [comment]
Which document?

**Comment by enyst** [comment]
It seems we send in feedback what the UI received, but that's not always the same with what we send to the LLM. The alternative is to send the actual history, which has already removed certain objects, screenshots, particularly from the browsing agent's data. The actual history seems to me important for understanding why the LLM did something.
