### ISSUE TITLE
[Bug]:  Agent Requests Above Maximum Token Limit

### ISSUE THREAD

**Issue by wTaylorBickelmann** [All-Hands-AI/OpenHands#2888]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Not sure if this is better understood as a bug or feature request, but I was using OpenDevin when I got the following error in the logging

```
litellm.exceptions.ContextWindowExceededError: litellm.BadRequestError: litellm.ContextWindowExceededError: ContextWindowExceededError: OpenAIException - Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 8641 tokens (4545 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
```

It seems like this could be solvable through chunking whenever the context window is exceeded (and maybe that is the intent?)

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin:latest (which on 7/10/24 i think would be 0.7.1)
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Model and Agent

gpt4
CodeActAgent

### Operating System

WSL

### Reproduction Steps

I asked it to fix a flask program

### Logs, Errors, Screenshots, and Additional Context

[error_log.txt](https://github.com/user-attachments/files/16169770/error_log.txt)

**Comment by SmartManoj** [comment]
#2021 will solve.
