### ISSUE TITLE
[Bug]: OpenDevin UI delays feedback when running a long running command

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#2918]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When asking OpenDevin to perform a command that will take some time, instead of telling the user that something is happening, only the "..." is displayed while in the terminal you can see that OpenDevin is doing something. This gives the perception that OpenDevin may be stuck if only looking at the UI.

### Current OpenDevin version

```bash
main
```

### Installation and Configuration

```bash
Following docker command in README
```

### Model and Agent

gpt-4o
CodeActAgent

### Operating System

MacOS

### Reproduction Steps

1. Tell OpenDevin to "Write a Hello World program in Ruby but do not execute it"
2. Tell OpenDevin to "Install Ruby and execute the script"

In the terminal I can see:
THOUGHT: Sure! First, let's install Ruby.
And it running the command. But in the OpenDevin UI, I have gotten no response yet after my prompt. It just shows `...`
Then after the entire command has been completed, I quickly get the response.

**Comment by tobitege** [comment]
We have multiple related duplicates for this topic, it all comes down to async/streaming being implemented soon-ish.

**Comment by mamoodi** [comment]
@tobitege I noticed this in the most recent version. Didn't occur before. If it's a direct duplicate, do you mind linking the issue and closing this as duplicate please?

**Comment by tobitege** [comment]
Hmm... on 2nd thought, this could be caused by a switch in logging observations.
I thought about #1427 first, but your finding is different here, I agree.
