### ISSUE TITLE
[question]: How can I open 2 completely different instances of OpenDevin?

### ISSUE THREAD

**Issue by 4tal** [All-Hands-AI/OpenHands#2920]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I want to run another different instance of OpenDevin docker.

### Current OpenDevin version

```bash
Latest
```

### Installation and Configuration

```bash
docker run \
        -it \
        --pull=always \
        -e LLM_API_KEY \
        -e SANDBOX_USER_ID=$(id -u) \
        -e HF_HOME=~/code/self/.cache \
        -e PERSIST_SANDBOX="true" \
        -e SSH_PASSWORD=$SSH_PASSWORD \
        -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
        -v $WORKSPACE_BASE:/opt/workspace_base \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -p $PORT:3000 \
        --add-host host.docker.internal:host-gateway \
        --name $INSTANCE_NAME \
        ghcr.io/opendevin/opendevin:main
```

### Operating System

MacOS M1

### Reproduction Steps

I've change the SSH_PASSWORD and PORT on the second docker instance

**Comment by SmartManoj** [comment]
You need to change the `ssh_port` config and #2413

CC: @mamoodi @neubig
