### ISSUE TITLE
[Bug]: CodeActAgent not executing code

### ISSUE THREAD

**Issue by blshao84** [All-Hands-AI/OpenHands#2924]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Hi, I'm new to opendevin. I am able to run opendevin locally (using ollama) and it seems working since I'm able to get response from my local model. However, as I try to reproduce the demo here: ,https://github.com/OpenDevin/OpenDevin/assets/38853559/f592a192-e86c-4f48-ad31-d69282d5f6ac I only get code response from model but it seems nothing gets executed. The model I'm running is lamma3:70b. Is it because of the model or I miss anything?

![image](https://github.com/user-attachments/assets/4bc3ffc0-28fc-4d5a-9d7e-03862882235a)

### Current OpenDevin version

```bash
0.8.0
```

### Installation and Configuration

```bash
docker run  -it     --pull=always    --add-host host.docker.internal:host-gateway     -e SANDBOX_USER_ID=$(id -u)     -e LLM_API_KEY="ollama"    -e LLM_BASE_URL="http://host.docker.internal:11434"    -e LLM_OLLAMA_BASE_URL="http://host.docker.internal:11434"     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000 ghcr.io/opendevin/opendevin:latest
```

### Model and Agent

- Model: llama3:70b
- Agent: CodeActAgent

### Operating System

macos

**Comment by SmartManoj** [comment]
LLM_MODEL - llama3-70b-8192

Version: e819fd3d78da696268985e363cf033f9277412a1

![image](https://github.com/user-attachments/assets/d8753736-7f96-4a03-9f4a-6bc355e320d7)

[Event history](https://od-feedback.vercel.app/show?feedback_id=e322aa411cea1e2800b95c6443b3762b7021e022406d6b97dd7911a16a5da5b0)

**Comment by BradKML** [comment]
Could it be that sometimes when the context window is too small (default) that the Code Editor or the Jupyter Notebook will simply refuse to launch? And instead test code in the chat window?

**Comment by tobitege** [comment]
> Could it be that sometimes when the context window is too small (default) that the Code Editor or the Jupyter Notebook will simply refuse to launch? And instead fake test code in the chat window?

It is more like the model does not understand the system prompt correctly, in how to call the commands for editing or python execution. So it may just "make commands up", but those don't trigger the actual tasks within OpenDevin's agent.

**Comment by SmartManoj** [comment]
> Could it be that sometimes when the context window is too small (default) that the Code Editor or the Jupyter Notebook will simply refuse to launch?

No, that may be another error.

**Comment by BradKML** [comment]
@tobitege how do you check if the LLM has "memorized" the system prompt correctly?

@SmartManoj if the fake test code is due to truncation, that means Code Editor and Jupyter Notebook will not by proxy, or is there a way around to double-check its functions?

**Comment by SmartManoj** [comment]
> Check your `ollama serve` logs to check the input_tokens are truncated like [ollama/ollama#4967](https://github.com/ollama/ollama/issues/4967)

Could you confirm this?

**Comment by tobitege** [comment]
> @tobitege how do you check if the LLM has "memorized" the system prompt correctly?

The easiest way would be to simply ask the model, example: "Were you provided any commands on how to execute my code?" or something similar.
If it has any references still in its context, it should say so.

**Comment by BradKML** [comment]
@SmartManoj confirmed that it did say it was "truncated" into 2048 so definitely need an update on this (maybe there is a way to check the GPU and then infer ideal context size?)

@tobitege would like this to be part of FAQ or testing cus the model (Qwen2) knows about the instruction but refused to run, opting for generic information.

**Comment by SmartManoj** [comment]
Could you test #2927?

**Comment by BradKML** [comment]
Will need to get it done cus currently I am using Docker + WSL and everything seems to go smoothly.

**Comment by tobitege** [comment]
> @tobitege would like this to be part of FAQ or testing cus the model (Qwen2) knows about the instruction but refused to run, opting for generic information.

Not quite sure how to go about this: from the screenshot in your first post, it is a little vague what you expect it to do.
Seems a little cumbersome, but just try to be more convincing in your request that it shall execute the code with the given commands? There's no easy fix for such a moody model, imo, unless someone else has a working "solution"?

**Comment by SmartManoj** [comment]
> from the screenshot in your first post,

@BradKML is not the author but @blshao84.

**Comment by BradKML** [comment]
Currently I am a little stuck so I would like @SmartManoj to confirm if it really was a "moodiness" issue with certain models rather than a broken context issue causing loss of instruction-following. Have you tried some of the others like Qwen2, DeepSeekCoder, or OpenCodeInterpreter?

**Comment by tobitege** [comment]
> Currently I am a little stuck so I would like @SmartManoj to confirm if it really was a "moodiness" issue with certain models rather than a broken context issue causing loss of instruction-following. Have you tried some of the others like Qwen2, DeepSeekCoder, or OpenCodeInterpreter with code changes?

You did write "knows about the instruction but refused to run" so it knows the commands but doesn't use them, right?

**Comment by SmartManoj** [comment]
As mentioned [here](https://github.com/ollama/ollama/issues/2714#issuecomment-1961882175), the prompt is split into two parts. Seems the first part is truncated.

Sample prompt :
https://github.com/OpenDevin/Opendevin/blob/main/tests/integration/mock/CodeActAgent/test_write_simple_script/prompt_001.log#L201
