### ISSUE TITLE
ghcr images: switch docker base images from Ubuntu 22.04 to 24.04?

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#2931]
**What problem or use case are you trying to solve?**

The two workflow builds of sandbox/OpenDevin images for arm64 take twice the time than for amd64.
If compatibility allows and this could be made faster by using a newer Ubuntu version,
e.g. 23 instead of 22, this should be considered.

**Do you have thoughts on the technical implementation?**

In workflows and docker files look into using more current image bases to speed up building.

**Important:**
- for v22.04 the mesa lib is installed via `libgl1-mesa-glx`, but for v24 it is just `libgl1`
- v24.04 errors about `libasound2` package: fix is to install `libasound2-plugins` as package provider

**Comment by tobitege** [comment]
cc @xingyaoww @Shimada666  👋

**Comment by charliez0** [comment]
ubuntu 24.04 have released, why not this?

**Comment by tobitege** [comment]
> ubuntu 24.04 have released, why not this?

There are package dependencies in 24.x that currently cause problems with OpenDevin and first need to be addressed.

**Comment by charliez0** [comment]
> > ubuntu 24.04 have released, why not this?
> 
> There are package dependencies in 24.x that currently cause problems with OpenDevin and first need to be addressed.

Can you give issue links with that?

**Comment by tobitege** [comment]
> Can you give issue links with that?

Sorry, not sure there's an issue for it. I only remember from building from source a while back that there was some virtual package, which was a self-installable one v23.04, which caused installation issues as it was "provided" then by 2 different other packages.
But I can't remember its specific name right now, but remember alsa and/or cups being mentioned in my attempts. 😔

**Comment by charliez0** [comment]
> > Can you give issue links with that?
> 
> Sorry, not sure there's an issue for it. I only remember from building from source a while back that there was a package, which was self-installable in v23.04, but with v24.04 it went "virtual" which caused installation issues as it was "provided" then by 2 different other packages. I can't remember its specific name right now, only that alsa and/or cups were being mentioned in my attempts. 😔

mesagl? I posted a issue with that and it got merged, and then mesagl isn't default in the image now though

**Comment by tobitege** [comment]
I couldn't find the issue, do you still have a link for that?

**Comment by charliez0** [comment]
> I couldn't find the issue, do you still have a link for that?

https://github.com/VirtualGL/virtualgl/issues/242

I guess this

**Comment by tobitege** [comment]
> > I couldn't find the issue, do you still have a link for that?
> 
> [VirtualGL/virtualgl#242](https://github.com/VirtualGL/virtualgl/issues/242)
> 
> I guess this

That one too, but I ran into this just now trying 24.04:
`E: Package 'libasound2' has no installation candidate`
This package is virtual, i.e. must be installed by one of two other packages, and both have consequences on a train of dependencies, afaik.
