### ISSUE TITLE
[Bug]: litellm response type ModelResponse causes ErrorObservation

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#2949]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://opendevin.github.io/OpenDevin/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

During integration tests, today litellm returned a completion result `ModelResponse` back.
This is not handled anywhere yet and results in an `ErrorObservation` to be returned (e.g. from MicroAgent).
```
20:23:29 - opendevin:INFO: agent_controller.py:251
OBSERVATION
ErrorObservation(content="Error in controller step: Unexpected response type: <class 'litellm.types.utils.ModelResponse'>", observation='error')
```

Actual data:
```
ModelResponse(
    id='chatcmpl-47df6b79-cb8d-4f07-920a-8c5551ea7ee4',
    choices=[
        Choices(
            finish_reason='stop',
            index=0,
            message=Message(
                content='{\n  "action": "run",\n  "args": {\n    "command": "ls"\n  }\n}\n',
                role='assistant',
                tool_calls=None,
                function_call=None
            )
        )
    ],
    created=1721067905,
    model='anthropic/claude-3.5-sonnet:beta',
    object='chat.completion',
    system_fingerprint=None,
    usage=Usage(
        prompt_tokens=10,
        completion_tokens=20,
        total_tokens=30
    )
)
```

cc @xingyaoww @li-boxuan 

### Current OpenDevin version

```bash
0.8.0
```

### Installation and Configuration

```bash
WSL, source dev
```

### Model and Agent

- Model: `anthropic/claude-3.5-sonnet:beta`
- Agent: MicroAgent

### Reproduction Steps

1. Ran integration tests with Sonnet (WSL)

**Comment by SmartManoj** [comment]
Could you provide the traceback and the commit hash as there are no log statements in L251?

v.0.0.8
https://github.com/OpenDevin/OpenDevin/blob/64be2cb466672445f44c65983495150aec4d8536/opendevin/controller/agent_controller.py#L251

Latest commit
https://github.com/OpenDevin/OpenDevin/blob/8f76587e5cbaf47acae8b49578580ffa8fdf1785/opendevin/controller/agent_controller.py#L251
