### ISSUE TITLE
open-D-tutor

### ISSUE THREAD

**Issue by rezzie-rich** [All-Hands-AI/OpenHands#2955]
Description:
I propose adding a new agent named "open-D-tutor" to the OpenDevin project. This agent's primary function will be to explain and teach users rather than generate any code. This agent will be highly beneficial for new developers learning programming and for experienced developers who need to quickly understand the structure and functionality of existing projects.

Key Features:
Educational Focus: "open-D-tutor" will provide detailed explanations of the source code for any project, whether it's local or hosted on GitHub. It will help users understand functions, algorithms, and overall project architecture.
Interactive Tutoring: Users can ask specific questions about the code or concepts they don't understand, and the agent will provide detailed explanations and clarifications.
Project Integration: This agent can be used with any project, making it an excellent tool for new developers to learn programming through real-world examples, and for experienced developers to understand new codebases quickly.

Benefits:
Learning Tool: "open-D-tutor" will be an invaluable resource for new developers learning programming by examining real projects.
Enhanced Understanding: It will help developers at all levels better understand complex codebases, speeding up the onboarding process for new projects.
Increased Engagement: By providing an educational component, OpenDevin can attract a broader audience, including educators and students.

Implementation Details:
Agent Functionality: The agent will parse the source code and generate human-readable explanations and tutorials. It will support various programming languages and frameworks.
Integration with Existing Tools: The agent will integrate with existing OpenDevin tools and UI, allowing users to select a project and receive explanations directly within the platform.
User Interaction: Users will interact with "open-D-tutor" through a chat interface, where they can ask questions and receive detailed responses.

**Comment by tobitege** [comment]
Now I'm curious what happens next 😂

**Comment by tobitege** [comment]
I like the idea you posted.
If it only was about code explanation and not execution, then it could be a different version of the `coder` micro agent` (see both the prompt.md and yaml file there):
https://github.com/OpenDevin/OpenDevin/blob/5a5713009f7a0b3fd2f61f43bf14452bf1b92ad5/agenthub/micro/coder/agent.yaml

But when I'd use such an agent, I might be quite tempted to actually have simple snippets be executed, and then we're back into CodeActAgent territory.
What do you think?

**Comment by tobitege** [comment]
Sure, I'd be happy to look at a PR for this! 👍

**Comment by tobitege** [comment]
> @tobitege couldn't add you for review, probably because it's my first PR and requires approval from the maintainer. feel free to check it out and make changes as necessary. this will be a good test for mentatbot.

I was on it while you posted your comment. It's mixed bags, to say the least 😁
