### ISSUE TITLE
Add dummy runtime image for testing

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3015]
In testing, there are errors related to building images from scratch.
https://github.com/OpenDevin/OpenDevin/actions/runs/10002545326/job/27648010988?pr=2602#step:7:2162
```
04:34:23 - opendevin:INFO: runtime_build.py:205 - Error pulling image od_runtime:ubuntu_tag_22.04, building it from scratch
04:34:23 - opendevin:INFO: runtime_build.py:206 - Non-fatal error: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=ubuntu_tag_22.04&fromImage=od_runtime: Not Found ("pull access denied for od_runtime, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```
Maybe we should we upload at least one dummy "od_runtime" image to prevent this `Client Error`, thus eliminating the constant rebuild of the image for each test in the script?
Running the actual build process in this test should probably only be required once.

_Originally posted by @tobitege in https://github.com/OpenDevin/OpenDevin/issues/3005#issuecomment-2238255728_

**Comment by xingyaoww** [comment]
@tobitege on a second thought, i think is just the bad logging.. So if it cannot pull it from the hub, it will also check locally if the image exists, if so, it will not rebuild. Let me improve the log a bit.
