### ISSUE TITLE
[Bug]: /app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'

### ISSUE THREAD

**Issue by charliez0** [All-Hands-AI/OpenHands#3018]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

warning on start
```plain
/app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
```

### Current OpenDevin version

```bash
latest
```

### Installation and Configuration

```bash
not related
```

**Comment by tobitege** [comment]
Btw, we don't support Python 3.12, but 3.11.

Do you have a little more logs for this, like where litellm "completion" is called?

**Comment by hanwsf** [comment]
I edited this metadata_filter.py, removed \*, then it is OK

**Comment by charliez0** [comment]
> Btw, we don't support Python 3.12, but 3.11.
> 
> Do you have a little more logs for this, like where litellm "completion" is called?

no further logs, just every time the server start

**Comment by SmartManoj** [comment]
> I edited this metadata_filter.py, removed *, then it is OK

You should convert it as a raw string.

Relevant SO post : [Python3.12 SyntaxWarning on triplequoted string `\d` must be `\\d`](https://stackoverflow.com/a/77531416)
