### ISSUE TITLE
[Bug]: opendevin cannot hosted in the subdir

### ISSUE THREAD

**Issue by charliez0** [All-Hands-AI/OpenHands#3019]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

/locales dir seems hardcord to the apex dir, so that hosted on subdir fail to load

### Current OpenDevin version

```bash
latest
```

### Installation and Configuration

```bash
not related
```

**Comment by mamoodi** [comment]
Hi can you clarify what you mean by "cannot be hosted in the subdir" please?
Are you referring to the workspace OpenDevin has access to?

**Comment by charliez0** [comment]
> Hi can you clarify what you mean by "cannot be hosted in the subdir" please? Are you referring to the workspace OpenDevin has access to?

Using a reverse proxy (such as nginx) to host opendevin website on subdir

**Comment by SmartManoj** [comment]
Duplicate of #2553?

**Comment by charliez0** [comment]
> Duplicate of #2553?

seems not exactly the same problem but you can track them allgather
