### ISSUE TITLE
[Bug]: gemini always trying to do the same thing in browsing

### ISSUE THREAD

**Issue by charliez0** [All-Hands-AI/OpenHands#3034]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

![image](https://github.com/user-attachments/assets/ad9cf430-8733-4b61-aaa2-6b13606fa2bf)

### Current OpenDevin version

```bash
latest
```

### Installation and Configuration

```bash
docker compose
```

**Comment by mamoodi** [comment]
Hello. Are you able to provide the prompt you ask it to perform when this happens?

**Comment by charliez0** [comment]
https://github.com/StackExchange/dnscontrol/pull/3000 browse this and figure out the solution

**Comment by tobitege** [comment]
The "empty" message is not ideal, especially not when it repeats like that.

@xingyaoww @li-boxuan the class `BrowseInteractiveAction` seems to output the action here (empty).
How about we output `self.thought` instead in this case or is this rather a condition for "stuck", if there's no real action to it?
