### ISSUE TITLE
Why nvidia is packed into the frontend container?

### ISSUE THREAD

**Issue by charliez0** [All-Hands-AI/OpenHands#3043]
![image](https://github.com/user-attachments/assets/8bd0f6f4-5551-4659-ac0e-208553bdd6e0)

**Comment by charliez0** [comment]
I found that there might still some packages not needed such as notebook
Should we do a cleanup right now?

**Comment by mamoodi** [comment]
This seems relevant or a duplicate of https://github.com/OpenDevin/OpenDevin/issues/794
