### ISSUE TITLE
[Bug]: Packages installed by Devin are not persistent

### ISSUE THREAD

**Issue by Xerizaf** [All-Hands-AI/OpenHands#3098]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I'm trying to use the latest version of OpenDevin on Windows with WSL but I'm getting the following issue: when Devin installs a package it has to reinstall it after a while because when trying to execute a script it says module not found. Any clue why this is happening?

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Model and Agent

GPT-4o and CodeAct

### Operating System

WSL on Windows

**Comment by SmartManoj** [comment]
`PERSIST_SANDBOX` config will do that.
```
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e PERSIST_SANDBOX=true \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

or you can use a [Custom Docker Sandbox](https://docs.all-hands.dev/modules/usage/custom_sandbox_guide).

**Comment by mamoodi** [comment]
Hello! Between the time that the packages need to be installed, does OpenDevin restart? If it does, that would explain it.
OpenDevin uses a sandbox which is a docker container and that's where it installs all the packages. If OpenDevin restarts, then that sandbox gets deleted and you lose your installed packages.

If you want the same packages installed all the time, you could follow this guide to create a docker image and use it as a starting image for OpenDevin: https://docs.all-hands.dev/modules/usage/custom_sandbox_guide
This is the recommended way.

You could also set `PERSIST_SANDBOX=true` as suggested above, but that may be a bit buggy depending on what you do.

**Comment by Xerizaf** [comment]
No, it doesn't restart, anyway I will try the PERSIST_SANDBOX=true and let you know. Thank you very much!

**Comment by Xerizaf** [comment]
When setting PERSIST_SANDBOX=true I get: Error creating controller. Please check Docker is running and visit https://docs.all-hands.dev/modules/usage/troubleshooting for more debugging information..

**Comment by mamoodi** [comment]
Yeah you have to pass in SSH_PASSWORD as well:
-e SSH_PASSWORD="mypassword"

**Comment by Xerizaf** [comment]
Alright, I've set every environment variable but packages still are not persistent, they have to be reinstalled every time. Why is this happening?

**Comment by mamoodi** [comment]
@Xerizaf in your docker desktop, check the container name of opendevin-sandbox.

Does the name change when it requires to reinstall the packages? 

Do you do anything in between the need for reinstall packages or does this happen within the same session? 

I can understand this is quite frustrating, I can try to get some eyes on this from the maintainers but wondering if the sandbox container is getting recreated.

**Comment by Xerizaf** [comment]
I didn't do anything in the process. I don't know how to check for docker containers, I'm not a dev

**Comment by mamoodi** [comment]
Open up the Docker Desktop application and got to "Containers". Here's a screenshot to help you out.
![Screenshot 2024-07-29 at 3 07 44 PM](https://github.com/user-attachments/assets/7f91be09-99bb-4fcb-aca2-2cf4e9110439)

**Comment by Xerizaf** [comment]
No, I don't think it changes name

**Comment by mamoodi** [comment]
Hmmmm very strange behavior! I have noticed when the packages do not persist, the sandbox gets deleted and recreated and it loses its packages.
If you ever close OpenDevin or restart it, this will happen.

But if you don't close or restart it and the sandbox is not changing at all, then I'm not sure.

**Comment by SmartManoj** [comment]
> Alright, I've set every environment variable but packages still are not persistent, they have to be reinstalled every time. Why is this happening?

Which package is it reinstalling?

**Comment by Xerizaf** [comment]
Pandas

**Comment by SmartManoj** [comment]
![image](https://github.com/user-attachments/assets/3818728d-e015-4016-aacb-17a209475db5)


[Event history](https://www.all-hands.dev/share-opendevin?share_id=ebf7ae636fbdc3a7f2a0351f17b45eec6cf8fd6474e7cbf5ba492358eb91cdbf&password=Ynb8750OiwFRdIZO)

**Comment by Xerizaf** [comment]
This time is python-binance

==============
CodeActAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0

19:37:03 - opendevin:INFO: llm.py:181 - Cost: 0.02 USD | Accumulated Cost: 0.02 USD
19:37:03 - ACTION
**IPythonRunCellAction**
THOUGHT: Sure! Let's create a basic trading bot for Binance. We'll use the `python-binance` library to interact with the Binance API. Here are the steps we'll follow:

1. Install the `python-binance` library.
2. Create a Python script for the trading bot.
3. Implement basic functionality to fetch market data and place orders.

Let's start by installing the `python-binance` library.
CODE:
%pip install python-binance
> >
WARNING: The directory '/home/opendevin/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -ytz (/opendevin/miniforge3/lib/python3.10/site-packages)
Requirement already satisfied: python-binance in /opendevin/miniforge3/lib/python3.10/site-packages (1.0.19)
Requirement already satisfied: requests in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (2.32.3)
Requirement already satisfied: six in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (1.16.0)
Requirement already satisfied: dateparser in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (1.2.0)
Requirement already satisfied: aiohttp in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (3.9.5)
Requirement already satisfied: ujson in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (5.10.0)
Requirement already satisfied: websockets in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (12.0)
Requirement already satisfied: pycryptodome in /opendevin/miniforge3/lib/python3.10/site-packages (from python-binance) (3.20.0)
Requirement already satisfied: aiosignal>=1.1.2 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /opendevin/miniforge3/lib/python3.10/site-packages (from aiohttp->python-binance) (4.0.3)
Requirement already satisfied: python-dateutil in /opendevin/miniforge3/lib/python3.10/site-packages (from dateparser->python-binance) (2.9.0.post0)
Requirement already satisfied: pytz in /opendevin/miniforge3/lib/python3.10/site-packages (from dateparser->python-binance) (2024.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /opendevin/miniforge3/lib/python3.10/site-packages (from dateparser->python-binance) (2024.7.24)
Requirement already satisfied: tzlocal in /opendevin/miniforge3/lib/python3.10/site-packages (from dateparser->python-binance) (5.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opendevin/miniforge3/lib/python3.10/site-packages (from requests->python-binance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opendevin/miniforge3/lib/python3.10/site-packages (from requests->python-binance) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opendevin/miniforge3/lib/python3.10/site-packages (from requests->python-binance) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /opendevin/miniforge3/lib/python3.10/site-packages (from requests->python-binance) (2024.2.2)
WARNING: Ignoring invalid distribution -ytz (/opendevin/miniforge3/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ytz (/opendevin/miniforge3/lib/python3.10/site-packages)
Note: you may need to restart the kernel to use updated packages.

19:37:05 - OBSERVATION
**IPythonRunCellObservation**
[Package already installed]


==============
CodeActAgent LEVEL 0 LOCAL STEP 1 GLOBAL STEP 1

19:37:08 - opendevin:INFO: llm.py:181 - Cost: 0.02 USD | Accumulated Cost: 0.04 USD
19:37:08 - ACTION
**IPythonRunCellAction**
THOUGHT: Great! Since the `python-binance` library is already installed, let's proceed with creating the Python script for the trading bot.

I'll create a file named `trading_bot.py` and add the initial code to set up the Binance client and fetch market data.
CODE:
create_file('trading_bot.py')
19:37:08 - OBSERVATION
**IPythonRunCellObservation**
[File: /workspace/trading_bot.py (1 lines total)]
(this is the beginning of the file)
1|
(this is the end of the file)
[File trading_bot.py created.]



==============
CodeActAgent LEVEL 0 LOCAL STEP 2 GLOBAL STEP 2

19:37:20 - opendevin:INFO: llm.py:181 - Cost: 0.02 USD | Accumulated Cost: 0.07 USD
19:37:20 - ACTION
**IPythonRunCellAction**
THOUGHT: Let's start by adding the initial code to set up the Binance client and fetch market data. We'll need to use your Binance API key and secret. Please provide them, or if you prefer, you can set them as environment variables.

For now, I'll add the basic structure of the script:
CODE:
EDITED_CODE = """import os
from binance.client import Client

# Set up the Binance client
api_key = os.getenv('BINANCE_API_KEY')
api_secret = os.getenv('BINANCE_API_SECRET')
client = Client(api_key, api_secret)

# Fetch market data
def get_market_data(symbol):
    try:
        ticker = client.get_ticker(symbol=symbol)
        return ticker
    except Exception as e:
        print(f"An error occurred: {e}")
        return None

if __name__ == '__main__':
    symbol = 'BTCUSDT'
    market_data = get_market_data(symbol)
    if market_data:
        print(market_data)
"""

insert_content_at_line('trading_bot.py', 1, EDITED_CODE)
19:37:20 - OBSERVATION
**IPythonRunCellObservation**
[File: /workspace/trading_bot.py (22 lines total after edit)]
(this is the beginning of the file)
1|import os
2|from binance.client import Client
3|
4|# Set up the Binance client
5|api_key = os.getenv('BINANCE_API_KEY')
6|api_secret = os.getenv('BINANCE_API_SECRET')
7|client = Client(api_key, api_secret)
8|
9|# Fetch market data
10|def get_market_data(symbol):
11|    try:
12|        ticker = client.get_ticker(symbol=symbol)
13|        return ticker
14|    except Exception as e:
15|        print(f"An error occurred: {e}")
16|        return None
17|
18|if __name__ == '__main__':
19|    symbol = 'BTCUSDT'
20|    market_data = get_market_data(symbol)
21|    if market_data:
22|        print(market_data)
(this is the end of the file)
[File updated (edited at line 1). Please review the changes and make sure they are correct (correct indentation, no duplicate lines, etc). Edit the file again if necessary.]



==============
CodeActAgent LEVEL 0 LOCAL STEP 3 GLOBAL STEP 3

19:37:26 - opendevin:INFO: llm.py:181 - Cost: 0.02 USD | Accumulated Cost: 0.09 USD
19:37:26 - ACTION
**CmdRunAction (source=EventSource.AGENT)**
THOUGHT: The initial setup for the trading bot is complete. Now, let's run the script to ensure it fetches market data correctly. Please make sure your Binance API key and secret are set as environment variables `BINANCE_API_KEY` and `BINANCE_API_SECRET`.

Let's run the script:
COMMAND:
python3 trading_bot.py
19:37:26 - OBSERVATION
**CmdOutputObservation (source=EventSource.AGENT, exit code=1)**
Traceback (most recent call last):
  File "/workspace/trading_bot.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'


==============
CodeActAgent LEVEL 0 LOCAL STEP 4 GLOBAL STEP 4

19:37:34 - opendevin:INFO: llm.py:181 - Cost: 0.02 USD | Accumulated Cost: 0.11 USD
19:37:34 - ACTION
**IPythonRunCellAction**
THOUGHT: It seems there is an issue with the `python-binance` library. Let's ensure it is installed correctly and try again.

First, let's verify the installation of the `python-binance` library:
CODE:
%pip show python-binance
19:37:36 - OBSERVATION
**IPythonRunCellObservation**
WARNING: The directory '/home/opendevin/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -ytz (/opendevin/miniforge3/lib/python3.10/site-packages)
Name: python-binance
Version: 1.0.19
Summary: Binance REST API python implementation
Home-page: https://github.com/sammchardy/python-binance
Author: Sam McHardy
Author-email:
License: MIT
Location: /opendevin/miniforge3/lib/python3.10/site-packages
Requires: aiohttp, dateparser, pycryptodome, requests, six, ujson, websockets
Required-by:
Note: you may need to restart the kernel to use updated packages.



==============
CodeActAgent LEVEL 0 LOCAL STEP 5 GLOBAL STEP 5

19:37:44 - opendevin:INFO: llm.py:181 - Cost: 0.03 USD | Accumulated Cost: 0.14 USD
19:37:44 - ACTION
**IPythonRunCellAction**
THOUGHT: The `python-binance` library is installed correctly. However, it seems there might be an issue with the environment. Let's try restarting the kernel to ensure the package is properly recognized.

I'll restart the kernel now.
CODE:
import os
os._exit(0)
