### ISSUE TITLE
[Bug]: stat: cannot statx '/var/run/docker.sock': No such file or directory

### ISSUE THREAD

**Issue by nasirkhansafi** [All-Hands-AI/OpenHands#3170]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

in the windows docker environment when the docker is sun it gives Error 
stat: cannot statx '/var/run/docker.sock': No such file or directory

$ docker run -it     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name opendevin-app-$(date +%Y%m%d%H%M%S)     ghcr.io/opendevin/opendevin
e +%Y%m%d%H%M%S)     ghcr.io/opendevin/opendevin;0aa55ac0-587b-436f-8269-2d4e61bc4a82latest: Pulling from opendevin/opendevin
Digest: sha256:ecb9f793d304e2127a99da8ce6c4418f2459fb0f0eafb25b5a4146d73e134c40
Status: Image is up to date for ghcr.io/opendevin/opendevin:latest
Starting OpenDevin...
Setting up enduser with id 197609
stat: cannot statx '/var/run/docker.sock': No such file or directory

### Current OpenDevin version

```bash
latest
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Operating System

windows 10

**Comment by tobitege** [comment]
OpenDevin is not supported on Windows, only WSL.

**Comment by mamoodi** [comment]
@nasirkhansafi were you using WSL on Windows?

**Comment by brendanboyle87** [comment]
Do you actually have a wsl2 distro installed? / WSL2 enabled in your docker desktop settings? I hit similar until I downloaded an Ubunto distro and configured 

https://learn.microsoft.com/en-us/windows/wsl/basic-commands#set-wsl-version-to-1-or-2

![image](https://github.com/user-attachments/assets/df206341-b488-4549-ba98-d81d73429aab)

![image](https://github.com/user-attachments/assets/155023ba-3a66-408b-8756-9b13430a2298)
