### ISSUE TITLE
[Bug]: long running commands and commands that are interactive

### ISSUE THREAD

**Issue by zenitogr** [All-Hands-AI/OpenHands#3176]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I think there is a problem with running tasks with opendevin, when I run npm run dev it runs succesfully but there is no output until the timeout is hit and I see the output but it sigkills the command

### Current OpenDevin version

```bash
ghcr.io/opendevin/opendevin
```

### Installation and Configuration

```bash
local llm with LM-Studio
docker

#!/usr/bin/env sh
# Define variables
WORKSPACE_BASE=$(pwd)/workspace;
SANDBOX_USER_ID=$(id -u)
PERSIST_SANDBOX="true"
SSH_PASSWORD="sshpassword"
IMAGE_NAME="ghcr.io/opendevin/opendevin"
CONTAINER_PORT=3000
HOST_PORT=3000 
NAME=opendevin-app-$(date +%Y%m%d%H%M%S)
echo "$NAME\n" >> "docker_container_names.txt"
# Run the Docker container
docker run -it \
    --pull=always \
    -e SANDBOX_TIMEOUT=120 \
    -e SANDBOX_USER_ID=$SANDBOX_USER_ID \
    -e LLM_MODEL="openai/<your-model-name-from-lm-studio>" \
    -e LLM_BASE_URL="http://host.docker.internal:1234/v1" \
    -e LLM_API_KEY="lm-studio" \
    -e CUSTOM_LLM_PROVIDER="openai" \
    -e PERSIST_SANDBOX=$PERSIST_SANDBOX \
    -e SSH_PASSWORD=$SSH_PASSWORD \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p $HOST_PORT:$CONTAINER_PORT \
    --add-host host.docker.internal:host-gateway \
    --name $NAME \
    $IMAGE_NAME
```
```


### Model and Agent

lmstudio-community/Llama-3-Groq-8B-Tool-Use-GGUF
CodeAct

### Operating System

windows 11

### Reproduction Steps

1. run the script
2. install node
3. (because there is this bug I run the command with non interactive way) npx create-next-app my-next-app --ts --app --eslint --import-alias "@/*" --use-npm --tailwind --no-src-dir
4. cd /workspace/my-next-app
5. npm run dev

the command runs succesfully but there is no output until the timeout hits and the output is shown and the command is killed with sigkill saying it timedout

### Logs, Errors, Screenshots, and Additional Context

there should be a way to run long running tasks like npm run dev and interactive commands like npx create-next-app

**Comment by zenitogr** [comment]
for anyone who want to create a nextjs app here is the noninteractive way:
`npx create-next-app my-app-name --ts --app --eslint --import-alias "@/*" --use-npm --tailwind --no-src-dir`
you basicly pass all the options you want BUT you must pass all of them with --no- if you dont want them or --flag if you want them. I would just create-next-app in my wsl if you are using wsl and call it a day

**Comment by SmartManoj** [comment]
You can increase the `SANDBOX_TIMEOUT` config. Currently, you set the default value (120 (2 minutes)) only.

**Comment by zenitogr** [comment]
> You can increase the `SANDBOX_TIMEOUT` config. Currently, you set the default value (120 (2 minutes)) only.

thats a non solution as the terminal in opendevin is noninteractive, doesnt show the ouput of the prompt and doesnt allow for long running commands to exist in the opendevin context and understanding.

for example I would like to ask openedevin to test if my app works by running npm run dev then openning the browser and click on register and input a new username and password and click register and see if it is successfull

right now I need to do all that by myself

**Comment by SmartManoj** [comment]
> You can increase the `SANDBOX_TIMEOUT` config. Currently, you set the default value (120 (2 minutes)) only.

This is a workaround for long-running commands only.

**Comment by zenitogr** [comment]
> The agent can run `npm run dev` in the background and do the remaining tasks too.

my interface locks the agent is not running anything in my local llm ollama experience so there must be a bug when using my setup or local llms or ollama

**Comment by SmartManoj** [comment]
Could you check whether [this PR](https://github.com/OpenDevin/OpenDevin/pull/2927) works for you?

**Comment by zenitogr** [comment]
Can i use a env variable? Dont want to mess with thr code of opendevin

**Comment by imkebe** [comment]
I encountered same issue. Also with the node and npm. When i just ask the using multiple models (llama3.1, phi3, etc) to run it in dev mode. First it don't know how to install npm. If added it as a requirement in prompt the installation command was in the command line but it never ended. After the night i resumed the session and asked "What is the result" it didn't manage to go further.

Similar issue was with listing project files. It was providing some sophisticated command using awk, grep etc. and didn't manged to execute it in reasonable time. I was thinking that there is a ollama running but not. Nothing in logs. Just some wasted time while doing nothing... 

Running on my Macbook Pro M2 Pro - i had all necessary resources.
