### ISSUE TITLE
[Evaluation] Integrate Aider Editing Benchmark

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#3183]
**What problem or use case are you trying to solve?**

Integrate [Aider Editing Benchmark](https://github.com/paul-gauthier/aider/blob/main/benchmark/README.md). This will allow us to develop better editing approach without running the full SWE-bench.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

Similar to other benchmarks in `evaluation/`.

**Describe alternatives you've considered**

**Additional context**

**Comment by RajWorking** [comment]
I am working on this. Please assign it to me :)
