### ISSUE TITLE
[Bug]: OpenDevin stuck at initializing agent

### ISSUE THREAD

**Issue by prokemal2012** [All-Hands-AI/OpenHands#3194]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

when I start up the server it gets stuck at initializing agent. The way I downloaded it is by the command in the readme file.

This is what i get when i execute the command: 

latest: Pulling from opendevin/opendevin
Digest: sha256:ecb9f793d304e2127a99da8ce6c4418f2459fb0f0eafb25b5a4146d73e134c40
Status: Image is up to date for ghcr.io/opendevin/opendevin:latest
Starting OpenDevin...
Setting up enduser with id 501
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
15:46:33 - opendevin:INFO: config.py:437 - Config file not found: [Errno 2] No such file or directory: 'config.toml'
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)

### Current OpenDevin version

```bash
I am using the latest version of Open Devin
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin
```

### Operating System

MacOS

**Comment by mamoodi** [comment]
Hello. So if I understand correctly, when you visit: http://0.0.0.0:3000/

It just says "Initializing Agent" and just stays like that?

Since you're on Mac, did you:
Allow the default Docker socket to be used under Settings > Advanced in Docker Desktop
![Screenshot 2024-07-31 at 3 19 11 PM](https://github.com/user-attachments/assets/17a355a2-e479-42e2-b806-bca2d9f99aac)
