### ISSUE TITLE
[Edit] Improve edit prompt so agent is aware of max output token limit

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#3214]
**What problem or use case are you trying to solve?**

Hit a case where the agent tries to perform a very lengthy edit, but its output got truncated due to LLM's `max_output_tokens` hence causing syntax error:
https://www.all-hands.dev/share-opendevin?share_id=c6a56077d6326398c672a1c8f1d17e3a6f9864846765f141f1e8e95f75f60ace&password=9PAJW79cCVczHXNc

**Describe the UX of the solution you'd like**

- Either prompt the agent to perform a shorter edit
- Figure out a way to change the edit, e.g., using the `>>>>>SEARCH` `>>>>>REPLACE` block used by Aider, so we can detect in-complete edits and feed it to the model again to complete it.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
Not stale
