### ISSUE TITLE
[Mega Issue] Agent Quality: Editing

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#3231]
**What problem or use case are you trying to solve?**

OpenDevin hits a bunch of issues when trying to perform edits:
- [ ] https://github.com/OpenDevin/OpenDevin/issues/3214
- [ ] Repeatedly failed to edit: https://opendevin.slack.com/archives/C06R25BT5B2/p1722547184048369

**Describe the UX of the solution you'd like**

Integrate / Build a light-weight evaluation for editing:
- [x] https://github.com/OpenDevin/OpenDevin/issues/3183
- [x] https://github.com/OpenDevin/OpenDevin/pull/2685#discussion_r1659651873

(Longer-term) Collect data and train a specialized model for editing
- [ ] https://github.com/OpenDevin/OpenDevin/issues/1854

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by neubig** [comment]
Here is an example of a prompt that causes lots of editing issues: https://www.all-hands.dev/share-opendevin?share_id=4e4841bd6240dc2ee334742dee59f5104b5c982ff9309aaeea5ce977968bfcf3

**Comment by li-boxuan** [comment]
Related issue: https://github.com/OpenDevin/OpenDevin/issues/3412

**Comment by tobitege** [comment]
Related issue: #3452

**Comment by James4Ever0** [comment]
Editing can be implemented as Terminal or GUI agent operations. For example:

- Instruct the Terminal agent to use an editor like `nano` or `vim`
- Instruct the GUI agent to use an IDE like `vscode` or `Jetbrains IDEA`

**Comment by neubig** [comment]
Interesting @James4Ever0 ! Have you compared the performance of something like this compared to other methods like the ones implemented in OpenHands or SWE-Agent?

**Comment by James4Ever0** [comment]
> Interesting @James4Ever0 ! Have you compared the accuracy of something like this compared to other methods like the ones implemented in OpenHands or SWE-Agent?

Benchmarking has not yet been done since this is just a library to interact with terminal and the actual terminal agent implementation is the most important factor in performance.

This method is promising since it allows direct interaction with almost all terminal programs, including those rendering complex graphics (like gameplay and QR codes) and layouts.

**Comment by mamoodi** [comment]
We've made a lot of good progress on this generally. @xingyaoww or @enyst do we feel like this is resolved?

**Comment by xingyaoww** [comment]
Let's close it for now since editing has got a lot better since new sonnet
