### ISSUE TITLE
[Bug]: not able to start opendevin on macos

### ISSUE THREAD

**Issue by KMJ-007** [All-Hands-AI/OpenHands#3258]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

![image](https://github.com/user-attachments/assets/678e6f70-799c-4d6c-bd79-060ff5eb7a12)

### Current OpenDevin version

```bash
opendevin:0.8
```

### Installation and Configuration

```bash
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

### Model and Agent

i didn't get chance, cuz it didn't started

### Operating System

macos

### Reproduction Steps

1.just run the command to start it
```bash
 WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8

```
2. open localhost, and wait and suddenly it shows the error from docker desktop

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/user-attachments/assets/cf64bcbf-1707-4e7a-9e2d-fc6818d5dc88)

**Comment by sdmorrey** [comment]
I’m seeing the same thing. MacBook Pro 2018 with Intel chipset.

**Comment by mamoodi** [comment]
Can you update your docker desktop to the latest and make sure this settings is set in the Advanced settings?

![Screenshot 2024-08-06 at 11 38 23 AM](https://github.com/user-attachments/assets/5bfe3d83-7ed3-427a-a9e1-f43d583ed0c5)

**Comment by sdmorrey** [comment]
That seems to have done it. Sadly I've got a new error:

```
Digest: sha256:ecb9f793d304e2127a99da8ce6c4418f2459fb0f0eafb25b5a4146d73e134c40
Status: Downloaded newer image for ghcr.io/opendevin/opendevin:latest
Starting OpenDevin...
Setting up enduser with id 501
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
07:30:35 - opendevin:INFO: config.py:437 - Config file not found: [Errno 2] No such file or directory: 'config.toml'
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     192.168.65.1:28838 - "GET /static/splash.png HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:52239 - "GET /static/splash.png HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:23528 - "GET /static/favicon.png HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:38331 - "GET /manifest.json HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:52239 - "GET /api/config HTTP/1.1" 401 Unauthorized
INFO:     192.168.65.1:52239 - "GET /_app/immutable/nodes/26.a7066c5c.js HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:52239 - "GET /_app/version.json HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:52239 - "GET /_app/version.json HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:25282 - "GET /opensearch.xml HTTP/1.1" 404 Not Found
```

I started it using this command (taken from Readme.md page of repo):
```
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:latest
```

**Comment by sdmorrey** [comment]
I was able to solve this. I had Ollama started without "ollama serve" it seems to be working now.

**Comment by mamoodi** [comment]
@KMJ-007 can you try the above suggestions as well and see if it works for you?

**Comment by KMJ-007** [comment]
what info i can provide more which will help in debugging this?

i tried on my friend's mac also facing the same issue their also

we both have same mac m1 air

**Comment by mamoodi** [comment]
Please provide your docker desktop version.
Then when you run the docker command to start OpenDevin, please copy the terminal output and post it here. I'll see if I can get someone to help out.

**Comment by neubig** [comment]
Yeah, sorry about the inconvenience @KMJ-007 , we'll try to help out with more details.
