### ISSUE TITLE
[Bug]: Not starting on Macos M1 with stock commands

### ISSUE THREAD

**Issue by tychezone** [All-Hands-AI/OpenHands#3281]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Running the stock docker command, I get the following in the container shell:

session.py:116 - Error creating controller: Failed to source /opendevin/bash.bashrc and ~/.bashrc with exit code 1 and output: -bash: /opendevin/bash.bashrc: No such file or directory

### Current OpenDevin version

```bash
0.8
```

### Installation and Configuration

```bash
Base confif
```

### Model and Agent

GPT-4o

### Operating System

Macos 15.1 Developer beta

### Reproduction Steps

Run stock command

**Comment by neubig** [comment]
Hey @tychezone, I tried to reproduce this and am having a different issue, but similarly the docker command is not working. I'm pasting the full log below.
[log.txt](https://github.com/user-attachments/files/16562471/log.txt)

Normally I'd try to debug further, but we're about to release v. 0.9 which will change a lot of things regarding how docker is managed (hopefully making things simpler), so I think we should probably revisit this when that happens, maybe early next week.

**Comment by neubig** [comment]
Actually NVM, I just had to wait longer and it worked fine out of the box for me. Nonetheless, my comment still stands, I hope that 0.9 will resolve this issue.

**Comment by tychezone** [comment]
@neubig when you say it worked fine, do you mean you were able to start the webserver? I can successfully start the webserver, the bug appears only _after_ you set your prefernces on the first popup for model and agent selection. Here's the log:

0.8: Pulling from opendevin/opendevin
Digest: sha256:ecb9f793d304e2127a99da8ce6c4418f2459fb0f0eafb25b5a4146d73e134c40
Status: Image is up to date for ghcr.io/opendevin/opendevin:0.8
Starting OpenDevin...
Setting up enduser with id 503
Docker socket group id: 0
root:x:0:
Group with id 0 already exists
Running as enduser
/app/.venv/lib/python3.12/site-packages/llama_cloud/types/metadata_filter.py:20: SyntaxWarning: invalid escape sequence '\*'
  """
02:14:09 - opendevin:INFO: config.py:437 - Config file not found: [Errno 2] No such file or directory: 'config.toml'
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     192.168.65.1:64913 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.65.1:64913 - "GET /assets/index-CKCRqlAe.js HTTP/1.1" 200 OK
INFO:     192.168.65.1:20879 - "GET /assets/index-Cm23Fd0t.css HTTP/1.1" 200 OK
INFO:     192.168.65.1:64913 - "GET /favicon-32x32.png HTTP/1.1" 200 OK
INFO:     192.168.65.1:20879 - "GET /locales/en-US/translation.json HTTP/1.1" 404 Not Found
INFO:     192.168.65.1:44997 - "GET /locales/en/translation.json HTTP/1.1" 200 OK
INFO:     192.168.65.1:44997 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     192.168.65.1:59652 - "GET /site.webmanifest HTTP/1.1" 200 OK
INFO:     192.168.65.1:44997 - "GET /api/options/agents HTTP/1.1" 200 OK
INFO:     ('192.168.65.1', 57767) - "WebSocket /ws" [accepted]
INFO:     connection open
02:15:25 - opendevin:INFO: agent.py:79 - Using runtime: server
02:15:25 - opendevin:INFO: ssh_box.py:135 - SSHBox is running as opendevin user with USER_ID=503 in the sandbox
02:15:25 - opendevin:INFO: ssh_box.py:178 - Detected initial session.
02:15:25 - opendevin:INFO: ssh_box.py:180 - Creating new Docker container
02:15:25 - opendevin:WARNING: ssh_box.py:578 - Using port forwarding till the enable host network mode of Docker is out of experimental mode.Check the 897th issue on https://github.com/OpenDevin/OpenDevin/issues/ for more information.
02:15:25 - opendevin:INFO: ssh_box.py:586 - Mounting volumes: {'/Users/callmenuwanda/workspace': {'bind': '/workspace', 'mode': 'rw'}, '/tmp/cache': {'bind': '/home/opendevin/.cache', 'mode': 'rw'}}
02:15:25 - opendevin:INFO: ssh_box.py:597 - Container started
02:15:26 - opendevin:INFO: ssh_box.py:613 - waiting for container to start: 1, container status: running
02:15:28 - opendevin:INFO: ssh_box.py:342 - Connecting to SSH session...
02:15:28 - opendevin:INFO: ssh_box.py:345 - You can debug the SSH connection by running: `ssh -v -p 56747 opendevin@localhost` using the password '6646d3f6-2266-4c4f-bd74-4ba52956188b'
02:15:29 - opendevin:INFO: ssh_box.py:349 - Connected to SSH session
02:15:31 - opendevin:INFO: agent.py:100 - Creating agent CodeActAgent using LLM gpt-4o
02:15:31 - opendevin:INFO: mixin.py:42 - Initializing plugins in the sandbox
02:15:32 - opendevin:ERROR: session.py:116 - Error creating controller: Failed to source /opendevin/bash.bashrc and ~/.bashrc with exit code 1 and output: -bash: /opendevin/bash.bashrc: No such file or directory
Traceback (most recent call last):
  File "/app/opendevin/server/session/session.py", line 106, in _initialize_agent
    await self.agent_session.start(
  File "/app/opendevin/server/session/agent.py", line 55, in start
    await self._create_controller(
  File "/app/opendevin/server/session/agent.py", line 110, in _create_controller
    self.runtime.init_sandbox_plugins(agent.sandbox_plugins)
  File "/app/opendevin/runtime/server/runtime.py", line 93, in init_sandbox_plugins
    self.sandbox.init_plugins(plugins)
  File "/app/opendevin/runtime/plugins/mixin.py", line 53, in init_plugins
    _source_bashrc(self)
  File "/app/opendevin/runtime/plugins/mixin.py", line 27, in _source_bashrc
    raise RuntimeError(
RuntimeError: Failed to source /opendevin/bash.bashrc and ~/.bashrc with exit code 1 and output: -bash: /opendevin/bash.bashrc: No such file or directory
