### ISSUE TITLE
[Documentation]: config.toml options should be documented on the doc web site

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3325]
**What problem or use case are you trying to solve?**

It seems that there is no documentation on all the options available to configure OpenDevin on the documentation web site: https://github.com/All-Hands-AI/OpenHands/tree/main/docs

**Describe the UX of the solution you'd like**

It would be ideal if we could get some documentation on the web site.

**Do you have thoughts on the technical implementation?**

This should be created as its own page, and also added to the appropriate place in sidebars.ts: https://github.com/All-Hands-AI/OpenHands/blob/main/docs/sidebars.ts

To figure out what configuration options are available, we can look at the following file:
https://github.com/All-Hands-AI/OpenHands/blob/1109637efbe72b524473f0a4a4b84bbc74db3764/openhands/core/schema/config.py#L4

**Comment by mamoodi** [comment]
The template is helpful: https://github.com/OpenDevin/OpenDevin/blob/main/config.template.toml

I agree though, there's a lot of configs that can be changed and we need some source of truth for those configs.

**Comment by JanumalaAkhilendra** [comment]
i want to work on this issue , if it is still open , please assign it to me . 
Thank you :)

**Comment by neubig** [comment]
Hey @JanumalaAkhilendra , ok, thanks!

**Comment by Mr-Imperium** [comment]
Working on it.
