### ISSUE TITLE
[Feature]: Support for prompt caching

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3397]
**What problem or use case are you trying to solve?**

Prompt caching makes it possible to cache the previous parts of the prompts and make it much faster and less expensive to process long prompts. It would be great if we could reap the benefits.

**Describe the UX of the solution you'd like**

Prompt cacheing just works, the user doesn't have to think about it.

**Do you have thoughts on the technical implementation?**

This will soon be supported by litellm, so we can turn it on:

* https://github.com/BerriAI/litellm/issues/5207

This is supported by several language models:

Anthropic: https://www.anthropic.com/news/prompt-caching
Gemini: https://ai.google.dev/gemini-api/docs/caching

We'll also have to examine the prompts by our various agents and see if they are conducive to caching. The prefix will need to stay the same.

A good first place to add this would be in CodeActAgent here: https://github.com/OpenDevin/OpenDevin/blob/50b1256c49739cfc854c048495268eda2d298773/agenthub/codeact_agent/codeact_agent.py#L208-L216

**Comment by RajWorking** [comment]
Taking a look at this.

**Comment by yufansong** [comment]
Related version upgrade patch #3403
