### ISSUE TITLE
[Bug]: clear docs of ssh_box and image_agnostic_util references (fr, zh-Hans)

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#3432]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The `fr` and `zh-Hans` documentation files for `custom_sandbox_guide.md` need references to `ssh_box.py` and `image_agnostic_util.py` being removed or rewritten.

https://github.com/OpenDevin/OpenDevin/blob/6e70f79bf4977a47ffdda00753fa56b5a17eae19/docs/i18n/fr/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md

https://github.com/OpenDevin/OpenDevin/blob/6e70f79bf4977a47ffdda00753fa56b5a17eae19/docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md

**Comment by WannaTen** [comment]
I can refer to the link "https://github.com/All-Hands-AI/OpenHands/blob/main/docs/modules/usage/how-to/custom-sandbox-guide.md" to modify the corresponding zh-Hans part

**Comment by enyst** [comment]
It looks like this was solved by the linked PR, closing. @tobitege please feel free to re-open if it's not yet fixed.
