### ISSUE TITLE
Send backend steps messages during initialization to UI

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#3440]
**What problem or use case are you trying to solve?**

The initialization phase after opening OD in the browser and then starting a new session can now take way longer than the displayed 10 seconds. It's more like 30 seconds (with no local images present on a fast machine) and there's no extra info updates keeping the user informed of what is going on.

**Describe the UX of the solution you'd like**

I'd like to propose a more granular "sub status" message appearing below the current "Initializing agent..." message that actually lets the user know what step is currently being performed, like "Pulling image", "Creating runtime container" etc.

**Do you have thoughts on the technical implementation?**

The backbone, i.e. client runtime, would need to send multiple status messages throughout the different methods it's going through with probably an extra message type.

**Comment by maxcurrent420** [comment]
I would also like some status/debugging messages as the initializing agent phase does not seem to complete for me. Now when I try to open the configuration setting for the llm it just says to wait while the agent loads "this may take a few seconds". Is it supposed to take :infinity: ?

**Comment by enyst** [comment]
Sorry @maxcurrent420, it currently does take indeed much more than 10 seconds. Also please see https://github.com/All-Hands-AI/OpenHands/issues/3898

If it still doesn't seem to do anything for minutes, please open a new issue, with your configuration/operating system, so we can figure it out.

**Comment by tobitege** [comment]
Fixed by #3771
