### ISSUE TITLE
[Bug]: Invalid Token, Can't find Claude as a Model

### ISSUE THREAD

**Issue by DibakarBala** [All-Hands-AI/OpenHands#3475]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Have been trying to install OpenHands for the last 48 hours but now finally giving up since i can't get past this error. It just won't connect with any LLM Api.

### Current OpenHands version

```bash
0.8.3
```

### Installation and Configuration

```bash
Ran this in Ubuntu
WORKSPACE_BASE=/mnt/d/OpenDevin/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.8
```

### Model and Agent

Anthropic Claude Sonnet 3.5

### Operating System

Windows

### Reproduction Steps

Could be system specific. I just followed the standard installation guide

### Logs, Errors, Screenshots, and Additional Context

![Screenshot 2024-08-19 231810](https://github.com/user-attachments/assets/1d63611f-41f5-4f8c-9594-28bda34b5ccb)

**Comment by crypdick** [comment]
it could be unfortunate timing with all the PRs currently getting merged in to rename the repo from OpenDevin to OpenHands https://github.com/All-Hands-AI/OpenHands/pull/3474
