### ISSUE TITLE
[Refactor]: Remove relative imports

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3491]
**Summary**

In most places in the library we are using absolute imports, which are a bit easier to understand. However, there is at least one place (probably more) where we are using relative imports: https://github.com/All-Hands-AI/OpenHands/blob/0a3d46a90b4a390180d33381c94cc98c88e36f48/openhands/events/stream.py#L12

We could:
1. search for all relative imports in the code
2. replace them with absolute imports

**Comment by tobitege** [comment]
That's ~63 files 😁

**Comment by Ma-hawaj** [comment]
Can I work on this ?

**Comment by tobitege** [comment]
> Can I work on this ?

Yes, please do! 👍
