### ISSUE TITLE
Move `test_runtime.py` out of test folder

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#3504]
The `test_runtime.py`, which started as a unit test, is now run in a special workflow and explicitly excluded from unit tests workflow.

Suggested actions:
- move the file into a different folder (and/or rename it)
- adapt its call in `ghcr_runtime` workflow accordingly:

https://github.com/All-Hands-AI/OpenHands/blob/a7dfd5b9facc5726369152d10853c99df3c5c88e/.github/workflows/ghcr_runtime.yml#L194

- adapt unit test workflows to remove occurences of `-k "not test_runtime.py"`:
https://github.com/All-Hands-AI/OpenHands/blob/a7dfd5b9facc5726369152d10853c99df3c5c88e/.github/workflows/py-unit-tests.yml#L85

https://github.com/All-Hands-AI/OpenHands/blob/a7dfd5b9facc5726369152d10853c99df3c5c88e/.github/workflows/py-unit-tests.yml#L114

---

@xingyaoww wrote: "@tobitege on a second note, we should probably move `test_runtime` out of that directory and break it down to multiple files to avoid similar confusions in the future 😄 

_Originally posted by @xingyaoww in https://github.com/All-Hands-AI/OpenHands/issues/3464#issuecomment-2299181355_

**Comment by neubig** [comment]
Hey @tobitege is this done?

**Comment by xingyaoww** [comment]
I think this is completed in #3513
