### ISSUE TITLE
[Bug]: VertexAI integration with Anthropic fails due to missing dependencies

### ISSUE THREAD

**Issue by ttamoud** [All-Hands-AI/OpenHands#3505]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When attempting to use the VertexAI integration with Anthropic in OpenDevin, the application fails due to missing Python dependencies.

## Error Message
The following error is encountered:

```python
ModuleNotFoundError: No module named 'anthropic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2052, in completion
    model_response = vertex_ai_anthropic.completion(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/vertex_ai_anthropic.py", line 268, in completion
    raise VertexAIError(
litellm.llms.vertex_ai_anthropic.VertexAIError: vertexai import failed please run `pip install -U google-cloud-aiplatform "anthropic[vertex]"`

### Current OpenHands version

```bash
used with tag :latest: so i suppose 0.8.3
```

### Installation and Configuration

```bash
Running the command i always run with opendevin, this one : 
WORKSPACE_BASE=/mnt/c/Users/tamou/langchain/workspace && docker run --pull=always -e SANDBOX_USER_ID=$(id -u) -e PERSIST_SANDBOX="true" -e SSH_PASSWORD="12345678" -e GOOGLE_APPLICATION_CREDENTIALS=/mnt/c/Users/tamou/langchain/aerial-valor-428210-u3-e27544061b85.json -e VERTEXAI_PROJECT=aerial-valor-428210-u3 -e VERTEXAI_LOCATION=europe-west1 -e LLM_MODEL=vertex_ai/claude-3-5-sonnet@20240620 -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE -v $WORKSPACE_BASE:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 --add-host host.docker.internal:host-gateway ghcr.io/opendevin/opendevin:latest
```

### Model and Agent

Default config, didnt get to this part since didnt have any answer

### Operating System

WSL on Windows

### Reproduction Steps

1- Set up the Docker environment with VertexAI and Anthropic configurations.
2- Attempt to run the OpenDevin application.
3- Encounter the above error when the application tries to use the VertexAI integration.

### Logs, Errors, Screenshots, and Additional Context

Any guidance on how to properly set up the VertexAI integration with Anthropic in the Docker environment would be greatly appreciated.

**Comment by tobitege** [comment]
Thanks for reporting this @ttamoud ! 
Hopefully we can fix that asap with the above PR.

**Comment by tobitege** [comment]
@ttamoud Please feel free to open this issue in case the updated dependencies don't resolve your issue.
