### ISSUE TITLE
[Bug]: Cant run new (openhands) docker image on linux (Ubuntu0

### ISSUE THREAD

**Issue by PascPeli** [All-Hands-AI/OpenHands#3525]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I run the command as described in the README and I immediately get 

```
0.8: Pulling from all-hands-ai/openhands
Digest: sha256:5d1304a69ffa4f12cd044ffd096e6066eb77ef428b8409cdb1da259ed2789cc2
Status: Image is up to date for ghcr.io/all-hands-ai/openhands:0.8
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /app/entrypoint.sh: exec format error

```

It seems that 0.8 points to an arm64 installation

instead `ghcr.io/all-hands-ai/openhands:main` works as expected

I would suggest correcting the README.

### Current OpenHands version

```bash
latest.
I have tried the previous tag which works perfectly
```

### Installation and Configuration

```bash
Ubuntu 22 
Docker 27
```

**Comment by djl0** [comment]
Same issue for me, on debian

**Comment by KrE80r** [comment]
I see the 0.8 tag is a synonym to arm arch [here](https://github.com/All-Hands-AI/OpenHands/pkgs/container/openhands/versions?filters%5Bversion_type%5D=tagged)

Try using `ghcr.io/all-hands-ai/openhands:0.8_amd64` instead

**Comment by superurbi** [comment]
Using tag :0.8_amd64
I receive this output:
10:15:17 - openhands:INFO: docker.py:75 - Cannot pull image ghcr.io/all-hands-ai/runtime:cd6b943f5c629c94354e38c5f50b15e9 directly

**Comment by tobitege** [comment]
Hey @PascPeli @djl0 @KrE80r 
for the time being, we've changed back the link to the image on the main page back to the old repo.
There're some tech issues we're working on to resolve the issue and change it back when done, just fyi.
