### ISSUE TITLE
[Bug]: openhands-ai Python package requires agenthub

### ISSUE THREAD

**Issue by mattbarlow-sg** [All-Hands-AI/OpenHands#3527]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When attempting to use the openhands-ai package from PyPi, I encounter an issue that `agenthub` cannot be imported. I believe this is because `agenthub` is imported, but it does not exist as part of the package in PyPi.

### Current OpenHands version

```bash
openhands-ai                  0.8.3
```

### Installation and Configuration
I ran `poetry install openhands-ai`, then installed missing dependencies, then attempted to use it. Specifically it is failing on the import of `openhands.core.main`.
```bash


from openhands.controller.state.state import State
from openhands.core.config import AppConfig, SandboxConfig
from openhands.core.main import run_controller
from openhands.runtime import get_runtime_cls
```

### Operating System

MacOS

### Reproduction Steps

1. Clone https://github.com/mattbarlow-sg/openhands-test
2. Run `poetry install`
3. Run `poetry shell`
4. Run `openhands-package`

### Logs, Errors, Screenshots, and Additional Context

```
ERROR:root:  File "/Users/matt.barlow/Library/Caches/pypoetry/virtualenvs/openhands-package-8SiZbAsB-py3.12/bin/openhands-package", line 3, in <module>
    from openhands_package.cli import ai_tools
  File "/Users/matt.barlow/Engineering/openhands-package/openhands_package/__init__.py", line 1, in <module>
    from .cli import main
  File "/Users/matt.barlow/Engineering/openhands-package/openhands_package/cli.py", line 7, in <module>
    from openhands.core.main import run_controller
  File "/Users/matt.barlow/Library/Caches/pypoetry/virtualenvs/openhands-package-8SiZbAsB-py3.12/lib/python3.12/site-packages/openhands/core/main.py", line 7, in <module>
    import agenthub  # noqa F401 (we import this to get the agents registered)
    ^^^^^^^^^^^^^^^

ERROR:root:<class 'ModuleNotFoundError'>: No module named 'agenthub'
```

**Comment by neubig** [comment]
Hey @mattbarlow-sg , this should be fixed in 0.9.0! Please try it again and we'd be happy to help with any residual things.
