### ISSUE TITLE
[Bug]: CLI-capable image does not support MacOS/arm

### ISSUE THREAD

**Issue by Obs01ete** [All-Hands-AI/OpenHands#3544]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The CLI-capable image
https://github.com/all-hands-ai/OpenHands/pkgs/container/openhands
does not support MacOS arm.

### Current OpenHands version

```bash
0.8
```

### Installation and Configuration

```bash
---
```

### Model and Agent

Irrelevant

### Operating System

MacOS arm64

### Reproduction Steps

```
docker run -it \
>     --pull=always \
>     -e SANDBOX_USER_ID=$(id -u) \
>     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
>     -e LLM_API_KEY=$LLM_API_KEY \
>     -e LLM_MODEL=$LLM_MODEL \
>     -v $WORKSPACE_BASE:/opt/workspace_base \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     --add-host host.docker.internal:host-gateway \
>     --name openhands-app-$(date +%Y%m%d%H%M%S) \
>     ghcr.io/all-hands-ai/openhands:main \
>     python -m openhands.core.main \
>     -t "Write a bash script that prints Hello World"
main: Pulling from all-hands-ai/openhands
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

**Comment by tofarr** [comment]
I run it from an M2 - Can you provide any additional error details? (Log output / Screenshots)?

Thanks!

**Comment by Obs01ete** [comment]
The issue is resolved by @SmartManoj. My appreciation!
https://github.com/SmartManoj/Kevin/issues/38#issue-2482339816
