### ISSUE TITLE
[Bug]: Unable to locate npx, npm or node from the terminal in the browser

### ISSUE THREAD

**Issue by GM-dot-one** [All-Hands-AI/OpenHands#3555]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

My local opendevin install is unable to find npx, npm or node from the terminal prompt in the browser. All these are installed on my mac and I can access it through a local terminal. I can't figure out where do I need to put a .bashrc file for the shell to find the path.

<img width="824" alt="image" src="https://github.com/user-attachments/assets/9584576b-48d6-4ed7-93d7-d63e9b2954ca">

<img width="562" alt="image" src="https://github.com/user-attachments/assets/8cb6abf1-a3a9-4642-8a3f-1fc3f06d383c">

<img width="540" alt="image" src="https://github.com/user-attachments/assets/d82d4cf3-6284-4579-8ed8-96e975cb2520">

### Current OpenHands version

```bash
docker run -it     --pull=always     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name opendevin-app-$(date +%Y%m%d%H%M%S)     ghcr.io/opendevin/opendevin:0.8
```

### Installation and Configuration

```bash
I have a config.toml file in my "opendevin" folder. I get an error at startup saying "config.toml" not found.
I can get around this by entering my api-key on the browser.

To recreate the issue, I tried to generate a frontend using Vue.js and opendevin tried to find node, then install it and then failed to find it. 

It seems like both these issues can be fixed by setting PATH in .bashrc. But for the life of me I can't figure out where to make these changes.
```

### Model and Agent

-Model: CodeActAgent
-Agent: gpt-4o

### Operating System

MacOS

**Comment by mamoodi** [comment]
OpenHands runs the sandbox in a container so the environment is different than what you have on your local system.
For example if you have nodejs installed on your mac, it doesn't mean that OpenHands also has it installed. 

That being said, in the main line I believe the sandbox environment is setup with some basic packages so it may have node already installed.

In your docker command if you replace:
`ghcr.io/opendevin/opendevin:0.8` with `ghcr.io/opendevin/opendevin:main`
can you then check if node or npm is installed?
