### ISSUE TITLE
[Bug]: Lots of clutter in the terminal prompts

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#3557]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

There's a ton of info in the terminal prompt that probably doesn't need to be there. We should modify it to give a simple prompt like
```
openhands:/workspace $
```

<img width="768" alt="Screenshot 2024-08-23 at 10 11 52 AM" src="https://github.com/user-attachments/assets/8cb748c6-92f5-49ac-b4b7-c812d433f14f">

### Current OpenHands version

```bash
8d47cebde95dda44a096ee4fa9c99281e6a5f81b
```

### Installation and Configuration

```bash
dev mode
```

### Model and Agent

N/A

### Operating System

OS X

**Comment by tobitege** [comment]
This was added on purpose to give the LLM more info, especially to highlight potential bash and ipython differences.
It's pretty fresh still and I'd suggest we leave this in for at least a couple of weeks to see if the related issues are helped by this.

**Comment by xingyaoww** [comment]
I think the best way is probably modify the `CmdOutputObservation` to include these info (e.g., user, host name, workdir, py interpreter) as a metadata, so we can share this info with the agent (helpful for LLM to figure out different python virtualenv), but not the user.
