### ISSUE TITLE
twai

### ISSUE THREAD

**Issue by WEI567** [All-Hands-AI/OpenHands#3567]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by WEI567** [comment]
不容意

**Comment by neubig** [comment]
It is not clear what this issue means, so I will close it. We'd welcome a more concrete issue!

**Comment by WEI567** [comment]
- I (1)
- heard (2)
- a (3)
- dog (4)
- bark (5)
- loudly (6)
- at (7)
- *("a" is already tokenized as 3)*
- cat (8)
