### ISSUE TITLE
[docs] Create documentation for the CLI mode on the docs site

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#3578]
Maybe we should create documentation for the CLI mode on our docs site?

_Originally posted by @xingyaoww in https://github.com/All-Hands-AI/OpenHands/issues/3564#issuecomment-2309013494_

**Comment by neubig** [comment]
This should be done by https://github.com/All-Hands-AI/OpenHands/pull/3733
