### ISSUE TITLE
[Bug]: File contents do not update in the UI after agent makes an edit to it

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3580]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When the agent makes an edit to the contents of an existing file in the workspace. The contents do not update in the UI, even after clicking the refresh button.

### Current OpenHands version

```bash
0.9.0
```

### Installation and Configuration

```bash
dev mode
```

### Model and Agent

- Model: `openai/gpt-4o`
- Agent: default (`CodeActAgent`)

### Operating System

macOS Sonoma

### Reproduction Steps

1. Create a file or ask OpenHands to create a file in the workspace
2. Look at the contents
3. Ask to make edits (e.g., add comments)
4. UI does not show updates

**Comment by mamoodi** [comment]
Yep. I've noticed this recently as well.
