### ISSUE TITLE
[Documentation] how to set the workspace directory

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3605]
**What problem or use case are you trying to solve?**

I don't think we have any documentation about how to set the workspace directory?

**Describe the UX of the solution you'd like**

It could be documented here for instance: https://docs.all-hands.dev/modules/usage/how-to

**Describe alternatives you've considered**

Alternatively, we could make it more self-explanatory in the frontend.

**Comment by sahilborse** [comment]
@neubig  i would like to work on this issue

**Comment by tobitege** [comment]
> @neubig  i would like to work on this issue
> 

You expressed interest to work on multiple issues now. Please feel free to contribute PR's where you seem fit first and handle them one by one. Thanks!

**Comment by mamoodi** [comment]
Alot has changed in this area. We changed the recommended guidelines but we also have this doc now:
https://docs.all-hands.dev/modules/usage/runtimes#connecting-to-your-filesystem

**Comment by mamoodi** [comment]
Going to close based on the doc link provided above.
