### ISSUE TITLE
Allow to set workspace directory

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3611]
**Summary**
Extend the backend to support setting the workspace directory during initialisation. Right now it is only possible through a variable when starting OpenHands via shell

**Motivation**
In order for the user to select an existing project in their local system through the UI, the backend should support setting it during initialisation

**Technical Design**
Perhaps extending server/session/session.py to accept an absolute path could be enough. It may not be necessary to allow the user to change the directory afterwards

**Alternatives to Consider**

**Additional context**

**Comment by mamoodi** [comment]
This is great as users sometimes have a hard time figuring out what their workspace is set to. Especially if they ran the default docker command in the README.
Ideally, if possible, with this a user can quickly check what the workspace path is set to.

**Comment by amanape** [comment]
CAUTION this may actually be cancelled

**Comment by amanape** [comment]
Handled a simpler way in #3604
