### ISSUE TITLE
Given a GH repo link, clone it into the sandbox

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3627]
**Summary**
Future UI will support the user to select a GH repo they would like to start with (optionally). If that is the case, the sandbox will also have to clone the repo to work with.

**Motivation**
New features and UI

**Technical Design**
The GH repo (`{owner}/{repo}`) could be passed to the backend via the config. This will then be used to clone the project during initialization.

**Things to Consider**
The user will not have direct access to this project in their file system as it will be in a Docker container. This may imply that we would want to create a separate container for each new project.

**Additional Context**
Blocks #3604

**Comment by shubhamofbce** [comment]
This will be a great addition.

**Comment by amanape** [comment]
Moved to #3736
