### ISSUE TITLE
[Bug]: Initial run is very slow for new users

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#3644]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When a new user runs the `docker run` command in our README, it takes a minute or so to download the runtime image

### Current OpenHands version

```bash
0.9
```

### Installation and Configuration

```bash
default install in readme
```

**Comment by amanape** [comment]
Related #3551

**Comment by mamoodi** [comment]
Is this fully resolved now with the PR?

**Comment by tobitege** [comment]
No, not fully, but at least the logging will give a better idea about what steps are taken at startup with regard to pulling/creation of docker images.

**Comment by neubig** [comment]
I'm still interested in helping with this, but I don't want to block others working on it if you're also interested. Basically we can give instructions to set `runtime_container_image` in the docker run command, and that should prevent the image from being built (although it will still be downloaded)

**Comment by tobitege** [comment]
Related #3682 - this brings docker pull progress info
