### ISSUE TITLE
[Bug]: gpt-4o editing accuracy is low

### ISSUE THREAD

**Issue by namastex888** [All-Hands-AI/OpenHands#3679]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

whenever running any task that requires editing an existing file I got infinite loops with the agent trying to edit an existing file.

trying deploying multiple ways (docker wsl and ubuntu wsl directly), read thru the docs, also tried differeent llms.

### Current OpenHands version

```bash
0.9.0 and 0.9.1
```

### Installation and Configuration

```bash
copy paste from readme from docker, make build, make setup-config and make run for the local repo tentative
```

### Model and Agent

default, didnt mess with any advanced settings.

### Operating System

ubuntu on wsl

**Comment by mamoodi** [comment]
Just to be sure, if you didn't change the model, does that mean you are using GPT4?

**Comment by namastex888** [comment]
i tried both gpt-4o and sonnet 3.5, sonnet wouldnt even run. gpt-4o worked, but displayed the issue.

**Comment by neubig** [comment]
Hey @namastex888 , we're working on editing capability and have noticed that recently gpt-4o is not working well. I changed the name of the issue so we can track this more precisely.

Sonnet-3.5 definitely runs (that's what I use all the time), but there might be an issue with the configuration. If you want to open another issue for that we can help.

**Comment by namastex888** [comment]
Thanks for the prompt support, amazing work y'all doing. Will give it a try again shortly. 🙏
