### ISSUE TITLE
[Bug]: Confirmation mode does not work as it is supposed to

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3684]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Enabling confirmation mode from the settings does not prevent the execution of shell commands (before confirmation). In fact, it executes it a second time after confirming.

### Current OpenHands version

```bash
0.9.1
```

### Installation and Configuration

```bash
make build && make run
```

### Model and Agent

N/A

### Operating System

macOS Sonoma

### Reproduction Steps

1. Enable confirmation mode from the settings
2. Ask OpenHands to run a shell command (e.g., "Please run `ls`")
3. Observe how the command has been executed in the terminal before confirming
4. Confirm
5. Observe that the command has been executed for the second time

### Logs, Errors, Screenshots, and Additional Context

<img width="1108" alt="Screenshot 2024-09-01 at 14 33 42" src="https://github.com/user-attachments/assets/32572e98-b461-4a9b-9f8e-2e231eaf282a">

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/fdba3e54-3a5a-4523-bbb0-d7a7e980e297">

**Comment by mbalunovic** [comment]
This issue appears because `EventStreamRuntime` did not implement confirmation mode logic as the old `Runtime`. I addressed it here: https://github.com/All-Hands-AI/OpenHands/pull/3695, it works for me now.
