### ISSUE TITLE
Add an indicator for the cost of usage

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3685]
**What problem or use case are you trying to solve?**
The number of tokens and total cost spent so far is not displayed on the UI.

**Describe the UX of the solution you'd like**
Add a global total indicator (perhaps somewhere on the chat header) and another indicator for each message (in the chat bubble itself)

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhamofbce** [comment]
This will be a great addition.

**Comment by shubhamofbce** [comment]
If anyone is planning to work on this, LiteLLM provides token count and completion count easily. https://docs.litellm.ai/docs/completion/token_usage#6-completion_cost

**Comment by amanape** [comment]
Sure thing @Yashwanth-Chandrakumar, thanks for taking this up
