### ISSUE TITLE
support for CCS 1.0.0-RFC to boost context throughout the codebase

### ISSUE THREAD

**Issue by killerapp** [All-Hands-AI/OpenHands#3690]
# Summary

https://github.com/Agentic-Insights/codebase-context-spec

Please add support for the Codebase Context Specification (CCS) in Aider. CCS allows developers to embed rich contextual information within codebases using standardized `.context.md`, `.context.yaml`, and `.context.json` files. This enhancement will improve Aider's ability to understand project structure, architecture, and conventions, leading to more accurate code suggestions and better AI-assisted development workflows.

# Motivation

## Codebase Context: A New Convention

The Codebase Context Specification introduces a convention similar to `.env` and `.editorconfig` systems, but focused on documenting your code for both AI and humans. Just as `.env` files manage environment variables and `.editorconfig` ensures consistent coding styles, CCS files (`.context.md`, `.context.yaml`, `.context.json`) provide a standardized way to capture and communicate the context of your codebase.

This convention allows developers to:
1. Document high-level architecture and design decisions
2. Explain project-specific conventions and patterns
3. Highlight important relationships between different parts of the codebase
4. Provide context that might not be immediately apparent from the code itself

By adopting this convention, teams can ensure that both human developers and AI assistants have access to crucial contextual information, leading to better code understanding, more accurate suggestions, and improved overall development efficiency.

## Key Concepts

- **Contextual Metadata**: Structured information about the project, its components, and conventions, designed for both human and AI consumption.
- **AI-Human Collaborative Documentation**: Guidelines for creating documentation that's easily parsed by AI models while remaining human-readable and maintainable.
- **Standardized Context Files**: Consistent use of `.context.md`, `.context.yaml`, and `.context.json` files for conveying codebase context at various levels (project-wide, directory-specific, etc.).
- **Context-Aware Development**: Encouraging a development approach that considers and documents the broader context of code, not just its immediate functionality.

# Additional context

https://agenticinsights.substack.com/p/codebase-context-specification-rfc

**Comment by neubig** [comment]
Hi @killerapp , this is not the Aider repository :)

Just to clarify, when you say "support", what would you suggest we do? My guess would be that if you just tell OpenHands "there is a description of the project in `.context.md`", then it would read that file and act based on the information. If you were thinking of something more complex, we could consider this as well.

**Comment by killerapp** [comment]
Yes, that is the most lightweight way of supporting it, the secondary would be something where the tooling adds further support for the other files and provisions. Most notably:

1. support for the .contextignore file - this allows the tree-map to be pruned explicitly. Just telling the model to ignore files already in it's context window is .. dubious at best with the current models. This part of the spec begs for tooling.
2. the other file .contextdocs - this is also a tooling type of thing, yes the model could go and fetch each of the urls and think about them, but this could also be bridged with RAG and explicit agent references to these 'docs bundles' as defined in .contextdocs part of the specification.
3. actively looking for such files and respecting the .contextignore would be benefitical as you are working with a human-in-the-loop.
4. if the tool knows that this is a way to store context, it could allow for better ways to define context and to add it to the codebase easily.
