### ISSUE TITLE
[Bug]: Clicking on a file to display is blocked when the agent is working

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3693]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When the agent is running a task, the user is unable to open any of the files in the workspace.

### Current OpenHands version

```bash
0.9.1
```

### Installation and Configuration

```bash
make build && make run
```

### Model and Agent

N/A

### Operating System

macOS Sonoma

### Reproduction Steps

1. Create a file (or two) in the workspace with some content
2. Ask OpenHands something to perform a task
3. While OpenHands is working, attempt to open the file

**Comment by mamoodi** [comment]
Yep. I've seen this as well. At first I thought it's by design because what would happen if you edited a file while OpenHands was working on it? But I think it's because OpenHands does everything synchronously.

**Comment by xingyaoww** [comment]
I think we can fix this by tweaking this:
https://github.com/All-Hands-AI/OpenHands/blob/d1a741792fe3b7c607e0acd0d47eb8e8a735a51b/openhands/runtime/client/client.py#L492-L498

We can allow endpoint like `/list_file` etc to not hold this lock at all -- the lock was mainly there to make sure we are not executing multiple bash commands at the same time
