### ISSUE TITLE
[Bug]: 403 on Bedrock when using claude-3-5-sonnet-20240620

### ISSUE THREAD

**Issue by tuanardouin** [All-Hands-AI/OpenHands#3708]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I got a similar issue as this : https://github.com/All-Hands-AI/OpenHands/issues/3310

My goal is to use the model Sonnet 3.5 from Anthropic using their API (Not AWS Bedrock).

When selecting this model from Anthropic in the interface, if I want to use Sonnet 3.5 my only choice is to use claude-3-5-sonnet-20240620-v1:0. But I think I should be able to select claude-3-5-sonnet-20240620 as per the doc from l[itellm](https://litellm.vercel.app/docs/providers/anthropic) and the one from [Anthropic](https://docs.anthropic.com/en/docs/about-claude/models#model-names).

I'm going to switch to Bedrock in the meantime, but I don't think I did anything wrong ?

Edit:
I can't use Bedrock also because the model id should be `eu.anthropic.claude-3-5-sonnet-20240620-v1:0`.

Thank you for your help, love your tool!

### Current OpenHands version

```bash
ghcr.io/all-hands-ai/openhands:0.9.1
```

### Installation and Configuration

```bash
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    -e AWS_REGION_NAME=$AWS_REGION_NAME \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3042:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:0.9.1
```

### Model and Agent

- Model : claude-3-5-sonnet-20240620
- Agent : CodeActAgent

### Operating System

MacOS 14.5 (23F79)

### Reproduction Steps

1. Run on any directory
2. Type "test"

### Logs, Errors, Screenshots, and Additional Context
```
INFO:     192.168.65.1:19032 - "GET /api/list-files HTTP/1.1" 200 OK
11:09:20 - USER_ACTION
**MessageAction** (source=EventSource.USER)
CONTENT: Test
11:09:20 - openhands:INFO: session.py:139 - Server event


==============
CodeActAgent LEVEL 0 LOCAL STEP 0 GLOBAL STEP 0


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

11:09:21 - openhands:ERROR: llm.py:128 - litellm.APIConnectionError: {"message":"You don't have access to the model with the specified model ID."}
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1749, in completion
    response.raise_for_status()
  File "/app/.venv/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2333, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1752, in completion
    raise BedrockError(status_code=error_code, message=response.text)
litellm.llms.bedrock.BedrockError: {"message":"You don't have access to the model with the specified model ID."}
. Attempt #1 | You can customize these settings in the configuration.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
```

**Comment by rbren** [comment]
FYI, the correct model is indeed in the "Anthropic" dropdown, as `claude-v2`, but unverified. Not sure if there's a way to pick sonnet specifically...

**Comment by tuanardouin** [comment]
Thanks for your work @amanape
