### ISSUE TITLE
[Bug]: "Verified" Anthropic/Claude model is actually a bedrock version of the mdoel

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#3709]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When you select "Anthropic" as a model provider, and then choose the verified claude model, it seems to try and use bedrock. I repeatedly get a NoCredentialsError

### Current OpenHands version

```bash
0.9
```

### Installation and Configuration

```bash
normal `docker run` steps
```

### Logs, Errors, Screenshots, and Additional Context

```
14:48:04 - openhands:ERROR: agent_controller.py:160 - Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2333, in completion
    response = bedrock_converse_chat_completion.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/bedrock_httpx.py", line 1661, in completion
    sigv4.add_auth(request)
  File "/app/.venv/lib/python3.12/site-packages/botocore/auth.py", line 423, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by mamoodi** [comment]
Duplicate of this: https://github.com/All-Hands-AI/OpenHands/issues/3708?

**Comment by rbren** [comment]
Yup! Thanks
