### ISSUE TITLE
[Refactor]: Simplify AgentController Logic

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3730]
**Summary**

The AgentController logic is very complex, making it difficult to understand. We can refactor it to improve readability.

https://github.com/All-Hands-AI/OpenHands/blob/add4653335218eb04d0b7960fa67c21f8e313b8e/openhands/controller/agent_controller.py#L47

**Comment by WannaTen** [comment]
Hi, Prof.  I'd like to have a try on this,my initial thought is
-  To split 'on_event' into 'action_event' and 'observation_event'
-  To refactor the logic of '_step', which currently contains a large code block

How does that sound?

**Comment by WannaTen** [comment]
@neubig Hi,  I refactored the logic of the AgentController in  #3873 , Could you please review it?

**Comment by enyst** [comment]
This has been addressed by the PR linked above, thank you @WannaTen!

I'll close this issue, @neubig please re-open if you think there is more here.

**Comment by neubig** [comment]
Thanks a lot! There might still be more to do here, but for the time being I think it's much better.
