### ISSUE TITLE
[Frontend]: Add awareness of github projects

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3736]
**What problem or use case are you trying to solve?**

One common workflow that users may have when they interact with OpenHands is to do fixes on github repos. Because of this, we could add some ability to select github repos, add tokens to access the repos, etc.

I think @amanape is working on this.

**Comment by mamoodi** [comment]
Related / Duplicate? https://github.com/All-Hands-AI/OpenHands/issues/3627

**Comment by neubig** [comment]
Fixed by #3604
