### ISSUE TITLE
Open a new event stream / channel dedicated for error messages, notifications, and related data

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#3739]
**Summary**
Create a new event stream / channel in the form of another WebSocket connection or message queue that is dedicated for sharing non-agent related data. Things like error messages, loading indicators, and other notifications of the sort could benefit from a separate channel as it would be sent quickly and without blocking the main event stream (or the other way around)

**Motivation**
We need to find a way to push certain message in the backend that are not being sent to the UI in an efficient manner that does not slow down the main event. For example, an error that is thrown and its details (missing API Key), loading indicators (pulling docker image), and so on

**Technical Design**
Unlike the current event stream, this channel does not have to be bi-directional. As for the actual implementation, the options are another WebSocket path or a message queue-like setup where we can publish and subscribe to the different events

**Alternatives to Consider**

**Additional context**

**Comment by amanape** [comment]
Related #1451

**Comment by rbren** [comment]
Hmm I'm not sure we need a new websocket or EventStream here. Instead, I'd like to figure out why errors aren't propagating immediately over the current WS/ES--is there some reason that they're getting blocked?

**Comment by amanape** [comment]
From [our earlier discussion on Slack](https://openhands-ai.slack.com/archives/C06QKSD9UBA/p1725480493601289), we could change the issue to focus on pushing any and all relevant errors or build indicators to the frontend first and then see how well it handles and what changes we can make to the event stream

**Comment by tobitege** [comment]
@rbren - the EventStreamRuntime is single-task currently, iirc, and our traffic isn't async yet.
