### ISSUE TITLE
Arch: make agent and runtime pluggable

### ISSUE THREAD

**Issue by yufansong** [All-Hands-AI/OpenHands#3753]
**Summary**

We put too much thing in EventStream , so it looks mess now. In order to make OH pluggable, Not only `EventStream`, but also need to simplify the controller logic. 

**Motivation**
Make the module pluggable. If someone want to try his agent, just replace the agent module. If someone want to interact with robot rather than docker, change the runtime module.

For example:
1. Agent (Event+Action+ step logic)
2. Runtime (How to interact with robot)

When we change the above logic, we can change openHands from a code generation platform into robot controll platform.

**Technical Design**

Our current logic:
1. controller will call agent via function call.
2. controller will communicate async with runtime via EventStream
3. runtime will interact with docker via REST API. We implement a docker client inside the docker.

To achieve pluggable, we should optimize the interaction logic between controller with agent and controller with runtime. If we can decouple their logic, we can make agent/runtime as hot plug.

**Alternatives to Consider**

**Additional context**

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by imeDevelopers** [comment]
@yufansong 
You've my support! Same ideas here: [#3758](https://github.com/All-Hands-AI/OpenHands/issues/3758)
