### ISSUE TITLE
Change "WORKSPACE_BASE" environment variable in "Quick Start" docs

### ISSUE THREAD

**Issue by imeDevelopers** [All-Hands-AI/OpenHands#3757]
This [`WORKSPACE_BASE=$(pwd)/workspace`](https://github.com/All-Hands-AI/OpenHands#:~:text=WORKSPACE_BASE%3D%24(pwd)/workspace)

If you run `echo $WORKSPACE_BASE` in terminal it will print nothing! (which means the variable not set.)

It should be `export WORKSPACE_BASE=$(pwd)/workspace`

Now if you run `echo $WORKSPACE_BASE` in terminal it will print `/home/kali/workspace` (which means the variable in now set)

I think this will fix this problem: [Comment #2332238664](https://github.com/All-Hands-AI/OpenHands/issues/3748#issuecomment-2332238664)

**Comment by imeDevelopers** [comment]
@mamoodi 

My way is more comprehensive as if you try it on your environment it will work, but when I try yours on my environment it doesn't work and of course `-e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \`  variable will be certainly empty in that case (while the end-user don't know what is the problem!)

**Comment by mamoodi** [comment]
Updated README and docs. Thank you!
Closing.
