### ISSUE TITLE
Please add the model used and its configuration in the demo video

### ISSUE THREAD

**Issue by cloudbow** [All-Hands-AI/OpenHands#3797]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**
I was uanble to reproduce the demo video in page - https://docs.all-hands.dev/ with the same prompt as shown in the video. I used gpt4o. I got "Agent stuck in a loop" error.  It would be great if the demo video shows what model configuraiton, model used and any other openhands configuration.

https://docs.all-hands.dev/

**Comment by mamoodi** [comment]
Thanks for bringing up this issue. Yes the gpt4o currently has editing issues: https://github.com/All-Hands-AI/OpenHands/issues/3679

I believe the model used in the demo was sonnet3.5

**Comment by mamoodi** [comment]
Did you happen to also press the `thumbs down` button on OpenHands when you encountered the error?
