### ISSUE TITLE
Why do I "must use WSL"?

### ISSUE THREAD

**Issue by MeNicefellow** [All-Hands-AI/OpenHands#3810]
You already use docker. Then why WSL as well??

**Comment by Polygons1** [comment]
I am using it on Windows without WSL

**Comment by MeNicefellow** [comment]
> I am using it on Windows without WSL

They should update their README. Cuz they say for Windows, WSL must be used.

**Comment by enyst** [comment]
WSL must be used, sorry. WSL is a Linux system for Windows, and that's what the project is compatible with.

It might or not work without WSL, but we don't support it, we don't test on it I believe, and we might not be able to help you with it otherwise. I suggest to install WSL and use openhands on it, or a regular Linux.

**Comment by MeNicefellow** [comment]
> WSL is necessary, sorry, for the project to work well. WSL is a Linux system for Windows, and that's what the project is compatible with. openhands works on Mac, Linux, and as for Windows, under WSL.
> 
> In practice, it might or not work without WSL, but we don't support that configuration, we don't have it and don't test on it I believe, and we might not be able to help you with it. I suggest to install WSL and use openhands on it, or a regular Linux.

Why doesn't Docker only work?

**Comment by enyst** [comment]
From what I recall, we've seen problems from the fact that openhands mounts a folder on the local machine, to be its workspace, where it creates files, edits files, deletes stuff etc. On a Windows machine, we have seen issues with libraries, function calls, etc, necessary to do stuff like that. Also, the user the app runs as, the permissions on those files etc, might or not work. I could perhaps add that openhands has two docker containers, one for the external app to run, and another, the runtime that executes the actions.

I believe there are users who use it nevertheless, on Windows without WSL, or have in the past. I don't have a Windows machine and I'm not sure if/what they needed to do or work around. If you want to try it, please feel free to, and I believe we would accept documentation on it. We just don't support it or recommend it.

**Comment by Polygons1** [comment]
> WSL is necessary, sorry, for the project to work well. 

I've tried with WSL first and WSL crashed, that's the only reason I am using it on Windows

**Comment by enyst** [comment]
@Polygons1 Could you please open an issue and fill in the template? As complete as possible, with all information and logs you can, it helps to figure out the problem.

**Comment by Polygons1** [comment]
the problem is that there is nothing, no logs, nothing, just a shutdown of wsl.

**Comment by enyst** [comment]
A shutdown _of WSL_ or do you mean a shutdown of the openhands application?

**Comment by Polygons1** [comment]
of WSL and I think that’s a Docker issue and not OpenHands

**Comment by enyst** [comment]
Yes, that's likely. You can install docker on WSL, and run openhands in WSL.
I understand it can work with docker on Windows and openhands in WSL, I've never tried it, but others have.

Whichever solution you choose, can you try to fix docker so that it works normally then run openhands?

**Comment by Polygons1** [comment]
I think I’ve fixed it now, I don’t know what I did but it worked
