### ISSUE TITLE
[Bug]: No response "Agent is initialized, waiting for task..."

### ISSUE THREAD

**Issue by crazyAI427** [All-Hands-AI/OpenHands#3831]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Hello.
I run open hands docker command in ubuntu terminal.
when I asked some questions, it is not responsed, still "Agent is initialized, waiting for task..."
![123](https://github.com/user-attachments/assets/3663b14e-78a1-47b1-bbca-b691baa26b1c)

and the terminal is like this.
![124](https://github.com/user-attachments/assets/199322b8-5e96-41ad-b167-e09cb9e50378)
How to fix this error?
Thanks

### Current OpenHands version

```bash
ghcr.io/all-hands-ai/openhands:0.9
```

### Installation and Configuration

```bash
export WORKSPACE_BASE=$(pwd)/workspace

docker run -it --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:0.9-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:0.9
```

**Comment by mamoodi** [comment]
Hello! I don't see a particular error. That error restoring session is not fatal.

After you launched OpenHands via the docker command, did you set the `Model` and `API Key`  in the settings menu?

**Comment by crazyAI427** [comment]
> Hello! I don't see a particular error. That error restoring session is not fatal.
> 
> After you launched OpenHands via the docker command, did you set the `Model` and `API Key` in the settings menu?

Yes, of course.

**Comment by amanape** [comment]
UI has been updated, can you check if you're still encountering this issue?

**Comment by crazyAI427** [comment]
Yes, I already solveed, thanks.
