### ISSUE TITLE
[Bug]: <Attribute Error> while running instances for SWE-BENCH instances

### ISSUE THREAD

**Issue by JiseungHong** [All-Hands-AI/OpenHands#3834]
### Is there an existing issue for the same bug?

- [x] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [x] I have checked the existing issues.

### Describe the bug

When [running inference on SWE-BENCH instances](https://github.com/All-Hands-AI/OpenHands/tree/main/evaluation/swe_bench#run-inference-on-swe-bench-instances) with `eval limit` = 300, I encounter an Attribute Error that does not appear in `eval limit` = 5.

### Current OpenHands version

```bash
0.9.2
```

### Installation and Configuration

```bash
./evaluation/swe_bench/scripts/run_infer.sh [model_config] HEAD CodeActAgent 300
```

### Model and Agent

- Model: openai/gpt-4o-2024-05-13
- Agent: CodeActAgent

### Operating System

Linux

### Reproduction Steps

1. [Set up the environment](https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md)
2. Write the Openhands/config.toml as follows (The name of the model_config `llm.gpt4o` is what I created for convenience):
```
[core]
workspace_base="./workspace"

[llm.gpt4o]
model="openai/gpt-4o-2024-05-13"
api_key="[your_api_key]"
base_url="https://llm-proxy.all-hands.dev"
embedding_model="openai"
```
3. Run
`$ ./evaluation/swe_bench/scripts/run_infer.sh llm.gpt4o HEAD CodeActAgent 300`

### Logs, Errors, Screenshots, and Additional Context

The error should be as follows (`(...)` is a directory where your Openhands exists) :
```
[After Running Properly For A While]

ERROR:root:  File "(...)/OpenHands/evaluation/swe_bench/run_infer.py", line 465, in <module>
    run_evaluation(
  File "(...)/OpenHands/evaluation/utils/shared.py", line 278, in run_evaluation
    output = process_instance_func(instance, metadata, False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "(...)/OpenHands/evaluation/swe_bench/run_infer.py", line 353, in process_instance
    return_val = complete_runtime(runtime, instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "(...)/OpenHands/evaluation/swe_bench/run_infer.py", line 275, in complete_runtime
    assert obs.exit_code == 0
           ^^^^^^^^^^^^^
ERROR:root:<class 'AttributeError'>: 'ErrorObservation' object has no attribute 'exit_code'
Instance django__django-11133:   3%| | 9/295 [1:00:50<32:13:15, 405.58s/it, Test Result: {'git_patch'
```

**Comment by mamoodi** [comment]
@xingyaoww not very familiar with the eval part. If you have a few minutes to take a look at this.

**Comment by xingyaoww** [comment]
Yeah this one was more like a transient issue that I've encountered once in a while - typically, re-running the same instance again would most likely solve the issue.

@JiseungHong can you identify which "instance" this error happens, and can you show the detailed `infer_logs` for that? e.g., i want to know what action execution leads to this error.

**Comment by xingyaoww** [comment]
Oh nvm! I saw the `line 275` - probably the cd directory command. Can you share the commit you are running on?

This could be fixed by #3829. Can you try that one as well?

**Comment by JiseungHong** [comment]
@xingyaoww I merged the most recent official repo, but failed again with another error... It seems to be affected by some external environments (docker or disk related), so I'll manage to figure out and run it, thanks!

**Comment by xingyaoww** [comment]
@JiseungHong Can you share more about the another error? Would https://github.com/All-Hands-AI/OpenHands/pull/3846 helps/

**Comment by JiseungHong** [comment]
@xingyaoww I would really like to, but I'm currently stuck because of the server problems (docker images). I'll be sharing the errors ASAP when I solve other errors.

**Comment by tobitege** [comment]
The issue here is that in `run_infer.py` method `complete_runtime` it does not have an actual assert to assure it is the right result type, e.g.
```
assert isinstance(obs, CmdOutputObservation)
```
The result could be an `ErrorObservation` or any other event, but only `CmdOutputObservation` has the `exit_code` attribute.
