### ISSUE TITLE
[Bug]: Embedded browser not usable

### ISSUE THREAD

**Issue by MeNicefellow** [All-Hands-AI/OpenHands#3842]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

![image](https://github.com/user-attachments/assets/0180972e-97f4-4544-a599-54794dfde4aa)
The address cannot be edited.

### Current OpenHands version

```bash
newest.
```

### Installation and Configuration

```bash
docker from wsl
```

**Comment by mamoodi** [comment]
Hello there! I think currently that's as designed. They don't want it to be editable, it's just for OpenHands to use and it is in an experimental stage.

For example you can give it this prompt:
Go to the OpenHands github page at https://github.com/All-Hands-AI/OpenHands and tell me how many stars the github repo currently has

It will use the browser to perform the task.

**Comment by mamoodi** [comment]
Closing as designed.
