### ISSUE TITLE
[Feature]: Limit Input/Output Tokens, RP(M/D) Requests per (minute/day)

### ISSUE THREAD

**Issue by imeDevelopers** [All-Hands-AI/OpenHands#3853]
We need options to Limit the Input/Output Tokens, RP(M/D) Requests per (minute/day) ..

or notify the user once a specified number of Input/Output Tokens has reached.

also support Multi-Model, if one not works then use the another one to execute the tasks?!

why there's no such things!

it's very logically needed.

**Comment by imeDevelopers** [comment]
Also the cost limit feature ..

Once I reach $10 for example then notify me or pause the operations if I set such a limit ..

**Comment by mamoodi** [comment]
Hello. Some configurations are adjustable. You can see the [config.t](https://github.com/All-Hands-AI/OpenHands/blob/main/config.template.toml)

You can also set limits on the LLM end as mentioned in the warning:
https://docs.all-hands.dev/modules/usage/llms
