### ISSUE TITLE
[Bug]: "Initializing agent (may take up to 10 seconds)..." takes more than 10 seconds

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3898]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Right now we have a message in the frontend that says "Initializing agent (may take up to 10 seconds)..." but it often takes more than 10 seconds.

There are many reasons why it takes more than 10 seconds, but as a short-term fix, we should probably fix the frontend to be more honest about how long it may take to get started and provide some meaningful progress indicator.

### Current OpenHands version

```bash
f11e767eb54f68c23b0c3b156dc328de0192e63b
```

### Installation and Configuration

```bash
make build; make run
```

**Comment by tobitege** [comment]
Fixed by #3771
