### ISSUE TITLE
[Bug]: Models are cut off in the Settings UI. Full model name on hover

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#3900]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Either a bug or small enhancement. Currently, some models have longer names and get cut off. I have to select the model, then scroll to the right to see what I've selected. Can we have a popup of what the full model name is when you hover over it?

### Current OpenHands version

```bash
main
```

### Installation and Configuration

```bash
N/A
```

### Model and Agent

N/A

### Operating System

MacOS

### Reproduction Steps

1. Open the Settings
2. Select Anthropic for LLM Provider
3. Open up LLM Model dropdown

### Logs, Errors, Screenshots, and Additional Context

![Screenshot 2024-09-16 at 12 01 52 PM](https://github.com/user-attachments/assets/f2164b36-e129-425b-96fa-0eba9bd8d863)

**Comment by iaavas** [comment]
Hi, I'd like to work on this issue! I believe I can provide a fix. Could you please assign it to me?

Thanks!

**Comment by enyst** [comment]
Thank you, @iaavas ! You are most welcome to work on it, regardless of assignment of course. But since you prefer that, sure, it's yours!
