### ISSUE TITLE
[Bug]: permission issues accessing the workspace folder

### ISSUE THREAD

**Issue by m9e** [All-Hands-AI/OpenHands#3921]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When starting with the     -e SANDBOX_USER_ID=$(id -u)  syntax, the sandbox is created with an /etc/passwd like:

```
pn:x:1000:1000::/home/pn:/bin/bash
messagebus:x:100:102::/nonexistent:/usr/sbin/nologin
openhands:x:1001:0::/home/openhands:/bin/bash
```

But the parent container has openhands as uid 1000

as a result, the sandbox has permission denied on the workspace folder.

I am running it ~identical to the example in the readme:

```
export WORKSPACE_BASE=$(pwd)/workspace

docker run -it --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:0.9-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:0.9
 ```
    
   and the executing user is id 1000 on the host system
   
   the /etc/passwd from the openhands app container is:
   
```
   messagebus:x:100:101::/nonexistent:/usr/sbin/nologin
sshd:x:101:65534::/run/sshd:/usr/sbin/nologin
openhands:x:42420:42420::/home/openhands:/bin/bash
enduser:x:1000:42421::/home/enduser:/bin/bash
```

in the relevant part.

### Current OpenHands version

```bash
0.9 - image id 2d5ad156203d
```

### Installation and Configuration

```bash
docker run -it --pull=always -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:0.9-nikolaik -e SANDBOX_USER_ID=1000 -e WORKSPACE_MOUNT_PATH=/path/to/my/workspace -v /path/to/my/workspace:/opt/workspace_base -v /var/run/docker.sock:/var/run/docker.sock -p 3001:3000 --add-host host.docker.internal:host-gateway --name openhands-app-20240917130226 ghcr.io/all-hands-ai/openhands:0.9
```

### Model and Agent

- model: azure oai gpt4o
- agent: default (codeactagent?)

### Operating System

ubuntu 22.04 lts server

**Comment by m9e** [comment]
![Screenshot 2024-09-17 at 9 24 00 AM](https://github.com/user-attachments/assets/20476b36-fa26-4fd8-8e23-7785dab16cb4)

**Comment by m9e** [comment]
as a note, the agent is trying to do work in /tmp but that's not very helpful since it won't persist

**Comment by mamoodi** [comment]
I'm not sure if it's the same issue but multiple people did run into permission issues on Discord using Ubuntu as well so would be good to get some eyes on this. Thanks for bringing it up.

**Comment by scott-r-lindsey** [comment]
I'm seeing the same issue

```
0.9: Pulling from all-hands-ai/openhands
Digest: sha256:9d5f929c5c49bc15a405a8bc6d617516ec5dd25c2f3da42684b27278adc314f7
Status: Image is up to date for ghcr.io/all-hands-ai/openhands:0.9
Starting OpenHands...
Setting up enduser with id 1000
Docker socket group id: 136
Creating group with id 136
Running as enduser
```

id -u returns "1001", so we can't edit files.

**Comment by mamoodi** [comment]
Thanks again for bringing up this issue and these logs. I think the cause has been identified and they are trying to see how to approach this. Seems like the sandbox container used has a conflicting UID.

**Comment by mamoodi** [comment]
@m9e or @scott-r-lindsey, can you delete docker images associated with OpenHands and run the app replacing 0.9 in two places with "main" please?

```
export WORKSPACE_BASE=$(pwd)/workspace

docker run -it --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:main-nikolaik \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/all-hands-ai/openhands:main 
 ```

**Comment by scott-r-lindsey** [comment]
@mamoodi right on the money, tyvm

```
$ id -u
1000
```
