### ISSUE TITLE
[Bug]: `AgentDelegateObservation` is format as json for `CodeActAgent`

### ISSUE THREAD

**Issue by ryanhoangt** [All-Hands-AI/OpenHands#3969]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

From the [log below](https://github.com/user-attachments/files/17073518/prompt_005.log), the observation of `BrowsingAgent` finishing its task is sent to `CodeActAgent` as json.

This seems to be because of this line: https://github.com/All-Hands-AI/OpenHands/blob/45066f19dcec21b718e1d5dfb0586ae1c3091a90/agenthub/codeact_agent/codeact_agent.py#L156

### Current OpenHands version

```bash
0.9.3
```

### Installation and Configuration

```bash
`make start-backend`
```

### Model and Agent

- Model: gpt-4o
- Agent: CodeActAgent

### Operating System

Linux

### Reproduction Steps

1. `make start-backend`
2. On browser type: "go to "All-Hands-AI" github profile and get number of repositories they have"

**Comment by ryanhoangt** [comment]
@enyst This might be the reason for your observation last time. I'm not sure if this is expected and simply modifing the observation above is good enough.

**Comment by tobitege** [comment]
Hmm why is this a bug? Even before the "Message()" implementation, the observation was converted to a LLM-formatted message format?
