### ISSUE TITLE
[Bug]: Can't use OpenAI Compatabile API's, BadRequest Error

### ISSUE THREAD

**Issue by Nova-lotus** [All-Hands-AI/OpenHands#4004]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

Gives me badreqeust error, I tried it along using litellm but it works, it even works with Aider and Continue (Though I get the same thing with ClaudeDev)

It works perfectly with Gemini.

### Current OpenHands version

```bash
0.9.4
```

### Installation and Configuration

```bash
Hyperbolic API or Together AI
```

### Model and Agent

Qwen2.5-72B-Instruct

### Operating System

WSL On Windows

### Reproduction Steps

Just use the https://api.hyperbolic.xyz/v1 api base along with openai/Qwen/Qwen2.5-72B-Instruct

### Logs, Errors, Screenshots, and Additional Context

Error: BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'object': 'error', 'message': 'can only concatenate str (not "list") to str', 'code': 40302}
Please try again.

**Comment by enyst** [comment]
Thank you for the report, @Nova-lotus ! I could replicate it, and a PR is in review.

**Comment by mamoodi** [comment]
@enyst can this be closed now?

**Comment by enyst** [comment]
@Nova-lotus please check the newest version, the issue was fixed.

**Comment by Nova-lotus** [comment]
Thank you it works perfectly
