### ISSUE TITLE
[Bug]: out of the box the loading process is not ending 

### ISSUE THREAD

**Issue by hemangjoshi37a** [All-Hands-AI/OpenHands#4018]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

when i start using this command 
```sh
sudo docker run -it --pull=always     -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:latest     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name openhands-app-$(date +%Y%m%d%H%M%S)     ghcr.io/all-hands-ai/openhands:latest
```

the  leading process keeps going and not stopping 
![image](https://github.com/user-attachments/assets/c091f8f0-2316-47e0-8918-971a548ccd5b)

### Current OpenHands version

```bash
latest image from `ghcr.io/all-hands-ai/openhands:latest`
```

### Installation and Configuration

```bash
sudo docker run -it --pull=always     -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:latest     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name openhands-app-$(date +%Y%m%d%H%M%S)     ghcr.io/all-hands-ai/openhands:latest
```

### Model and Agent

openai 4o model (default)

### Reproduction Steps

Ubuntu 24.10

### Logs, Errors, Screenshots, and Additional Context

no visible errors .
```sh
(myenv) hemang@hemang-levono-15arr:~$ sudo docker run -it --pull=always     -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:latest     -e SANDBOX_USER_ID=$(id -u)     -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE     -v $WORKSPACE_BASE:/opt/workspace_base     -v /var/run/docker.sock:/var/run/docker.sock     -p 3000:3000     --add-host host.docker.internal:host-gateway     --name openhands-app-$(date +%Y%m%d%H%M%S)     ghcr.io/all-hands-ai/openhands:latest
latest: Pulling from all-hands-ai/openhands
Digest: sha256:02fe89753f51fec68082ad2466a45e669b458a38187666dc2bd3d7e49e8b6a4a
Status: Image is up to date for ghcr.io/all-hands-ai/openhands:latest
Starting OpenHands...
Setting up enduser with id 1000
Docker socket group id: 997
systemd-timesync:x:997:
Group with id 997 already exists
Running as enduser
INFO:     Started server process [36]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)
INFO:     172.17.0.1:40992 - "GET / HTTP/1.1" 200 OK
INFO:     172.17.0.1:40992 - "GET /api/options/models HTTP/1.1" 200 OK
INFO:     ('172.17.0.1', 41006) - "WebSocket /ws" [accepted]
INFO:     connection open
09:05:59 - openhands:INFO: agent.py:79 - Using security analyzer: 
09:05:59 - openhands:INFO: agent.py:90 - Initializing runtime `eventstream` now...
09:05:59 - openhands:INFO: runtime.py:203 - Starting container with image: ghcr.io/all-hands-ai/runtime:latest and name: openhands-sandbox-f0856bc5-685f-4b39-b209-e194807414df_bdcbc102-073a-4bb1-b225-55269ca4fa8d
09:05:59 - openhands:INFO: runtime.py:243 - Workspace Base: /opt/workspace_base
09:05:59 - openhands:INFO: runtime.py:247 - Mount dir: /home/hemang/workspace
09:05:59 - openhands:INFO: runtime.py:253 - Sandbox workspace: /workspace

```

**Comment by hemangjoshi37a** [comment]
it just keeps initializing infinitely 

![image](https://github.com/user-attachments/assets/0bae939e-0e31-46a0-abbc-b8beadf9a4f5)

**Comment by RonnyOtieno20** [comment]
My god I thought I was the only one suffering from this issue. I've spent 2 days trying to debug and nothing.

**Comment by hemangjoshi37a** [comment]
@RonnyOtieno20 Actually it takes around 15 minutes or so to load at the first time . and you should turn on the sound button that is muted by default at the right bottom corner that will beep once the system is on. actually we are also discussing other bug at https://github.com/SmartManoj/Kevin/issues/59 if you are interested .

**Comment by tobitege** [comment]
The `latest` tag is not what you think it is, that runtime image is a month old.
Please use the docker image tags as on the main page (runtime:0.9-nikolaik and openhands:0.9).

And yes, the first start can take a few minutes as current versions of docker images and container are being prepared.
In the near future we will show status messages during that time at least to show what is happening.

**Comment by hemangjoshi37a** [comment]
@tobitege I am using both latest images for the  runtime and the main . so i think it should not be a problem .

**Comment by tobitege** [comment]
> @tobitege I am using both latest images for the runtime and the main . so i think it should not be a problem .

The tags match, yes, just saying that you're not on the current version, in case of other things we've added and issues fixed since then. 😄 

The loading time is still the same initially, but should get faster on subsequent loads (still not "10 seconds" unfortunately).

Also, since it is not explicitly mentioned in your report, did you set/execute this as well?
```bash
export WORKSPACE_BASE=$(pwd)/workspace
``` 
If not, that could explain while your files are not where you expected them to be (if I read the other link correctly).

**Comment by hemangjoshi37a** [comment]
I have created the workplace 
![image](https://github.com/user-attachments/assets/512f55f5-f423-4d6a-85b6-a7b59e0f9054)

but there is not folder /tmp that is mentioned in the chat . i beleive that is in the contained volume and should be moved to the workspace folder

**Comment by tobitege** [comment]
I've removed the image, fyi

**Comment by RonnyOtieno20** [comment]
@hemangjoshi37a Thanks. Let me give it some time and see how it goes. Following your discussion with @SmartManoj as well.

**Comment by tobitege** [comment]
> but there is not folder /tmp that is mentioned in the chat . i beleive that is in the contained volume and should be moved to the workspace folder

Because the environment variable WORKSPACE_BASE was not set by the command I posted above.
Please run that before you start the next docker command to start OpenHands.

**Comment by hemangjoshi37a** [comment]
I already have ran this command befor starting it `export WORKSPACE_BASE=$(pwd)/workspace`

**Comment by hemangjoshi37a** [comment]
here is my feedback page if you want to check it more verbosely : `https://www.all-hands.dev/share?share_id=2ce107aebe4bde7190815ea469326b1a31e2d1d92093a5618052ed57ac0a3b70`

**Comment by hemangjoshi37a** [comment]
can we do aider integration in this because it is really good at search-and-replace for code edit and many other things, instead developing it from the scratch we can use it off the shelf and apply it here .

**Comment by tobitege** [comment]
Ok, that /tmp folder got me confused, it wasn't anywhere in the docker command.
You asked the LLM about a /tmp folder, which from the view of OpenHands, is inside the container.
And as that is specified as a absolute path, it is outside of the mapped workspace folder, i.e. not visible on your machine.
I hope that explains the issue here.

Please direct the model next time to treat /workspace as its working directory.

Since the issue itself was about the loading, please feel free to close this issue and/or create a new one.

**Comment by tobitege** [comment]
> here is my feedback page if you want to check it more verbosely : https://www.all-hands.dev/share?share_id=2ce107aebe4bde7190815ea469326b1a31e2d1d92093a5618052ed57ac0a3b70
> 
> in this you can see that there are some errors when the agent is executing some commands :
> 
> ```
> Command execution failed: {"detail":"action={'id': 12, 'timestamp': '2024-09-24T10:06:26.638864', 'source': 'agent', 'message': 'Running command: pwd', 'action': 'run', 'args': {'command': 'pwd', 'thought': "It seems there is an issue with executing the ls command directly. Let me try using the pwd command to confirm the current working directory and then list the files in the /tmp directory.\n\nFirst, I'll get the current working directory:", 'blocking': True, 'keep_prompt': True, 'is_confirmed': 'confirmed'}, 'timeout': 120} has the wrong arguments"}
> ```

Please use the docker command with the tags I mentioned earlier, that error should be fixed.

**Comment by hemangjoshi37a** [comment]
@tobitege  ok got it . please review #4022

**Comment by tobitege** [comment]
In the meantime we added a small feature, that the UI will show status updates during startup.
This doesn't change the time needed, but finally gives some feedback.

Closing this issue, thanks for your support and discussions!
