### ISSUE TITLE
I want there to be live local graphRAG 

### ISSUE THREAD

**Issue by hemangjoshi37a** [All-Hands-AI/OpenHands#4020]
This should help make development possible for long format code or bigger code bases. the live word means that whenever the code change is made the graphrag system will update the graph database using latest code version and based on that the future queries will be generated .

**Comment by tobitege** [comment]
Please be so kind to also provide links or further information and save us the time to search for everything.

**Comment by hemangjoshi37a** [comment]
here is a link from one of many implementations : https://github.com/severian42/GraphRAG-Local-UI

**Comment by hemangjoshi37a** [comment]
@tobitege hey i want to become collaborator for this project. please help me

**Comment by tobitege** [comment]
Please follow the repo's main page, all the information and links are there :)
