### ISSUE TITLE
I want there to be a system prompt box similar to how openai and anthropic and groq has 

### ISSUE THREAD

**Issue by hemangjoshi37a** [All-Hands-AI/OpenHands#4021]
It will give us control on how we want to make the llm to behave . something i have been trying  to do this here : https://github.com/hemangjoshi37a/o1-meta-prompt

**Comment by enyst** [comment]
Hi @hemangjoshi37a! `openhands` supports multiple agents, and each agent has a system prompt. For example, the system prompt for the main agent is specified [here](https://github.com/All-Hands-AI/OpenHands/blob/main/agenthub/codeact_agent/system_prompt.j2)

We plan to support prompt pieces that the user can choose and add/insert into the prompt. I'm not so sure about the full prompt, in that case it seems to me that you're asking for a new agent. Maybe that's the way forward for your proposal: if you wish to make an agent which "transforms" other LLMs into something o1-like, feel free to define one and submit a PR. If it works well, we can try it!

Agents are defined in the `agenthub` directory. Please feel free to look around! For example, there is an experimental planner agent [here](https://github.com/All-Hands-AI/OpenHands/tree/main/agenthub/planner_agent).
