### ISSUE TITLE
[Usability] Improving CLI interface for OpenHands with `oh launch here` and `oh launch here --remote`

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4024]
**What problem or use case are you trying to solve?**

I hope to start OpenHands wherever I want it to work. But now we have to manually maintain a lengthy docker run script and change `WORKSPACE_BASE` every time, or have to `make run` in a directory and modify `config.toml` to set the right workspace directory.

**Describe the UX of the solution you'd like**

For example, I am in a folder `xyz/`, and instead of launching a lengthy docker run command, the experience i hope to have is:
1. `cd xyz/`
2. `pip install openhands`
3. `oh launch cli here` -> It will launch a OpenHands CLI pointing to `xyz/` as the workspace.
4. `oh launch ui here` -> It will launch a OpenHands UI pointing to `xyz/` as the workspace.

**Do you have thoughts on the technical implementation?**

Currently, we install OpenHands via `make build`, which uses poetry under the hood, and we already have a command line interface: `poetry run python -m openhands.core.cli`. You can find the details of the arg parser in `get_parser` function of `openhands/core/config/utils.py`. 

Specifically, it has a `--directory` argument.

What i want is:

1. Instead of calling `poetry run python -m openhands.core.cli`, I want to directly run `oh` 
2. When i run `oh launch cli here`, i hope i can have a `openhands.core.cli` started with `--directory` point to the current pwd.
3. When i run `oh launch ui here`, i hope i can start a GUI (following `run` in `./Makefile`) with environment variable `WORKSPACE_BASE` and `WORKSPACE_MOUNT_PATH` set to pwd

**Describe alternatives you've considered**

**Additional context**

**Comment by tobitege** [comment]
I think if you would expand on what CLI means in the context of openhands (via pip), i.e. which file to call etc., you should label it "fix-me" and let it try it.
