### ISSUE TITLE
Feature request: ask support for the InternLM

### ISSUE THREAD

**Issue by boshallen** [All-Hands-AI/OpenHands#4043]
Hi,

I noticed that the repository currently lacks support for the InternLM2.5-7B (1.8B, 20B) model, which may cause compatibility issues or missing steps for users trying to implement it. It would be beneficial to update the repository with detailed instructions or tools for integrating and using the InternLM2.5-7B model, ensuring the content remains relevant.

I believe that adding this support would significantly enhance the usability of the project. While some manual adjustments are possible, official guidance or toolchain support would be much more efficient and advantageous, especially for new users.

If possible, including example scripts or demonstrating integration with InternLM2.5-7B would also be a valuable addition.

For further support, please add the InternLM Assistant (WeChat search: InternLM) or join the InternLM Discord.

**Comment by tobitege** [comment]
Is there a website for this? What issues did you experience in OpenHands with that model?

**Comment by tobitege** [comment]
Their models seem only be avaiable and supported by litellm right now by using Ollama.

**Comment by enyst** [comment]
Hi @boshallen! As @tobitege said, we support InternLM via LiteLLM. If you wish more features, I suggest to post an issue in their repo:
https://github.com/BerriAI/litellm/issues

**Comment by tobitege** [comment]
Contrary to the authors claim, I doubt _any_ 7B model will benefit this project with regard to its main intent of software development.
Since there's no further replies here, closing this issue.

**Comment by boshallen** [comment]
> Hi @boshallen! As @tobitege said, we support InternLM via LiteLLM. If you wish more features, I suggest to post an issue in their repo: https://github.com/BerriAI/litellm/issues

OK, thanks for your reply！

**Comment by boshallen** [comment]
If there is a better idea next time, I will raise an issue in the repo you mentioned. Thank you.
