### ISSUE TITLE
Use litellm Router for rate limiting and/or fallback LLMs

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#4056]
**Summary**

Litellm has the [Router](https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/router.py#L130) class that encapsulates `completion` with rate limits handling. We can look into using it, because it should allow us to define a RetryPolicy hopefully based on how long the provider has left (though in my reading, it doesn't yet). It does allow to define a fall back LLM in case one provider runs out of tries. (https://github.com/All-Hands-AI/OpenHands/issues/1263)

Rate limit headers for OpenAI:
https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers

Rate limit headers for Anthropic:
https://docs.anthropic.com/en/api/rate-limits#response-headers

**Technical Design**

Replace `completion` direct call to litellm with [`Router.completion`](https://github.com/BerriAI/litellm/blob/2444d76fda2ddfb5756100286f4961592b8b6472/litellm/router.py#L589)

**Alternatives to Consider**

Continue to do it ourselves. Various providers have different rate limits, so our options are:
- don't get the remaining time, and think again of some sensible defaults, user-configurable; better documentation
- get the remaining time from liteLLM

Fall back LLM:
- do it ourselves
- configure litellm

**Comment by BradKML** [comment]
Bouncing this back to here https://github.com/All-Hands-AI/OpenHands/issues/4184
