### ISSUE TITLE
[Bug]: Reduce padding in lists inside of messages

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4082]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The spacing here is a little over the top :) 
<img width="464" alt="Screenshot 2024-09-27 at 10 39 35 AM" src="https://github.com/user-attachments/assets/e256687f-7aef-4d79-b84c-7d7ee3a18ede">

This can probably be fixed by modifying the spacing in `frontend/src/index.css`

### Current OpenHands version

```bash
0.9.5
```

### Installation and Configuration

```bash
`docker run` from the README
```

### Model and Agent

N/A

### Operating System

N/A

### Reproduction Steps

Write a prompt that uses markdown bullet points

**Comment by neubig** [comment]
Attempting to fix this PR automatically uncovered two issues:
* https://github.com/All-Hands-AI/OpenHands/issues/4103
* https://github.com/All-Hands-AI/openhands-resolver/issues/111

**Comment by Vaishakh-SM** [comment]
Hi!
Can I work on this?

**Comment by neubig** [comment]
Yes, please go ahead @Vaishakh-SM !

**Comment by Vaishakh-SM** [comment]
Adding a checklist of items that I intend to complete:

- [ ] Dev Setup efforts (Following the guide)
- [ ] Reproduction of the issue
- [ ] Glance over the frontend code-base, particularly places related to styling.
- [ ] Tweak styling and check if the issue is resolved
- [ ] Raise PR

**Comment by tobitege** [comment]
Hey @Vaishakh-SM 
please have a look at #3449 and the [comment](https://github.com/All-Hands-AI/OpenHands/pull/3449#issuecomment-2295380306) by @amanape 
I never got to do the follow PR. The above should give you a good starting point _where_ to look, I hope.

**Comment by Vaishakh-SM** [comment]
> Hey @Vaishakh-SM please have a look at #3449 and the [comment](https://github.com/All-Hands-AI/OpenHands/pull/3449#issuecomment-2295380306) by @amanape I never got to do the follow PR.

Thanks, this helps a lot!

Can I remove the styles that you added to index.css if I add them into the Markdown component like:

```jsx
      <Markdown
        components={{
          code,
          ul: ({ children }) => (
            <ul className="list-decimal ml-5 pl-2">{children}</ul>
          ),
          ol: ({ children }) => (
            <ol className="list-disc ml-5 pl-2">{children}</ol>
          ),
        }}
      >
```
