### ISSUE TITLE
[Bug]: Sandbox image fails to build at the last step and removes image

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4083]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

After starting the first-time setup on a new session, the setup fails at what looks like the last step. The worst part is the image is also removed, and the process will have to start from the beginning.

I've tried 6-8 times, and all times result in the same problem.

### Current OpenHands version

```bash
0.9.6?
```

### Installation and Configuration

```bash
make run && make build
```

### Model and Agent

N/A

### Operating System

Failed on macOS Sonoma and Sequoia

### Reproduction Steps

1. Clear all images on Docker
2. Run `make build && make run`
3. Open development URL to start new session (recommended on incognito)
4. Wait for image to download
5. Observe failure

### Logs, Errors, Screenshots, and Additional Context

```sh
# ...
Layer 58c95310a9d6: [==================================================>]  1.212kB/1.212kB Pull complete: [==================================================>]  214.1MB/214
Layer 843b1d832182: Already exists
Layer 9b9406b2910f: Already exists
Layer 9d130d7c7b24: Download complete
Layer 9f83f9ca11a4: Already exists
Layer a083108ed477: [==================================================>]     139B/139B Pull complete
Layer a348c2a8d946: Already exists
Layer e069d8931f58: [==================================================>]  214.1MB/214.1MB Pull complete
Layer e1860d8ed6fa: Already exists
================ DOCKER BUILD STARTED ================
------
Dockerfile:2
--------------------
1 |
2 | >>> FROM ghcr.io/all-hands-ai/runtime:oh_v0.9.6_image_nikolaik_s_python-node
3 |
4 |
--------------------
ERROR: failed to solve: failed to register layer: write /openhands/poetry/openha
View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux
18:35:56 - openhands:ERROR: docker.py:121 - Image build failed:
Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.9.6', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-09-27T18:25:14.662939', '--tag=ghcr.io/all-hands-ai/runtime:e6121feb1c641290475c9de016ade909', '--load', '/var/folders/h9/k824x1kx25g4mh3jgf3ld0h00000gn/T/tmpf6x8misq']' returned non-zero exit status 1.
18:35:56 - openhands:ERROR: docker.py:122 - Command output:
None
18:35:56 - openhands:ERROR: runtime_build.py:372 - Sandbox image build failed: Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.9.6', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-09-27T18:25:14.662939', '--tag=ghcr.io/all-hands-ai/runtime:e6121feb1c641290475c9de016ade909', '--load', '/var/folders/h9/k824x1kx25g4mh3jgf3ld0h00000gn/T/tmpf6x8misq']' returned non-zero exit status 1.
```

**Comment by tobitege** [comment]
Oh! I might have missed this, can you run this in your terminal:
docker buildx version
If it is not installed, it might give an error.
```
sudo apt update
sudo apt install docker-buildx
```

**Comment by tobitege** [comment]
And you're sure there is enough free disk space?

**Comment by amanape** [comment]
@tobitege 
Output of `docker buildx version`: 
`github.com/docker/buildx v0.16.2-desktop.1 081c21b9e461293ae243a1ff813a680a4f5f8fb9`

And yes, I have enough free disk space (~33 GB left 😢)

**Comment by amanape** [comment]
Actually you're most likely right. Trying to fetch the image directly or running `make docker-dev` does throw `You don't have enough free space in /var/cache/apt/archives/.` which is unexpected...

**Comment by tobitege** [comment]
Oh, ok. Time to prune your local docker registry 😔

**Comment by amanape** [comment]
Output of `docker system prune -a`:

`Total reclaimed space: 21.14GB`

...................................................................................................
