### ISSUE TITLE
[Bug]: Weird Bash-related Runtime Bug

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4094]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When execute command `python --version`, the bash wouldn't run the command for me, instead telling me: `
bash: --version: command not found`

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/8de83403-01d8-4917-87bf-bd1171424dd3">

But `echo "python --version" | eval` works:

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/e0fba2cb-bba2-4e42-a1bc-fa27967d65de">

And `which python` also works:

<img width="941" alt="image" src="https://github.com/user-attachments/assets/67d88f0f-4bcb-458e-9eaf-5e92e881923f">

This is also reported by multiple people (cc @RajWorking & Sanidhya)

### Current OpenHands version

```bash
main, `9df395cc67f5a2487e6bdebd90f37cfd491a9eef`
```

### Installation and Configuration

```bash
Building a runtime image based on `python:3.11-bookworm`:

/runtime/test_eval_images.py
"""Tests for SWE-Bench evaluation images."""

import os

import pytest
from conftest import (
    TEST_IN_CI,
    _close_test_runtime,
    _get_sandbox_folder,
    _load_runtime,
)

from datasets import load_dataset

from openhands.core.config import LLMConfig, AppConfig, SandboxConfig
from openhands.core.logger import openhands_logger as logger
from openhands.events.action import CmdRunAction
from openhands.events.observation import CmdOutputObservation

def test_python_container(temp_dir, box_class):
    dummy_metadata = EvalMetadata(
        agent_class='CodeActAgent',
        llm_config=LLMConfig(),
        max_iterations=30,
        eval_output_dir='dummy',
        start_time='dummy',
        git_commit='dummy',
    )

    config = AppConfig(
        run_as_openhands=False,
        sandbox=SandboxConfig(
            base_container_image='python:3.11-bookworm',
            enable_auto_lint=True,
            use_host_network=False,
            # large enough timeout, since some testcases take very long to run
            timeout=300
        ),
        # do not mount workspace
        workspace_base=None,
        workspace_mount_path=None,
    )

    runtime = _load_runtime(temp_dir, box_class, config_override=config)

    obs = runtime.run_action(CmdRunAction(command='python --version'))
    assert isinstance(obs, CmdOutputObservation)
    logger.info(obs, extra={'msg_type': 'OBSERVATION'})
    import pdb; pdb.set_trace()



Then `DEBUG=true pytest -vvxss tests/runtime/test_eval_images.py::test_python_container`
```

**Comment by RajWorking** [comment]
It also gives the same error when I run:
python -m unittest code_test.py

As a temporary workaround for now, I changed python to python3.

**Comment by xingyaoww** [comment]
Seems only happening with Python..

<img width="989" alt="image" src="https://github.com/user-attachments/assets/165c9910-b8b6-4961-a0e2-5e1a36961cc4">

**Comment by xingyaoww** [comment]
Looks like this is the cause (cc @tobitege) - we probably need to revert it
https://github.com/All-Hands-AI/OpenHands/blob/3f9111c615bc8da62aa6a5fbb0a385773d117b7d/openhands/runtime/utils/runtime_templates/Dockerfile.j2#L85-L92

The actual `bash.bashrc` doesn't look right
<img width="855" alt="image" src="https://github.com/user-attachments/assets/2c0af138-18ec-426e-ae95-d064bd4d9afb">

**Comment by tobitege** [comment]
Trying to fix this right now...

**Comment by xingyaoww** [comment]
@tobitege i think simply remove this should fix the problem -- but the problem is now embedded into the base image (e.g., `oh_v0.9.6_image_python_tag_3.11-bookworm)).. we probably need to fix it & cut a release to avoid future issue (new build may still build off the base) due to this..


<img width="1540" alt="image" src="https://github.com/user-attachments/assets/30943745-b732-4cc7-a392-6f363a9a5d60">

**Comment by tobitege** [comment]
just give me a few minutes, will also have a unit test for this, if all goes well

**Comment by xingyaoww** [comment]
Anyway, I think it is probably good to remove this block (at least the Python alias) -- i don't see the actual use case of using `$OH_INTERPRETER_PATH` as a default Python, the reason why i use `python:bookworm` is that i want to use the python interpreter there, but not the OpenHands one 🥵

**Comment by tobitege** [comment]
we're installing python into an env, so that one should be used, no?

**Comment by xingyaoww** [comment]
> we're installing python into an env, so that one should be used, no?

The installed interpreter should ONLY be used by OpenHands-related code inside the runtime (e.g., the webserver that receives and executes actions from the backend).

But it should ideally be never used by the agent: the agent might mess-up the dependencies there that eventually break the web server (i.e., runtime-client).
