### ISSUE TITLE
How do I integrate ollama as a repo explorer model

### ISSUE THREAD

**Issue by cloudbow** [All-Hands-AI/OpenHands#4106]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

I would like to  use the latest ollama 3.2 model as the model for using as repo explorer model. How do I do this with ollama serve. what is the api key.

It would be great if its linked in some doc.

**Comment by enyst** [comment]
The API key for ollama can be whatever you like. I used "dummy" or "ollama" for example.

That will enable you to use models served via ollama in `openhands`. Please take a look [at this doc](https://github.com/All-Hands-AI/OpenHands/blob/4bafaea7593ae7ae8f8814e5e2d87e186f47dd82/docs/modules/usage/llms/local-llms.md) too.
