### ISSUE TITLE
[Bug]: Disable cache on web application's index.html

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4127]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

For the root path `/` and `/index.html`, we need to make sure that there is no caching set up. Otherwise the frontend breaks on update.

This will involve editing openhands/server/listen.py, specifically the part that serves the web app at the bottom of the file

### Current OpenHands version

```bash
0.9.7
```

### Installation and Configuration

```bash
N/A
```

**Comment by amanape** [comment]
Does this issue still persist? Cache shouldn't be enabled by default.

**Comment by rbren** [comment]
I frequently have to cmd+shift+R when loading up a new version of OpenHands...

**Comment by mamoodi** [comment]
This would make a big difference for usability. I've had to do this way too many times.

**Comment by mamoodi** [comment]
@rbren was this fixed by any chance? I thought I saw a PR go by related to this.

**Comment by rbren** [comment]
Hypothetically yes, but I think I saw an issue w/ it again recently. Let's close this one for now and I'll keep an eye out
