### ISSUE TITLE
build own llm agent

### ISSUE THREAD

**Issue by kasinadhsarma** [All-Hands-AI/OpenHands#4132]
without using gemini openai and other ai stuff we need to develop the ai Vishwamai has datasets of coding we  https://huggingface.co/collections/VishwamAI/agi-devlopment-l1-66e01ca96848301e387d23fb let's elobrate the ai agentic view

**Comment by tobitege** [comment]
Hello @kasinadhsarma ,

its not quite clear what you are asking for here? OpenHands does not deal with training models which is independent of agents.

**Comment by kasinadhsarma** [comment]
Own llm ai agent like devin ai

**Comment by mamoodi** [comment]
I believe there is already an issue open for this to create a competitive LLM. However, that is not a simple task.

**Comment by kasinadhsarma** [comment]
well can we try it i have some dataset collections and development and we can also interlink with code gemma and other stuff also

**Comment by tobitege** [comment]
What you're asking is out of scope for this repository. Feel free to join the OpenHands Slack server to discuss LLM models etc., but we are not building/training LLM's here.
