### ISSUE TITLE
[Bug]: Sandbox image build failed on eval

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4157]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I ran the following on the `eval/24-sep` branch:
```bash
$ ./evaluation/swe_bench/scripts/run_infer.sh llm.mini HEAD CodeActAgent 2 30 1 princeton-nlp/SWE-bench_Lite test &> ~/sand/eval_log.log
```

But I'm getting issues pulling the docker image:
```bash
[92m20:44:21 - openhands:ERROR[0m: runtime_build.py:386 - Sandbox image build failed: 404 Client Error for http+docker://localhost/v1.46/images/ghcr.io/all-hands-ai/runtime:d123cc51fdfb0f69ea7a3c8bdda940d7/json: Not Found ("No such image: ghcr.io/all-hands-ai/runtime:d123cc51fdfb0f69ea7a3c8bdda940d7")
```

Apparently this is caused by the fact that I ran this on an `arm64` processor, which is not supported in SWE-bench evaluation.
To make this more clear for others who do the same thing, we should add a check in the main function of `evaluation/swe_bench/run_infer.py` and `evaluation/swe_bench/eval_infer.py`, and throwing an error if the processor type is arm64.

### Current OpenHands version

```bash
eval/24-sep
```

### Installation and Configuration

```bash
git clone
```

**Comment by neubig** [comment]
Thanks a bunch @xingyaoww ! But it seems like maybe it's still broken? Here's a log. I also deleted all my docker images to be sure it wasn't something residual.

[eval_log.log](https://github.com/user-attachments/files/17219304/eval_log.log)

**Comment by xingyaoww** [comment]
`[92m23:05:08 - openhands:INFO[0m: docker.py:31 - ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`


ahh i think it is probably because SWE-Bench doesn't officially support arm64 evaluation i believe? So maybe it is related to trying to build amd64 image on arm64?

**Comment by neubig** [comment]
Ah, I see... Maybe I'd have to do it on a VM.

**Comment by neubig** [comment]
Hmm @xingyaoww , it seems that it's also failing on a computer where I have x86_64
```bash
$ arch
x86_64
```

Here is the log:
[eval_log.log](https://github.com/user-attachments/files/17219758/eval_log.log)
