### ISSUE TITLE
[Bug]: Docker image build failing for SWE-Bench evaluation

### ISSUE THREAD

**Issue by sani903** [All-Hands-AI/OpenHands#4164]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The Sandbox image build is failing for SWE-Bench instances testing. 
I was previously working with OH version 0.9.4 which did not have this issue but upon pulling 0.9.7, this problem started with most instances. For example: astropy__astropy-7606, django__django-15375, django__django-13112, django__django-14855

I am using the Docker images (such as xingyaoww/sweb.eval.x86_64.django_s_django-13112:latest). 

### Current OpenHands version

```bash
0.9.7
```

### Installation and Configuration

```bash
Cloned OpenHands and ran evaluation with "./evaluation/swe_bench/scripts/run_infer.sh <model_config>"
I stored the instance IDs in config.toml
```

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

<img width="1438" alt="Screenshot 2024-10-01 at 11 10 46 PM" src="https://github.com/user-attachments/assets/0cb8b769-956e-4a04-9243-6c8d602b5454">

**Comment by neubig** [comment]
This might be duplicate with #4157 ?

**Comment by sani903** [comment]
> This might be duplicate with #4157 ?

As per the logs in that issue, while the error was related to building the Sandbox Image, the error there was an API error 
`[File "/home/gneubig/.cache/pypoetry/virtualenvs/openhands-ai-02VxP7eD-py3.11/lib/python3.11/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
           ^^^^^^^^^^^^^
  File "/home/gneubig/.cache/pypoetry/virtualenvs/openhands-ai-02VxP7eD-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/home/gneubig/.cache/pypoetry/virtualenvs/openhands-ai-02VxP7eD-py3.11/lib/python3.11/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e](https://github.com/All-Hands-AI/OpenHands/issues/4164)`

Here I am able to get the image, but then a particular mamba command is failing. So it might be related, but I thought this was a different problem as the error stemmed from docker.py.
