### ISSUE TITLE
[Bug]: Frontend workspace update is blocked until agent completes task

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4199]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

While the agent is working, it takes a long time for the frontend to register updates to the files displayed in the "workspace" view (maybe until the agent is done working?). It would be nice if the frontend updated more quickly.

### Current OpenHands version

```bash
0.9.8
```

### Installation and Configuration

```bash
make build; make run
```

**Comment by tobitege** [comment]
I'd say this is sortof a duplicate of #3739 - right now any completion by an agent is blocking the UI.

**Comment by mamoodi** [comment]
Updated the title of the bug to reflect the issue
