### ISSUE TITLE
Add a user guide page dedicated to setup OpenHandas to work with local models (Ollama/LiteLLM/etc)

### ISSUE THREAD

**Issue by gabrielblins** [All-Hands-AI/OpenHands#4227]
**What problem or use case are you trying to solve?**

Add a user guide page dedicated to setup OpenHandas to work with local models (Ollama/LiteLLM/etc)

**Describe the UX of the solution you'd like**

A new page on documentation describing how to setup OpenHands to work with local models + some troubleshooting for common errors

**Do you have thoughts on the technical implementation?**

--

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by enyst** [comment]
Please take a look here: https://docs.all-hands.dev/modules/usage/llms/local-llms

If you have suggestions or improvements, a PR is welcome!

**Comment by gabrielblins** [comment]
Thanks! That's what I was looking for!
