### ISSUE TITLE
[Bug]: Error in certain Docker images for SWE-Bench instance evaluations

### ISSUE THREAD

**Issue by sani903** [All-Hands-AI/OpenHands#4235]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When initializing the environment for instance-level SWE-Bench Docker images, the code to go to the desired directory as base throws an error. It might be related to swe-bench-instance.json. More specifically, for certain instances from repositories like pytest, matplotlib, sphinx, etc. the directory name to change directory to might not be constructed properly with an error concatenating the repo name and its version which leads to an error in making the required directory in line 31 of evaluation/swe_bench/scripts/setup/instance_swe_entry.sh

Some instances which throw this error:
* matplotlib__matplotlib-23314
* sphinx-doc__sphinx-7757
* scikit-learn__scikit-learn-9288
* pytest-dev__pytest-7432
* pytest-dev__pytest-5262
* matplotlib__matplotlib-26466

From all the instances of django and sympy that I have tested, none throw this error.

### Current OpenHands version

```bash
0.9.7
```

### Installation and Configuration

```bash
git clone
make build
```

### Operating System

Linux

### Reproduction Steps

1. Create config.toml in evaluation/swe_bench and add the instance IDs mentioned as "selected_ids = [ "<error_instance_ids> "] 
2. Run `./evaluation/swe_bench/scripts/run_infer.sh <llm.config>`

### Logs, Errors, Screenshots, and Additional Context

<img width="1365" alt="Screenshot 2024-10-05 at 1 30 33 AM" src="https://github.com/user-attachments/assets/323d5eca-d74e-41e5-8334-48abd1ce1281">

**Comment by neubig** [comment]
@xingyaoww it'd be great if you could take a look

**Comment by xingyaoww** [comment]
Haven't test it yet (will do soon) - but this should fix it: https://github.com/All-Hands-AI/OpenHands/pull/4241

**Comment by xingyaoww** [comment]
I tested #4241 on `matplotlib__matplotlib-23314` which is working.  I'll close this for now - @sani903 lmk if this works for you, feel free to re-open if not!
