### ISSUE TITLE
🐛[Bug]: In the Hero section Button UI hover effect not working .

### ISSUE THREAD

**Issue by prathamesh424** [All-Hands-AI/OpenHands#4237]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

###  On Hero Section the button's hover effect  not working like the other buttons in the website .. 
![Screenshot 2024-10-07 104754](https://github.com/user-attachments/assets/6950af45-5080-4d66-b0b6-1924615a589a)

### Expected hover effect :  
button : 
![Screenshot 2024-10-07 104741](https://github.com/user-attachments/assets/22ab3870-498e-400c-9b58-94c23c2c8ca4)
after hover effect
![Screenshot 2024-10-07 104747](https://github.com/user-attachments/assets/63a514c4-9ace-4a73-917f-22e223768452)

button:
![Screenshot 2024-10-07 104711](https://github.com/user-attachments/assets/96587584-6652-4c34-b138-942ff0da88d5)
after hover effect : 
![Screenshot 2024-10-07 104718](https://github.com/user-attachments/assets/c56eec8c-7361-4aa8-b929-b1c4157be032)

### Current OpenHands version

```bash
UI error : Windows 11 : chrome
```

### Installation and Configuration

```bash
N/A
```

### Reproduction Steps

1.Adding the Hover effect to the button

### So, Assign this issue to me ......

**Comment by mamoodi** [comment]
Thanks very much for bringing this to our attention and I see amanape has already taken this up. However, this is related to the All Hands AI company website and not the OpenHands application. As such I will close this.

**Comment by amanape** [comment]
Already resolved!
