### ISSUE TITLE
[Bug]: "Import Project" doesn't allow opening of a directory

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4255]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

I clicked on the "import project" button on the new UI.

<img width="281" alt="Screenshot 2024-10-07 at 4 32 47 PM" src="https://github.com/user-attachments/assets/9215ba25-ce01-4bcf-923a-be5eacbc4f9a">

When I clicked on this I expected that it would allow me to open a directory that I could use as the workspace, but in the mac file selection menu it doesn't allow me to open a directory (the "Open" button is inactive when I select a directory).

<img width="482" alt="Screenshot 2024-10-07 at 4 31 41 PM" src="https://github.com/user-attachments/assets/a1c72211-084e-4eca-8d33-c71b62e8e7c6">

### Current OpenHands version

```bash
0809d26f4d8a5514c0a255ed0a3bf3d999b1c29f
```

### Installation and Configuration

```bash
make build; make run
```

**Comment by mamoodi** [comment]
@amanape has mentioned this only works with .zip files. Have to decide whether to make this more clear or to allow directories to be selected.

**Comment by neubig** [comment]
Oh, when this is running locally I just assumed it would set the workspace directory. It seems like a nicer solution than requiring a zip file

**Comment by amanape** [comment]
We'd probably have to zip the directory either way when doing so, seems a matter of extending functionality. There doesn't seem to be any downsides I can think of, I'm good with the idea.

@rbren Thoughts?

**Comment by rbren** [comment]
This seems to have reasonable support in desktop browsers: https://caniuse.com/input-file-directory

We will probably have to handle it as a multipart upload, if I had to guess...not great but doable

**Comment by xingyaoww** [comment]
Or we could allow user to select a "folder" - and automatically zipping that folder for upload if we are using it on saas, otherwise just set that as workspace (in case it is launched locally?)
