### ISSUE TITLE
[Bug]: `zip_files_in_sandbox` not implemented for RemotRuntime

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4258]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

The following error happens with RemoteRuntime because the newly added `zip_files_in_sandbox` is not implemented. 

![image](https://github.com/user-attachments/assets/fa07fb65-6f9b-421e-bcf6-e664b9e143c9)

### Current OpenHands version

```bash
main, after amanape's UI change
```

### Installation and Configuration

```bash
dev
```

### Logs, Errors, Screenshots, and Additional Context

I think we should generalize the `copy_to` a bit and combine `zip_files_in_sandbox` with `copy_to`

**Comment by amanape** [comment]
Resolved by #4278
