### ISSUE TITLE
Allow confirmation of action without moving to next action.

### ISSUE THREAD

**Issue by amirshawn** [All-Hands-AI/OpenHands#4259]
**What problem or use case are you trying to solve?**
When in confirmation mode it's not possible to give instructions in between steps.  You have to reject an action and it seems like it doesn't know that the action was rejected.  

**Describe the UX of the solution you'd like**
The simplest would be to have a third option, confirm action and wait.  This way the action is confirmed but before it tries to take the next step you are able to give some feedback.  Also if it somehow knows the action was rejected that would be helpful as well so when you do reject an action it knows that action wasn't taken.

**Comment by neubig** [comment]
Hey @amirshawn , this is an interesting idea! I also think it shouldn't be too hard, so we can mark it as a good first issue.

**Comment by sahilborse** [comment]
@amirshawn  I would like to work on this issue assign it to me please.

**Comment by amirshawn** [comment]
Hi @sahilborse, 
That would be great if you could take this on!  I don't think I have the permissions to assign the issue to you.  @neubig Is this something you are able to do?

**Comment by enyst** [comment]
Thanks for taking it up, @sahilborse !

**Comment by frieda-huang** [comment]
Hi @amirshawn! It seems like this issue has been inactive for some time, but I found [Windsurf's cascade feature](https://docs.codeium.com/windsurf/cascade) to be relevant here. Though, what they have is still not perfect—if I reject the first change, it would still keep generating the next steps. 

Some notable things include:
- See diffs and accept changes block by block
- See the reasoning of each change step by step

If there is no implemented solution for it yet, I would like to take this issue on!

**Comment by maximilize** [comment]
Claude Code has solved this issue quite perfectly. Before each edit of a file, it's possible to review the diff in an editor, even edit it or reject the edit and give feedback. It's a big game changer.
