### ISSUE TITLE
View contents of file when the agent makes a modifications

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4274]
**What problem or use case are you trying to solve?**
When the agent works on a certain file, it would be helpful if the editor would open or display the contents of that file

**Do you have thoughts on the technical implementation?**
Trigger the relevant behavior when the appropriate events are received

**Describe alternatives you've considered**

**Additional context**

**Comment by amanape** [comment]
I think it is safe to un-assign @tofarr from this issue. The frontend already receives the necessary events (e.g., reading a file) to trigger the appropriate changes.

I'll re-assign @tofarr with details if I find this issue needs it.

**Comment by xingyaoww** [comment]
Done in https://github.com/All-Hands-AI/OpenHands/pull/5508
