### ISSUE TITLE
[Bug]: Refreshing page exposes GitHub token

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4289]
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

If I start a session, then do CMD+R, the GITHUB_TOKEN shows up in the terminal

Normally it shows as `****`

<img width="617" alt="Screenshot 2024-10-09 at 10 11 00 AM" src="https://github.com/user-attachments/assets/ce3cfb0c-3590-404c-b703-cb468b055ea7">

### Current OpenHands version

```bash
main branch, in dev mode
```

### Installation and Configuration

```bash
dev mode with remote runtime
```

### Reproduction Steps

1. connect GH
2. start a task
3. cmd+R

**Comment by mamoodi** [comment]
I think this is resolved now? @rbren ?

**Comment by rbren** [comment]
Yes!
