### ISSUE TITLE
Add an option to disable delegation to browsing agent

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#4309]
**What problem or use case are you trying to solve?**

Delegation to browsing agent is (almost) not stoppable, unless CTRL+C everything, it eats tokens like a mad cookie monster!
The agent spends thousands of tokens to even get over the cookie acceptance prompt of Google's landing page,
especially if its not in English.

**Do you have thoughts on the technical implementation?**

An option like for LLM class, usable via config.toml or env or docker....

**Describe alternatives you've considered**

Deleting the browsing_agent /sarcasm 😂

**Comment by enyst** [comment]
@tobitege We have taught the main agent to browse the web again, is this still the same or does browsing behave more reasonably now?

**Comment by tobitege** [comment]
I just tried with v0.13 and it seems to work much better now, closing this for now. :)
