### ISSUE TITLE
[Bug]: Feedback sending is broken in main

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#4348]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Clicking the thumb down and confirming the popup causes the following red toast to appear:
`Failed to share, please contact the developers: TypeError: R.body is undefined`

In terminal also:
`INFO:     127.0.0.1:38594 - "POST /api/submit-feedback HTTP/1.1" 422 Unprocessable Entity`

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

WSL on Windows

**Comment by mamoodi** [comment]
Going to bump this up to critical since the feedback is quite important.
