### ISSUE TITLE
[Bug]: HumanEval Inference - 'Series' object has no attribute 'task_id

### ISSUE THREAD

**Issue by Ethan0456** [All-Hands-AI/OpenHands#4363]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I was trying to run the `run_infer.sh` script for the Humanevalfix benchmark. However, when executing the script, I encountered an error where the code was referencing a non-existent column task_id.

1. Install OpenHands using the [Development Workflow](https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md).
2. Execute HumanEvalFix evaluation bash script.

### Expected behavior

The script should run successfully without errors.

### Proposed Solution

It seems the `task_id` column was renamed to `instance_id`, but the change hasn't been applied consistently throughout the code. To fix this, all references to `task_id` should be updated to `instance_id` across the script to ensure consistent naming and avoid attribute errors.

### OpenHands Installation

Development workflow

### OpenHands Version

0.9.8

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

```
10:51:27 - openhands:ERROR: shared.py:311 - ----------
Error in instance [Python/0]: 'Series' object has no attribute 'task_id'. Stacktrace:
Traceback (most recent call last):
  File "/Users/abhijeetsingh/project-repos/OpenHands/evaluation/utils/shared.py", line 281, in _process_instance_wrapper
    result = process_instance_func(instance, metadata, use_mp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhijeetsingh/project-repos/OpenHands/evaluation/humanevalfix/run_infer.py", line 204, in process_instance
    sid = _get_instance_id(instance)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abhijeetsingh/project-repos/OpenHands/evaluation/humanevalfix/run_infer.py", line 102, in _get_instance_id
    return instance.task_id.replace('/', '__')
           ^^^^^^^^^^^^^^^^
  File "/Users/abhijeetsingh/project-repos/OpenHands/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'task_id'

----------[The above error occurred. Retrying... (attempt 1 of 5)]----------
```

**Comment by suranah** [comment]
We could not add evaluation as a tag, which is something this is related to. We will raise a PR to fix this soon. 

NB: we are adding DiscoveryBench to evals (thanks for inputs @neubig); we encountered this issue while testing other benchmarks.
