### ISSUE TITLE
[Feature]: Interactive browser window

### ISSUE THREAD

**Issue by rooa** [All-Hands-AI/OpenHands#4389]
**What problem or use case are you trying to solve?**

- Agents start a web app but the browser is view-only, making it difficult to quickly test the outcome.

**Describe the UX of the solution you'd like**

- Users can go to the address bar of the browser view and explicitly type in URL
- Users can interact with the frontend (to test the UI).

**Do you have thoughts on the technical implementation?**

N/A.

**Describe alternatives you've considered**

- The alternative is to let docker pass through all ports with `docker run --net=host` (with the added documentation) cc: @neubig 

**Additional context**

N/A.

**Comment by kripper** [comment]
See: github.com/langchain-ai/langgraph/blob/main/docs/docs/tutorials/web-navigation/web_voyager.ipynb

**Comment by rishi8011** [comment]
@mamoodi  can you show me way to implement or use this interactive browser ??

**Comment by mamoodi** [comment]
@rishi8011 you can't use an interactive browser because currently it's not interactive. You and the user that created issue would like that to be the case.

I will say that the browser is in beta phase and it might go through a large change in the future.
