### ISSUE TITLE
[Bug]: code discreptancy between images_urls and image_urls

### ISSUE THREAD

**Issue by tobitege** [All-Hands-AI/OpenHands#4399]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The writing of `images_urls` (plural/plural) and `image_urls` (singular/plural) should be unified across the codebase, preferrably the latter one.
This can easily be overseen and lead to attribute errors during runtime if the wrong one were used.

**MessageAction**: `images_urls`
https://github.com/All-Hands-AI/OpenHands/blob/d47f3e854b10c93dc72c31b971ebe65b9451e3e7/openhands/events/action/message.py#L10

**ImageContent**: `image_urls`
https://github.com/All-Hands-AI/OpenHands/blob/d47f3e854b10c93dc72c31b971ebe65b9451e3e7/openhands/core/message.py#L38

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by sahilborse** [comment]
@tobitege I would like to work on this issue

**Comment by tobitege** [comment]
> @tobitege I would like to work on this issue
> 

Wonderful, thanks, assigned you.  👍
