### ISSUE TITLE
[Bug]: Sending feedback results in "Cannot read properties of undefined (reading 'message')"

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4414]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Currently, clicking the "thumbs-up" button results in an error: "Cannot read properties of undefined (reading 'message')"

<img width="408" alt="Screenshot 2024-10-15 at 1 52 22 PM" src="https://github.com/user-attachments/assets/98aa7dfb-58a0-4045-9edd-f410413355a8">

This happens both locally and in the online version.

### OpenHands Installation

Development workflow

### OpenHands Version

da23189e4c1de94240c4246b1ea7b0d4594e855b

### Operating System

MacOS

**Comment by neubig** [comment]
Maybe a duplicate of #4348

**Comment by mamoodi** [comment]
@neubig I kept getting this issue. I deleted all my containers, images, refreshed cache, then ran through main and it seemed fixed.

**Comment by mamoodi** [comment]
Good to close?

**Comment by mamoodi** [comment]
Closing as I'm pretty sure this specific issue is resolved.
