### ISSUE TITLE
[Evaluation] Add DiscoveryBench Benchmark

### ISSUE THREAD

**Issue by suranah** [All-Hands-AI/OpenHands#4465]
**What problem or use case are you trying to solve?**

Add DiscoveryBench to OpenHands' evaluation suite. DiscoveryBench contains 264 tasks collected
across 6 diverse domains, such as biology, economics, and sociology. It incorporates discovery workflows from published papers to approximate the real-world challenges faced by researchers. 

https://github.com/allenai/discoverybench/
https://x.com/mbodhisattwa/status/1811524569410531333

**Do you have thoughts on the technical implementation?**

The implementation will consist of:
1. Inference script to solve a DiscoveryBench task (goal & datasets)
2. Facetted evaluation script to rigorously evaluate the answers
3. Documentation for the OpenHands users 

**Additional context**

We are working on a PR for this and will seek OpenHands contributors' input to finalize it. Tagging other contributors to the PR - @Ethan0456, @majumderb and @neubig who helped us chart out the integration.

**Comment by majumderb** [comment]
Read details of the benchmark in this paper: https://arxiv.org/pdf/2407.01725v1
(A new version with more analysis is coming soon to arXiv)
