### ISSUE TITLE
[Bug]: Development guide instructions not working

### ISSUE THREAD

**Issue by bhackett1024** [All-Hands-AI/OpenHands#4490]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I tried following the development guide in https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md but after the `make run` step and visiting http://localhost:3001 the app was unable to select a model or start tasks using the agent.

I tracked down the problem to the frontend making OpenHands server requests (e.g. `/ws`, `/api/options/models`) to localhost:3001 instead of localhost:3000.

The code for getting the OpenHands server (getValidFallbackHost) changed recently in https://github.com/All-Hands-AI/OpenHands/pull/4413/files, which also set up a proxy to forward these requests from localhost:3000 to localhost:3001.  That forwarding doesn't seem to be working for me, though I don't know why (I'm not familiar with Vite configuration).

### OpenHands Installation

Development workflow

### Operating System

MacOS

**Comment by mamoodi** [comment]
Hmm I can't reproduce this issue. Couple of things:
* Delete all your openhands docker images
* Run `make build` and `make run` again
* When you go to `localhost:3001`, clean your cache with `CMD + Shift + R`

**Comment by Domiii** [comment]
Same problem here. @mamoodi's workaround does not do anything.

Some more observations:
* I open http://localhost:3001/app
* Status in the bottom left is stuck in `Starting up!`
* This is what I see in my console:
  * Some remotely fetched data expected to be json was actually `html`
  * `ws` connect fails (without clear reason):
  * Screenshot: ![image](https://github.com/user-attachments/assets/cab1ec33-f11b-492d-922f-12ab78ff7442)
* The network view also confirms @bhackett1024's point: The backend requests all seem to go to `3001`, not `3000`. Port forwarding/proxying is not working 🤷‍♀️ -
  ![image](https://github.com/user-attachments/assets/086b5327-be99-4a56-9de6-6dfd88f11bcb)

**Comment by Domiii** [comment]
## Possible Workaround?

* I restarted it a bunch of times. Also started it in `dev` mode:
  ```sh
  cd frontend && npm run dev
  ```
  ```sh
  make start-backend
  ```
* Suddenly, it seems to be proxying correctly 🤷‍♀️

**Comment by mamoodi** [comment]
@amanape there was another similar issue. Do you know what may be causing this?

**Comment by amanape** [comment]
Weird. I'll take a deep look into this tomorrow. Thanks for the all the details, @Domiii!

**Comment by amanape** [comment]
May be related https://github.com/All-Hands-AI/OpenHands/issues/4362

**Comment by amanape** [comment]
@bhackett1024 @Domiii It is correct to see requests being sent to `localhost:3001` since the requests are proxied through the frontend server to the backend server

https://github.com/All-Hands-AI/OpenHands/blob/a20da54e3afd498027fc4eaa1c5cae6fb37ba9dd/frontend/vite.config.ts#L70-L85

I am struggling to replicate the issue. Try running the app in incognito and let me know if the same issue persists. If it does not, then it is as @mamoodi suggested and has something to do with your browser cache.

**Comment by rbren** [comment]
@Domiii @bhackett1024 can you try checking out this branch and running `make run`? https://github.com/All-Hands-AI/OpenHands/pull/4591

**Comment by Domiii** [comment]
> @Domiii can you try checking out this branch and running `make run`? #4591

Not sure.
I am running into this consistently now: https://github.com/All-Hands-AI/OpenHands/issues/4607

**Comment by gfargo** [comment]
I've been running into this when attempting to boot another instance of All Hands on another port.  Not sure if this is expected behavior, the container displays the correct port mapping in Docker Desktop however browser fails to resolve the URL in the browser.

**Comment by rbren** [comment]
@gfargo this particular issue has been solved on main. Can you open a new issue with more details?

**Comment by gfargo** [comment]
Definitely! I’ll take a look to see if it persists when booting up a new
container today.

If so I’ll file a new issue 🙌
