### ISSUE TITLE
Product Analytics in OpenHands

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4533]
## Summary

Hi all!

The OpenHands community has built an incredible application, and many of us are already getting a ton of value out of it on a daily basis. But we're currently working on the roadmap, and unfortunately we're flying blind–we have very little data on how people are using OpenHands, and where they're getting stuck.

Here's a proposal, which we'd love the community's feedback on.

## Motivation

In order to ensure OpenHands can continue to improve, we need analytics to give us insight into how the product is working for real people.

**We also need to do this ethically and with users' consent.**

## Technical Design

We intend to use [PostHog](https://posthog.com/) for analytics. Like OpenHands, PostHog is fully open source. 

We’re thinking about using a subset of PostHog’s features across three areas: The https://www.all-hands.dev/ website (including docs), the OSS app, and the hosted app. 

Here’s what we’re thinking about using and where:

  | OpenHands | All Hands Website | All Hands SaaS
-- | -- | -- | --
[Web analytics](https://posthog.com/web-analytics) | x | x | x
[Product analytics](https://posthog.com/product-analytics) | x | x | x
[Session replay](https://posthog.com/session-replay) |   | x | x
[Feature flags](https://posthog.com/feature-flags) |   |   | x
[Experiments](https://posthog.com/docs/experiments) |   |   | x

### OpenHands
We want to keep the information we gather from the open source application minimal, in order to protect our users' privacy. But we also need some high-level data about what features people are using and where they might be getting stuck.

We will only gather high-level statistics about which pages are loaded, which buttons are clicked, etc. We will NOT gather any potentially sensitive information, like messages sent to the agent, the contents of files, commands that are run, etc.

We will have an easy way to opt-out of these analytics for any user who wants their usage to be 100% private.

### All Hands Website
We plan to add a bit more analytics on the All Hands website, and within the docs. This will be similar to the analytics that most websites gather: we'll look at what pages are being loaded, and how users are navigating those pages. We'll get insight into users’ journeys through landing page and docs, and which blog posts get the most traffic.

### All Hands SaaS
As many of you know, we're building a hosted version of OpenHands, which will run on our infrastructure. We plan to add some analytics to a subset of the info we collect, as well as the ability to run A/B tests to see whether our changes have the intended effect.

We understand that a lot of the content in the UI is sensitive (e.g. file contents, commands, API keys, etc). Fortunately, PostHog allows us to [block entire HTML elements](https://posthog.com/docs/session-replay/privacy#other-elements) from ever being captured, and we would use this ability to prevent capture of your work.

Just like with the open source version, we'll make it easy for users to opt-out of any tracking with PostHog.

## Alternatives to Consider
We've also considered using Mixpanel or Amplitude, but we like that PostHog is open source.

## Additional context

Getting analytics into OpenHands will be a huge help in figuring out where to focus our efforts.

But it’s important to do this alongside the community, so we want know: how does this land? Are there things we can clarify? Any concerns? We understand that this is a sensitive topic, and we want to have an open discussion before making any changes here.

**Comment by luizanao** [comment]
@rbren would you consider controlling the model display based on env vars?
My intention is to remove any developer friction in using the tool, and I can see how people might get confused about whether they should/are allowed to send analytics.
It would be great if we could just have a flag that we can control via deploy variables to have a default behavior for this.

what you think?

**Comment by rbren** [comment]
We could definitely add something to [config.json](https://github.com/All-Hands-AI/OpenHands/blob/main/frontend/public/config.json). Happy to accept a PR here!

As a side note, it sounds like you're serving a multi-tenant version of OH. This can be really tricky, and is what we're building our commercial offering around. Happy to chat about providing some more support here if you'd find it helpful!

**Comment by neubig** [comment]
I think that this is finished?
