### ISSUE TITLE
[Evaluation]: On evaluation, log actual messages sent to LLMs

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4544]
**What problem or use case are you trying to solve?**

On evaluation, such as SWE-bench, we are currently logging the instruction for each individual repo, but not actually logging the queries sent to the LLMs.

This can be a problem with respect to version control and reproducibility, because the underlying system prompt may change due to changes in the agents. It would be good if we could log/save all of the messages that are sent as well.

**Describe the UX of the solution you'd like**

The actual LLM messages are (optionally) logged along with the "history".

**Do you have thoughts on the technical implementation?**

We'll have to have a way to monitor/log all LLM calls, which might not be trivial at the moment. It'd probably require modifying the llm class. Also, we might consider using some sort of logging provider, e.g. through the litellm proxy or something else.

**Comment by xingyaoww** [comment]
I think this is already possible to do:
https://github.com/All-Hands-AI/OpenHands/blob/e878741ae748222b34bb724cf71bc5e2881a7172/openhands/llm/llm.py#L197-L206

But it just have issue logging when running this in multiprocessing 🤔

**Comment by enyst** [comment]
We are currently saving them in State as `llm_completions`. They are in the .jsonl file if the option `llm_config.log_completions=true`.

I'd love some too, but I haven't been very able to get them except with Deepseek lately.

**Comment by xingyaoww** [comment]
Just add `log_completions=true` in LLM config

**Comment by enyst** [comment]
Hah, you're fast Xingyao 😂

**Comment by neubig** [comment]
OK, sounds good! Practically, are these stored when we do evals? I don't think that they're included in output.jsonl, which is the main artifact resulting from evaluation.

**Comment by xingyaoww** [comment]
This is stored in output.jsonl if you turn them on :)

https://github.com/All-Hands-AI/OpenHands/blob/e878741ae748222b34bb724cf71bc5e2881a7172/evaluation/swe_bench/run_infer.py#L435

**Comment by neubig** [comment]
OK, should we turn it on by default for evaluation maybe? I'm thinking of how we can prevent the reproducibility issues that we had previously.

**Comment by xingyaoww** [comment]
@neubig the issue there would be we will end up with very large file :( - and also there's an issue where this is stuck & not runnable in parallel (i spent couple hours a while back and haven't been able to figure out why)
