### ISSUE TITLE
Multi Model config.toml help

### ISSUE THREAD

**Issue by ZackGitHub11** [All-Hands-AI/OpenHands#4555]
I need help setting up the config.toml file. I'm trying to configure multi-agent collaboration using OpenHands and I'm following the development guide (Make Run). Below is an example of my config.toml file (I've hidden the base URL, keys, and name). My goal is to assign specific agents to specific tasks, but I'm unsure how to set this up properly.

Getting error:
WARNING - llm config group llm.eval_Agent2 not found, using default config
WARNING - llm config group llm.eval_Agent3 not found, using default config

![Screenshot 2024-10-24 165156](https://github.com/user-attachments/assets/107c27d7-eaf6-42d2-a9c5-18cd4b5feed4)

**Comment by enyst** [comment]
I'm trying to replicate that, but it seems to work, I don't see what is different for you...
e.g. I have:
```
[core]
...stuff

[llm]
...stuff

[llm.or-qwen]
model="openrouter/qwen/etc"
...

[agent.BrowsingAgent]
llm_config="or-qwen"
```

Then I run: `main.py -l deepseek`. When it starts Browsing Agent, I see it has "openrouter/qwen...", not the main "deepseek", which is what I expected. 🤔
 
How exactly are you starting the app?

**Comment by ZackGitHub11** [comment]
@enyst Thank you for your reply! I spotted my mistake—I had mistakenly included "llm." in "llm.eval_Agent2" while defining llm_config = "llm.eval_Agent2". 

Removing "llm." resolved it, and now it correctly loads the LLM as defined in config.toml. 

I'm running my development environment using "make run".

Closing the issue. Cheers!! 🍺

**Comment by enyst** [comment]
Oh, the explanation was hiding in plain sight, of course I didn't see it! 😂 

Thanks for the heads-up, glad you got it solved!
