### ISSUE TITLE
request for swe-bench-verified support

### ISSUE THREAD

**Issue by UbeCc** [All-Hands-AI/OpenHands#4559]
Hi developers!
Thanks for your contribution in creating an evaluation infra. Will OpenHands add swe-bench-verified images these days? Thanks!

https://huggingface.co/datasets/princeton-nlp/SWE-bench_Verified

**Comment by xingyaoww** [comment]
I believe SWE-Bench Verified is currently supported:

https://github.com/All-Hands-AI/OpenHands/tree/main/evaluation/swe_bench#run-inference-on-swe-bench-instances

You can run something like:
```
./evaluation/swe_bench/scripts/run_infer.sh llm.model HEAD CodeActAgent 500 30 1 'princeton-nlp/SWE-bench_Verified' test
```
to run on 500 instances from SWE-Bench verified with 30 max turns.

Feel free to re-open if you run into any issues.
