### ISSUE TITLE
[Eval] Add ScienceAgentBench

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4571]
**What problem or use case are you trying to solve?**

https://arxiv.org/abs/2410.05080

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamoodi** [comment]
Seems to have been added: https://github.com/All-Hands-AI/OpenHands/tree/main/evaluation/scienceagentbench
