### ISSUE TITLE
Create Self-Discover Prompting Agent

### ISSUE THREAD

**Issue by yimothysu** [All-Hands-AI/OpenHands#46]
Based on [this blog post](https://tomhipwell.co/blog/devin/), Devin might be using a new prompting technique such as Self-Discover: https://arxiv.org/abs/2402.03620. We might want to consider a similar prompting technique, since Self-Discover seems to be noticeably better than chain-of-thought.

**Comment by rahulraikwar00** [comment]
I guess we can combine both approaches and it is technically feasible to combine to elevate user experience and build better faster response?
What's your thoughts on this?

**Comment by neubig** [comment]
Thanks! I'll take a closer look in a bit. I'd also be interested in hearing from @rbren , who created a nice backend draft: https://github.com/OpenDevin/OpenDevin/pull/35

**Comment by rbren** [comment]
Love it! Anything that lets the LLM plot out its own path is powerful--but it's also potentially expensive and unpredictable. It'll be really interesting to experiment with some self-discover prompts.

My hope is that we can do something like this:
* Set up a mini evaluation pipeline (something cheaper than SWE-bench)
* Have a pluggable/customizable set of prompts
* Let folks experiment with different prompt styles (e.g. self-discover vs CoT)

My PR has a first pass at the eval pipeline, but the prompts are hard-coded. Wouldn't be too hard to start customizing though!

**Comment by JustinLin610** [comment]
Yes,  it is urgent to build a small evaluation pipeline. Xingyao just uploaded a container https://github.com/OpenDevin/OpenDevin/pull/60, and we also have SWE-Lite or Jiaxin just found out what the Devin team tested. I think it will be quickly done

**Comment by tobitege** [comment]
...should not get stale again 😁

**Comment by sb-git-cloud** [comment]
Hey I started looking into this and would be happy to take it on!

**Comment by sb-git-cloud** [comment]
First draft is working. Now working on prompt improvements.

**Comment by sb-git-cloud** [comment]
First beta version: https://github.com/OpenDevin/OpenDevin/pull/3437

**Comment by sb-git-cloud** [comment]
still planning to run some benchmarks before merging it
