### ISSUE TITLE
[Bug]: [Hosted version] Github clone doesn't appear to work

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#4614]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Note: I think this might depend on having a workspace configured or not, and I can't reproduce that locally without manual changes at the moment. But it might relevant because we will stop recommending a workspace and/or not mount it automatically soon. So I tried how it currently works on the hosted version only:

- I had a few errors and reloads in the tab
- entered a Github token in the Account
- made a "new project"
- chose a GitHub repository (the token has many perms on that repo)
- entered a message (told the agent to pull main to update it)
=> Expected: to clone the repo in the workspace
=> Result: the workspace has only "Lost+found".

- I asked the agent to do a `ls`
=> Expected: to see the contents of that repo at least in terminal
=> Result: it saw "Lost+found".

Note: there was no visible error, and the agent status never changed to ERROR (during this "New project")

Cc: @amanape 

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by jkpjkpjkp** [comment]
seconded. i'm a new user and it's confusing to see nothing coming up from my repo (an empty workspace showed up besides dialogues). still finding solution (will look into the workspace setting u mentioned). thks!

**Comment by mamoodi** [comment]
This seems important. If you select a github repo, I'm guessing it's supposed to know that it should just clone it?
@amanape is my understanding correct?

**Comment by mamoodi** [comment]
Is this still an issue? I've played around with this and it seems to work.

**Comment by enyst** [comment]
It does appear to work for a while now.

**Comment by amanape** [comment]
I think the original issue was some edge case (e.g., signing in mid-session, exiting, selecting repo, reload, go back, select repo or something wack like that). I didn't get the opportunity to look into it deeply yet (sorry for the 3 week delayed response 😅)

**Comment by mamoodi** [comment]
Going to close this as I think it's fixed and there's been a lot of improvements here. Please reopen if I'm mistaken.

**Comment by enyst** [comment]
It's fine to close. It obviously works usually, and while I do meet the occasional glitch, we can look at those as they come.
