### ISSUE TITLE
[Bug]: Permission issue with new file_editor

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4623]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

New file editor introduced in https://github.com/All-Hands-AI/OpenHands/pull/4537 seems to causing issues when the agent is running as "openhands":

<img width="1349" alt="image" src="https://github.com/user-attachments/assets/076416aa-e0a5-416b-8044-b7b926b03e68">

### OpenHands Installation

Docker command in README

### Operating System

Linux

**Comment by xingyaoww** [comment]
This is actually expected..
Normal files own by OpenHands will be successfully edited - added a test here: https://github.com/All-Hands-AI/OpenHands/pull/4628

**Comment by mamoodi** [comment]
If this is expected, should the bug be closed?

**Comment by xingyaoww** [comment]
Let's close!
