### ISSUE TITLE
Add SANBOX_USER_ID to how to run quickstart

### ISSUE THREAD

**Issue by Pogayo** [All-Hands-AI/OpenHands#4654]
I was following the instructions on how to run OpenHands:
docker pull docker.all-hands.dev/all-hands-ai/runtime:0.11-nikolaik

```
docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.11-nikolaik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.11

```

Docker run exits when SANDBOX_USER_ID environment variable is not set.  Add a default SANDBOX_USER_ID in the entrypoint.sh file or set it in the docker run container for a seamless first-time running.

**Comment by neubig** [comment]
Thanks for pointing this out @Pogayo ! We I was able to confirm the error, so we should correct this ASAP.

**Comment by mamoodi** [comment]
@Pogayo are you able to try the latest 0.12 (Instructions in README) and see if it resolves this issue for you please?

**Comment by neubig** [comment]
I have confirmed that there is no problem with
```
docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.11-nikolaik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.12
```

**Comment by Pogayo** [comment]
@mamoodi @neubig no problem with 0.12. Thanks.
