### ISSUE TITLE
Adding llama-3.1-nemotron-70b-instruct

### ISSUE THREAD

**Issue by David-Sola** [All-Hands-AI/OpenHands#4660]
Currently it is not possible to add the model from Nvidia.
It would be great for this possibility as the api costs are quite low.

**Comment by mamoodi** [comment]
It doesn't work if you enable `Advanced Options` and set it as the model?
Here is the litellm docs: https://docs.litellm.ai/docs/providers/nvidia_nim

Unless it's not supported by litellm

**Comment by neubig** [comment]
Yes @David-Sola , you could access the model via any hosting API that supports the model. For instance OpenRouter should work

**Comment by mamoodi** [comment]
Going to close this as you can specify the model using `Advanced Options`, you don't need it in the dropdown.
