### ISSUE TITLE
[Bug]: Commands run in the terminal never return

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4675]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Run any command in the terminal window of OH. For me it just sits there, and I have to refresh the page to see the output

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by mamoodi** [comment]
This is good to close right?

**Comment by rbren** [comment]
Looks like amanape fixed it!
