### ISSUE TITLE
[Bug]: Vertical overscroll with long repo names

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4676]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

If you have a really long repo name, the page overscrolls vertically

We should prevent wrapping on this line, and instead have an ellipsis truncation

<img width="512" alt="Screenshot 2024-11-01 at 5 01 41 AM" src="https://github.com/user-attachments/assets/77e3ae9c-ef45-4700-9a1d-6807817f5ffc">

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by mamoodi** [comment]
I'm going to close this bug because the linked bug has a better description and is a duplicate. :D
