### ISSUE TITLE
[Bug]: Long delay before new messages unpause the agent

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4678]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

This is a flaky issue--no consistent way to repro that I can tell. I will try and spot a log pattern at least

Sometimes, when the agent is "waiting for user input", when I send a new message, nothing happens. If I refresh the page, the message is there (meaning it made it to the backend, so websocket is connected) and then the agent starts running.

EDIT: pretty sure it's actually a delay! the state changes only when a new event comes back from the agent. probably some async locking going on

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by enyst** [comment]
This sounds kind of like [something weird](https://github.com/All-Hands-AI/OpenHands/pull/4575#issuecomment-2451336353) I noticed on your branch. So this was on main. 🤔
