### ISSUE TITLE
[Bug]: Brief flicker of the input text when submitting

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4680]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When submitting an initial query from the home screen, a brief flicker can be observed of the text

### OpenHands Installation

Docker command in README

### OpenHands Version

0.12

### Operating System

MacOS

**Comment by fine20240123** [comment]
can you provide a  Screenshots or video? @amanape
