### ISSUE TITLE
[Bug]: if Jupyter Shell output has a long single line output, the UI container grows too wide and goes offscreen

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#4714]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

To repro:
- Make the agent run a python script in the jupyter shell that outputs a really long line
- Hint, maybe have a raw file with a single extra  wide line and just ask the agent to read the file
- In the UI, switch to the Jupyter tab, notice the UI will grow extra wide and potentially go off screen

Switching between the workspace and the Jupyter tab will also somehow make the outer container of the right hand side of the UI grow wider and squeeze the left side conversation box narrower.

I think the fix should be along the lines of adding `wrapLongLines={true}` to the `Syntaxhighlighter` in the `Jupyter.tsx` file.
However, even after adding that, the width of the jupyter container will still grow wider when switching between the workspace tab and the jupyter tab.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
Yep we've definitely seen the Jupyter tab act weird. Thanks for opening this issue!
