### ISSUE TITLE
Where is Workspace folder exactly?

### ISSUE THREAD

**Issue by jbosolutions** [All-Hands-AI/OpenHands#4719]
Hello, may you tell me where is the Workspace foldeR? i cant find it... i need to copy the generated files and i cant.

**Comment by mamoodi** [comment]
You can click on the `...` in the bottom right, then `Download as Zip` to copy all the files:
![Screenshot 2024-11-03 at 8 20 04 PM](https://github.com/user-attachments/assets/e17a36bb-e5ab-43a0-b530-aa76e3936cc5)

**Comment by mamoodi** [comment]
To further clarify, the workspace is in the runtime container. The only way you have access to it is through the download as zip. However, you can connect your filesystem like so: https://docs.all-hands.dev/modules/usage/runtimes#connecting-to-your-filesystem

If you do so, OpenHands will modify the directory that you specify in WORKSPACE_BASE and that's where the files will be.
