### ISSUE TITLE
[Bug]: SWE-bench evaluation harness fails because setuptools is not available in the conda channels for the ARM64 architecture

### ISSUE THREAD

**Issue by AlexCuadron** [All-Hands-AI/OpenHands#4724]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The Docker image build for ARM64 architecture is failing because the specified version of setuptools (38.2.4) is not available in the conda channels for the `ARM64/aarch64` platform.

### OpenHands Installation

Development workflow

### OpenHands Version

0.11.0

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

```
2024-11-03 16:00:28,104 - INFO - PackagesNotFoundError: The following packages are not available from current channels:

  - setuptools==38.2.4

Current channels:
```

**Comment by mamoodi** [comment]
Not quite the same error but sounds like the SWE-Bench doesn't officially support arm64?
https://github.com/All-Hands-AI/OpenHands/issues/4157#issuecomment-2387547678

**Comment by AlexCuadron** [comment]
True, hopefully they add support for it soon
