### ISSUE TITLE
Requests for slack link update

### ISSUE THREAD

**Issue by UbeCc** [All-Hands-AI/OpenHands#4725]
I've found the link to join slack (https://openhands-ai.slack.com/join/shared_invite/zt-2oikve2hu-UDxHeo8nsE69y6T7yFX_BA#/shared-invite/error) is invalid. Could you please update it. Thanks!

**Comment by mamoodi** [comment]
It's likely these slack invites keep expiring. Can you try this for now: https://join.slack.com/t/openhands-ai/shared_invite/zt-2tsz61h2a-nkAjpuoPYdq961SU7NsvEw

**Comment by rbren** [comment]
@UbeCc where did you find that link? it's not the one I'm seeing in the README

**Comment by UbeCc** [comment]
> @UbeCc where did you find that link? it's not the one I'm seeing in the README

I saw the link in the website (https://docs.all-hands.dev/). There is a button ref to "Slack, Join us"

**Comment by mamoodi** [comment]
Thanks for bringing it to our attention! It has been fixed now.
