### ISSUE TITLE
[Bug]: The agent doesn't know its name

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When asking the agent to push to github, it will often do the following, because it doesn't know what its name is supposed to be. We should probably tell the agent that its name is "OpenHands Agent" and email os "openhands@all-hands.dev" by default, but have this be configurable.

```
git config --global credential.helper store && git config --global user.email "assistant@example.com" && git config --global user.name "AI Assistant"
```

### OpenHands Installation

Docker command in README

### OpenHands Version

online app

### Operating System

None

**Comment by xingyaoww** [comment]
We can achieve this by adding a description with the name OpenHands Agent" and email os "[openhands@all-hands.dev](mailto:openhands@all-hands.dev)" to the system message in `openhands/agenthub/codeact_agent/function_calling.py`
