### ISSUE TITLE
[Bug]: Inconsistent default SANDBOX_RUNTIME_CONTAINER_IMAGE value

### ISSUE THREAD

**Issue by zetomatoz** [All-Hands-AI/OpenHands#4749]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

**Current Behavior**

The SANDBOX_RUNTIME_CONTAINER_IMAGE environment variable has inconsistent values across the [documentation and compose.yml files](https://github.com/search?q=repo%3AAll-Hands-AI%2FOpenHands+runtime%3A0.9-nikolaik&type=code) (i.e runtime:0.9-nikolaik instead of runtime:0.12-nikolaik). This discrepancy can cause confusing runtime error messages that are difficult to troubleshoot. Additionally, the documentation does not clearly emphasize that the sandbox runtime’s source code version must be synchronized with the backend to prevent errors.

**Expected Behavior**

When OpenHands releases a new version, the SANDBOX_RUNTIME_CONTAINER_IMAGE value should be updated and consistent across all parts of the repository. The documentation should also explicitly state the importance of keeping the sandbox runtime and backend versions in sync.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.10, 0.11, 0.12

### Operating System

None

**Comment by mamoodi** [comment]
Thanks. The docker compose was written by a community member but is not actively supported. We will try to update it going forward.

**Comment by zetomatoz** [comment]
That sounds great! The `containers/dev/compose.yml` file is indeed very useful for debugging OpenHands in Docker for Windows, especially without needing WSL.

**Comment by mamoodi** [comment]
This has been resolved. All versions updated
