### ISSUE TITLE
[Documentation] When GITHUB_TOKEN is provided automatically through the UI

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4756]
**What problem or use case are you trying to solve?**

I don't know when the `GITHUB_TOKEN` is provided to the agent through the UI, and I don't believe this is documented anywhere. 

It would be good to have this documented in the documentation. Does anyone have an idea under what conditions the GITHUB_TOKEN is provided?

**Comment by amanape** [comment]
https://github.com/All-Hands-AI/OpenHands/blob/eeb23425090286523ab4fcf5d6a86a98c4b4bb4d/frontend/src/routes/_oh.app.tsx#L273-L278

Once the user arrives at `/app`, we check if there is a `ghToken` present. This is obtained after either inputting the token directly (OSS) or through GitHub OAuth (SaaS). `userId` is retrieved via GET request to the GitHub `/user` API.

If it is present, we export it to the shell environment.

**Comment by neubig** [comment]
OK, great. This should probably be added to the docs for GUI mode. Assigning to openhands-agent.
https://docs.all-hands.dev/modules/usage/how-to/gui-mode
