### ISSUE TITLE
[Bug]: Tool call metadata should NOT be None when function calling is enabled

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4783]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Manually run command in the client terminal (e.g., `pwd`)
2. Error is thrown

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

<img width="395" alt="image" src="https://github.com/user-attachments/assets/9afa3669-863f-4d16-97ff-9e5f21fffd3e">

**Comment by ug911** [comment]
I am still getting this issue when I connect a github repo. 

What is the solution for this?

**Comment by scosenza** [comment]
I'm also seeing this when attempting to have OpenHands run a bazel command:

Model: litellm_proxy/bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0

Prompt:
```
Run bazel build //projects/foo/...
```

Error:
```
Tool call metadata should NOT be None when function calling is enabled. Action: **CmdRunAction (source=EventSource.USER)** COMMAND: ba[A[A[B[Bzel bazel build //projects/foo/......bbb[D[D[C[C[C[D[D[D[D[D[Dbbb[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D
```
