### ISSUE TITLE
[Bug]: [Function calling] Context window exceeded for gpt4 models (1024 per tool)

### ISSUE THREAD

**Issue by Srishti-Chouhan** [All-Hands-AI/OpenHands#4803]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

On using gpt4 models, the agent keeps running into an issue of Context Window Exceeded. 

### OpenHands Installation

Development workflow

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/user-attachments/assets/b77739d1-4a68-4001-926b-e0cae5cd686a)

**Comment by mamoodi** [comment]
Related PR Xingyao is working on: https://github.com/All-Hands-AI/OpenHands/pull/4778

**Comment by enyst** [comment]
Thank you for the report! This fix is in `main` now.

**Comment by bjoernwuest** [comment]
Version 1.82.3 still affected by this problem.
`
Workflow execution finished with error {"error":{"error":{"message":"Provider returned error","code":400,"metadata":{"raw":"{\n  \"error\": {\n    \"message\": \"Invalid 'tools[2].function.description': string too long. **Expected a string with maximum length 1024, but got a string with length 1655 instead.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": \"tools[2].function.description\",\n    \"code\": \"string_above_max_length\"\n  }\n}","provider_name":"Azure"}**},"code":400,"message":"Provider returned error","stack":"Error: Provider returned error\n    at Stream.iterator (/usr/local/lib/node_modules/n8n/node_modules/openai/streaming.js:40:35)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at ChatOpenAI._streamResponseChunks (/usr/local/lib/node_modules/n8n/node_modules/@langchain/openai/dist/chat_models.cjs:1256:26)\n    at ChatOpenAI._streamIterator (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/language_models/chat_models.cjs:100:34)\n    at ChatOpenAI.transform (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:402:9)\n    at RunnableBinding.transform (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:883:9)\n    at ToolCallingAgentOutputParser.transform (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:391:26)\n    at RunnableSequence._streamIterator (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:1320:30)\n    at RunnableSequence.transform (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:402:9)\n    at wrapInputForTracing (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:275:30)\n    at pipeGeneratorWithSetup (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/utils/stream.cjs:271:19)\n    at RunnableLambda._transformStreamWithConfig (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:296:26)\n    at wrapInputForTracing (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:275:30)\n    at pipeGeneratorWithSetup (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/utils/stream.cjs:271:19)\n    at RunnableLambda._transformStreamWithConfig (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:296:26)\n    at RunnableSequence._streamIterator (/usr/local/lib/node_modules/n8n/node_modules/@langchain/core/dist/runnables/base.cjs:1320:30)"},"workflowId":"ybBa2sUSHqIgBCJb","file":"LoggerProxy.js","function":"exports.debug"}
`
