### ISSUE TITLE
[Bug]: Clicking Jupyter bar expands it massively

### ISSUE THREAD

**Issue by outdoorsdev** [All-Hands-AI/OpenHands#4817]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Clicking the Jupyter bar makes it expand way out to the right of the screen. It actually makes all of the bars expand. If i click back to workspace, it shrinks back down.

This is the element i'm clicking

<a data-discover="true" class="px-2 border-b border-r border-neutral-600 bg-root-primary flex-1 first-of-type:rounded-tl-xl last-of-type:rounded-tr-xl last-of-type:border-r-0 flex items-center gap-2" href="/app/jupyter"><svg width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M6.6665 5.30664V6.00035V10.0004H5.6665V6.69407L4.82461 6.9747L4.50839 6.02601L6.00839 5.52601L6.6665 5.30664ZM20.6665 8.75035H11.7776V7.25035H20.6665V8.75035ZM20.6665 15.7504H11.7776V14.2504H20.6665V15.7504ZM5.23029 12.4381C5.71219 12.295 6.45934 12.1944 6.93213 12.8051C7.18578 13.1327 7.2182 13.5518 7.16656 13.8949C7.09092 14.3975 6.76355 15.0189 6.48884 15.5403C6.40144 15.7062 6.31938 15.862 6.25244 16.0006H7.16656V17.0006H4.48291C4.73561 16.5635 4.96935 16.163 5.19921 15.769C5.44194 15.3531 5.68033 14.9445 5.93213 14.5083C6.0589 14.2887 6.30178 13.7241 6.09229 13.4535C6.00257 13.3376 5.76468 13.2118 5.42432 13.3129C5.11672 13.4042 4.84136 13.6504 4.65037 13.8212L4.64324 13.8276L4.5128 12.7453C4.72415 12.6312 4.97299 12.5145 5.23029 12.4381Z" fill="#A3A3A3"></path></svg>Jupyter</a>

Tried using firefox and chrome for this, same issue.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.12.2

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

![image](https://github.com/user-attachments/assets/26646bda-5247-4dd2-bcf1-9ab8c46f351c)

**Comment by mamoodi** [comment]
Potential fix in this PR: https://github.com/All-Hands-AI/OpenHands/pull/4818

**Comment by amanape** [comment]
Hey could you try running on the latest changes and see if the issue still persists? The recent fix (#4818) should have taken care of it

**Comment by mamoodi** [comment]
Do not see this happening anymore. Closing.
