### ISSUE TITLE
[Bug]: Workspace's vertical bar doesn't align

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4827]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

See screenshot - the vertical bar doesn't align

<img width="748" alt="image" src="https://github.com/user-attachments/assets/5c747560-7d5e-4524-a478-d81282821cb4">

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

Linux

**Comment by diwu-sf** [comment]
These were not supposed to be aligned btw, it depends on the width of the monitor, example:
![image](https://github.com/user-attachments/assets/5347ee49-901b-447f-bdc0-ce265c4ccf99)

**Comment by xingyaoww** [comment]
@diwu-sf ahhhhh you are right - close this one
