### ISSUE TITLE
[Bug]: Regression on copy-paste text into the chat prompt input box

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#4859]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

This is a regression from https://github.com/All-Hands-AI/OpenHands/pull/4762

Copy pasting normal text into the input prompt box no longer works.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by diwu-sf** [comment]
Fix looks fine, would need to hand test it for verification. Can the agent
write a unit test for this?

**Comment by mamoodi** [comment]
@diwu-sf this should be fixed in the latest 0.13 or main line. Can you try with that and confirm? It worked for myself so want to make sure my understanding is correct.

**Comment by neubig** [comment]
Hey @diwu-sf , I think this was already fixed in https://github.com/All-Hands-AI/OpenHands/pull/4832

Could you please try with the most recent version, as @mamoodi suggested? I tried it now and it's working for me.

**Comment by diwu-sf** [comment]
It's fixed

Related feature request would be:
- if a TXT or LOG file is dragged into the input box
- attach it into the /workspace as a content file, and allow the agent to read the file

similar to how there's image upload support, being able to upload a few text files and have them pre-populated into the /workspace would be convenient for debugging tasks where logs get added
