### ISSUE TITLE
[Bug]: UnixHTTPConnectionPool Timeout error when establishing a connection

### ISSUE THREAD

**Issue by PierrunoYT** [All-Hands-AI/OpenHands#4862]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

A timeout error occurs when trying to establish a connection to the Runtime server. The server is configured to localhost

There was an error while connecting to the runtime.
UnixHTTPConnectionPool(host='localhost', port=None):
Read timed out. (read timeout=60)

Start Docker container according to README instructions
Attempt to establish a connection to the runtime server
The timeout error occurs after 60 seconds

### OpenHands Installation

Docker command in README

### OpenHands Version

0.13

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

After reloading the page the Agent started to work

**Comment by mamoodi** [comment]
Do you always run into this issue or is it intermittent?

**Comment by PierrunoYT** [comment]
I only tried it once
