### ISSUE TITLE
[Bug]: OpenHands frontend UI still displays text after the message have been sent

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#4866]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

OpenHands frontend UI still displays text after the message have been sent (hitting enter). We should clean-up the ChatInput box after sent.

<img width="385" alt="image" src="https://github.com/user-attachments/assets/03b5c405-205d-445c-a205-bf462869f09b">

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
What version did you encounter this in?

**Comment by xingyaoww** [comment]
Oh it was on my PR: https://github.com/All-Hands-AI/OpenHands/pull/4745

Not sure if this is already fixed or not

**Comment by mamoodi** [comment]
@xingyaoww this doesn't seem to happen on both 0.13 or main. Probably something wrong with your PR. Going to close it.
