### ISSUE TITLE
OpenHands Capabilities

### ISSUE THREAD

**Issue by Innoinva** [All-Hands-AI/OpenHands#4870]
I have a few questions about the capabilities of OpenHands for designing software architecture and implementing it. 
Who can answer my questions?

**Comment by mamoodi** [comment]
Hello. If you can, I would recommend joining the Slack server since all the maintainers are there and can likely answer the questions. A github issue won't be a great platform to go back and forth for your questions.

**Comment by Innoinva** [comment]
What is the link to the Slack server you are recommending? Is there any email to contact if Slack cannot be accessed? Can anyone join the Slack? Can they answer questions on how to use Open Hands for custom advanced software development?

**Comment by tobitege** [comment]
The link is directly on the repo main page

**Comment by Innoinva** [comment]
Is there any email to contact if Slack cannot be accessed? Can anyone join the Slack? Can they answer questions on how to use Open Hands for custom advanced software development? 
Can you please delete this Issue thread with its comments?

**Comment by mamoodi** [comment]
Yes anyone can join Slack.
It really depends on your question. People will try their best to answer.
You don't need to delete, just click the `Close` button below and the issue will close.

**Comment by Innoinva** [comment]
Thank You. I prefer my comments and this thread are deleted. Can you delete on your end?
