### ISSUE TITLE
Use OpenHands with udocker

### ISSUE THREAD

**Issue by Qarqor5555555** [All-Hands-AI/OpenHands#4890]
how to run openhands with udocker on colab 
not docker
docker pull docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik

docker run -it --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.13

**Comment by mamoodi** [comment]
I'm not sure what the answer will be here. If the README doesn't work with udocker, it will require work to get it working.
Unless someone else has run it like so and knows the answer/setup.

**Comment by werruww** [comment]
README
udocker is not mentioned
I want to run Docker imsage  in Colab because I want to run OpenHands and like this


And I failed to get that to work.

**Comment by werruww** [comment]
are you run 
https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md
on colab

**Comment by diwu-sf** [comment]
Stop trying to run this on Colab. Run it on your actual computer.
