### ISSUE TITLE
not run

### ISSUE THREAD

**Issue by werruww** [All-Hands-AI/OpenHands#4915]
docker pull docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik

m@DESKTOP-VKFHU30:~$ sudo docker run -it --privileged --rm --pull=always \
> --network host \
> -e LLM_API_KEY="ollama" \
 LLM_> -e LLM_BASE_URL="http://127.0.0.1:11434" \
> -e LLM_OLLAMA_BASE_URL="http://127.0.0.1:11434" \
> -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.12-nikolaik \
v /var/r> -v /var/run/docker.sock:/var/run/docker.sock \
> -p 3000:3000 \
> --add-host host.docker.internal:host-gateway \
-name op> --name openhands-app \
> docker.all-hands.dev/all-hands-ai/openhands:0.12
0.12: Pulling from all-hands-ai/openhands
Digest: sha256:2e7382f8ab4defa232071ddae3bc726a25373f4b08f68aee5a3eff5af412b597
Status: Image is up to date for docker.all-hands.dev/all-hands-ai/openhands:0.12
WARNING: Published ports are discarded when using host network mode
Starting OpenHands...
Running OpenHands as root
INFO:     Started server process [10]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:3000 (Press CTRL+C to quit)

http://0.0.0.0:3000 notrun

http://127.0.0.1:3000 not run

localhost:3000 not run

wsl on win10

**Comment by mamoodi** [comment]
Looks like you're trying to get it working with ollama?
