### ISSUE TITLE
Make Agent Behavior customizable by modifying System Prompt

### ISSUE THREAD

**Issue by RajWorking** [All-Hands-AI/OpenHands#4924]
**What problem or use case are you trying to solve?**

Generally people want to customize the agent's behavior. 
E.g. make fewer code comments, or more. 

**Describe the UX of the solution you'd like**
Users should be able to inject a few lines into the system prompt.

**Do you have thoughts on the technical implementation?**
Maybe create a section in the navbar where user can type in any modifications to the system prompt that they like.

**Comment by h55nick** [comment]
My understanding is that https://github.com/All-Hands-AI/OpenHands/blob/main/.openhands_instructions should be doing this? It seems to work on the github-resolver work?

**Comment by grrowl** [comment]
+1 — especially for the codeact agent, [the system prompt defines the git user and email configuration](https://github.com/All-Hands-AI/OpenHands/blob/a2779fe2f6c9ab29508676f21242b1c6b88e2f67/openhands/agenthub/codeact_agent/prompts/system_prompt.j2#L4) in a way the LLMs don't seem to accept overriding in `user` messages like `.openhands_instructions` (ineffective example below):

```
10. Git - EXPLICIT INSTRUCTIONS:

- Before committing, configure git to use "admin" as the user.name and "admin@company.com" as the user.email.
```

**Comment by mamoodi** [comment]
I believe this is being worked on.

**Comment by neubig** [comment]
Hey @RajWorking , is this finished by https://github.com/All-Hands-AI/OpenHands/pull/4983?

**Comment by RajWorking** [comment]
Yes, we can close this now

**Comment by RajWorking** [comment]
Yes, we can close this now
