### ISSUE TITLE
[Bug]: stat: cannot statx '/var/run/docker.sock': No such file or directory

### ISSUE THREAD

**Issue by avonian** [All-Hands-AI/OpenHands#4933]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Running linux mint 22 and docker 27

When I start the container with the boilerplate instructions it works fine:
```
docker run -it --rm --pull=always \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    -e LOG_ALL_EVENTS=true \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.13
```

but if i try to provide a working directory, i get the aforementioned error

here's how i'm doing it:
```
export WORKSPACE_BASE=/path/to/my/project

docker run -it --rm --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -p 3000:3000 \
    -e LOG_ALL_EVENTS=true \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.13
```

any ideas what the problem might be?

### OpenHands Installation

Docker command in README

### OpenHands Version

0.13

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

0.13: Pulling from all-hands-ai/openhands
Digest: sha256:5444b2c3667898163db4ce052717dd59e5040cdd05d2e9621d9018215865ae86
Status: Image is up to date for docker.all-hands.dev/all-hands-ai/openhands:0.13
Starting OpenHands...
Setting up enduser with id 1000
stat: cannot statx '/var/run/docker.sock': No such file or directory

**Comment by shaxxx** [comment]
Instead of 

> -v /var/run/docker.sock:/var/run/docker.sock \

try with

> -v //var/run/docker.sock:/var/run/docker.sock \

Worked for me.

**Comment by shaxxx** [comment]
No, but this workaround was needed to get it working in Docker terminal bash shell.
Otherwise, I would get exactly the same error

**Comment by avonian** [comment]
hi thanks for the tip

it seems if i include the `-v /var/run/docker.sock:/var/run/docker.sock` line it works, with or without //

as follows:
```
docker run -it --rm --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    -e LOG_ALL_EVENTS=true \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.13
```

however when it opens up it doesn't actually show the working directory, i get the "What do you want to build?" message

i can confirm `echo $WORKSPACE_BASE` outputs the correct path

**Comment by avonian** [comment]
i tried to open a repo via github and got:
```
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
```
seems similar to the original error

**Comment by mamoodi** [comment]
@avonian can you try this:

docker run -it --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.14-nikolaik \
    -e LOG_ALL_EVENTS=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name openhands-app \
    docker.all-hands.dev/all-hands-ai/openhands:0.14

**Comment by mamoodi** [comment]
Also the initial "What do you want to build" will always show. Even if you specify a workspace.
You can just give it a prompt to go to the next page like "What python version is installed"

**Comment by avonian** [comment]
thanks again for the quick reply

i did as you suggested, and asked a question to open up the IDE, and the working folder is empty

either way appreciate everyones help here

**Comment by mamoodi** [comment]
Just want to make sure that when you provided WORKSPACE_BASE, you provided an absolute path that exists?

**Comment by avonian** [comment]
yep, absolute path, and when i do an echo it appears correctly, and i can cd to it exactly as its printed
