### ISSUE TITLE
[Bug]: Reloading an existing session fails to restore complete message history

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#4938]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Send initial query
2. Continue sending messages after OpenHands responds
3. Refresh page
4. Observe incomplete message history

It also seems to be inconsistent with which messages are returned. Sometimes only the user messages, other times a mix of both (but still incomplete)

### OpenHands Installation

Docker command in README

### OpenHands Version

0.13.0

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

It seems to be a frontend issue since sharing the trajectory does display the full history.

UPDATE: Every time you reload you get a different set of incomplete messages

**Comment by enyst** [comment]
FWIW I just saw this, and I noticed that when the agent doing something with this "invisible history", the whole list does get sent in the prompt. So I agree it seems a FE issue.
