### ISSUE TITLE
How to configure the Hugging Face API? There is no Hugging Face option in the UI.

### ISSUE THREAD

**Issue by AKGO47** [All-Hands-AI/OpenHands#4960]
How to configure the Hugging Face API? There is no Hugging Face option in the UI.
This configuration doesn't work.

  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.13
    container_name: openhands
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - LOG_ALL_EVENTS=true
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik
      - LLM_API_KEY=hf_xxx
      - LLM_MODEL=huggingface/Qwen/Qwen2.5-Coder-32B-Instruct
    ports:
      - 127.0.0.1:8102:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pull_policy: always
    tty: true
    stdin_open: true

**Comment by mamoodi** [comment]
Looking at the Litellm docs for huggingface: https://docs.litellm.ai/docs/providers/huggingface
The LLM_MODEL looks right.

What is the error you are getting? Trying to understand if it's having issues connecting to the LLM or something with the additional configs you have given it

**Comment by mamoodi** [comment]
CC @enyst would appreciate a look when you have some time 🙏
