### ISSUE TITLE
[Refactor]: Incorporate OpenHands resolver

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4963]
The [OpenHands resolver](https://github.com/All-Hands-AI/openhands-resolver/) evolved as a separate project from OpenHands, but now it has become a somewhat integral form factor for using OpenHands. Because of this, we would like to incorporate the resolver into OpenHands itself. This has a number of benefits:

1. Preventing updates to OpenHands from breaking the resolver because all the code will be in one place and we can run CI
2. Allowing for us to incorporate the resolver's actions into OpenHands's `listen.py` server, which will make it easier logistically to solve https://github.com/All-Hands-AI/openhands-resolver/issues/155 without spinning up a separate server

To solve this issue, we should:
1. Move all code from the openhands-resolver repo's `openhands_resolver` into the `openhands/resolver` directory of the OpenHands repo
2. Move all tests from the openhands-resolver repo into `tests/unit/` in the OpenHands repo
3. Replace the `.github/workflows/openhands-resolver.yml` in the OpenHands repo with `.github/workflows/openhands-resolver.yml`, then make any adjustments to reflect that the resolver will directly use the OpenHands repo
4. Move documentation from the openhands-resolver repo's `README.md` into the OpenHands repo's `openhands/resolver/README.md`.
5. Adjust the links in the OpenHands documentation web site in the `docs` directory to point to the OpenHands repo

**Comment by ryx2** [comment]
Excellent!

**Comment by neubig** [comment]
Done
