### ISSUE TITLE
[Bug]: Runtime Leak

### ISSUE THREAD

**Issue by tofarr** [All-Hands-AI/OpenHands#4967]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The exit project button does not remove the runtime - these leak right now
<img width="625" alt="image" src="https://github.com/user-attachments/assets/220217cd-34ab-435e-b6e0-91198e837c4c">

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/3487959d-c67a-432a-8be6-c5b307e0a8ff">

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

<img width="625" alt="image" src="https://github.com/user-attachments/assets/220217cd-34ab-435e-b6e0-91198e837c4c">

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/3487959d-c67a-432a-8be6-c5b307e0a8ff">

**Comment by rbren** [comment]
Probably my issue 👀
