### ISSUE TITLE
[Bug]: UI gets stuck on "failed to retrieve files" even after recovering

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4981]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

If `/list-files` fails, the UI doesn't recover, even if a subsequent call is OK

<img width="1039" alt="Screenshot 2024-11-13 at 2 55 35 PM" src="https://github.com/user-attachments/assets/676148bf-2d47-42e1-bc51-6219bfd8a5f3">

My guess is we're not clearing some `error` variable from the React component state

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
I haven't seen this in a while. Going to close. Please reopen or open a new issue if it occurs again.
