### ISSUE TITLE
Allow configureing the litellm Timeout

### ISSUE THREAD

**Issue by IMbackK** [All-Hands-AI/OpenHands#4995]
I seams (from the documentation) that there is no way to configure the litellm timeout, this is  a problem as i am trying to use openahands with a local openai compatible server (tabbyai and aphrodite). Sometimes this can be very slow to return a compleation request, in this case openhands will timeout even though there is nothing wrong, the backend just needs more time.

**Comment by mamoodi** [comment]
If you are running the docker command, you can add:
`-e SANDBOX_TIMEOUT=360`

or whatever timeout you require to the command, and I believe it will work.

If you are running through the development workflow, 
In the config.toml:
[sandbox]
timeout = 360

Let me know if this resolves your issue. I know for example if you wanted to install Java which takes a long time you have to modify this command.

If I misunderstood litellm timeout I apologize.

**Comment by neubig** [comment]
Hey @mamoodi , maybe it's actually `LLM_TIMEOUT`?

https://github.com/All-Hands-AI/OpenHands/blob/a753babb7a326282921d26ccbcc531cfee477ec0/openhands/core/schema/config.py#L37

**Comment by mamoodi** [comment]
Ah thank you! Please try the above suggestion by passing in:
`-e LLM_TIMEOUT=<your timeout>`

to the docker command.

**Comment by IMbackK** [comment]
yes that seams to do the trick, i seams it might make sense to document the options provided by envvar via config.py

**Comment by mamoodi** [comment]
Yep we have an issue open for that! I believe someone is working on it. Thank you!
