### ISSUE TITLE
How to add Deepseek model

### ISSUE THREAD

**Issue by redpintings** [All-Hands-AI/OpenHands#5013]
**What problem or use case are you trying to solve?**

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

How to add Deepseek model? I just started using it and I searched for a long time but couldn't find the place to add Deepseek 2.5. I saw in your documentation that the strongest open models are Llama 3.1 405 B and Deepseek v2.5, which perform quite well and even outperform some closed models.

But I don't know how to add it, please give me the specific steps, thank you very much

**Comment by chasinalts** [comment]
Why did you close this? did you figure it out? Ive tried MANY ways and have had no luck.
Please Advise if you can.
