### ISSUE TITLE
[Resolver] [Refactor]: Filter issues before fetching extraneous details

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5034]
# Current

When `openhands-resolver` is kickstarted, we fetch all possible issues or PRs and supplemental details (review threads, comments, etc). Only after all of this is done we filter to find the relevant issue/pr we've chosen to address.

# Refactor
It would be nice to filter the issues/PRs first before fetching the supplemental details. This would prevent excessively using Github API, which is especially helpful for larger repos.

---
*Moved from All-Hands-AI/openhands-resolver#338*

**Comment by malhotra5** [comment]
I believe this is resolved!
