### ISSUE TITLE
[Resolver] [Doc]: Update README with more instructions

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5035]
# Ability to update PRs using `openhands-resolver`. 
Once a PR is created using the resolver, you can add additional comments/reviews and assign the `fix-me` label. The resolver will working with the current PR, consider the feedback left, and update your PR with new changes.  

# Ability to use macros to invoke `openhands-resolver`
If you begin a issue/PR comment with `@openhands-agent`, `openhands-resolver` will automatically start resolving the issues/pr while address the current comment. The macro `@openhands-agent` can also be customized by creating `OPENHANDS_MACRO`  [repo variable](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#creating-configuration-variables-for-a-repository). The value of this variable will be used to kickstart the resolver

---
*Moved from All-Hands-AI/openhands-resolver#337*

**Comment by malhotra5** [comment]
I believe this is resolved!
