### ISSUE TITLE
[Resolver] [Feat]: Enable experimental mode for macro

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5037]
Using `openhands-resolver` with `fix-me-experimental` label allowed us to test unreleased versions of the resolver. 

We should allow something similar for macros too. Currently `@openhands-agent` will only run with the latest official release of `openhands-resolver`, which makes it hard to test unreleased versions.

---
*Moved from All-Hands-AI/openhands-resolver#334*

**Comment by malhotra5** [comment]
I believe this is resolved!
