### ISSUE TITLE
[Resolver] Disable "github" microagent within github resolver

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5039]
The OpenHands github resolver has a separate workflow for pushing to github, and some instructions in the github microagent that was recently released in the `openhands-ai` library conflict with the resolver workflow.

This PR to the `openhands-ai` library makes it possible to disable particular microagents: https://github.com/All-Hands-AI/OpenHands/pull/4932

It is not currently in the most recent released version of OpenHands, but once the version of OpenHands is bumped to 0.13.1, we should:

1. bump the import of openhands-ai to 0.13.1
2. disable the `github` microagent by default by changing the settings in `resolve_issue.py`
3. Run tests and linting to make sure everything works

---
*Moved from All-Hands-AI/openhands-resolver#331*

**Comment by malhotra5** [comment]
I believe this has been resolved!
