### ISSUE TITLE
[Resolver] Move all resolver settings to repo variables for reusable workflow?

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5041]
Since a custom macro has to be defined as a repo variable, it would make sense to refactor all other resolver settings to use repo variables as well instead of being hard coded inside the example workflow file. This way there is one central place for users to tweak their settings.

The only variable to refactor for now is `MAX_ITERATIONS`.

---
*Moved from All-Hands-AI/openhands-resolver#325*

**Comment by malhotra5** [comment]
I believe this is resolved!
