### ISSUE TITLE
[Resolver] Logs are insufficient on litellm API errors

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5045]
In the following GitHub action, something is going wrong with an API call, but the logs are not sufficient to debug the problem. We should make sure that logs are effectively printed. 

https://github.com/PierrunoYT/OpenHands/actions/runs/11652322360/job/32443373978

---
*Moved from All-Hands-AI/openhands-resolver#239*

**Comment by enyst** [comment]
I think this works now, for example we saw some proxy "not found" errors these days. I'll close this, but please reopen if it's not fixed.
