### ISSUE TITLE
[Resolver] allow the github-resolver github action to be triggered by comments on issues or PRs

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5046]
The workflow we provide here can be trigger with a github action like the one in examples/openhands-resolver.yml, where it responds to issues that have been tagged

Please modify our workflow so that it can also be triggered by comments on issues or PRs, but only if the comment contains `@openhands-agent` (the name must be configurable by the user of the Action)

This should pull in the original issue/PR text, as well as the new comment, as the text that's passed to the agent as a prompt. If the comment is on a PR, and the PR mentions an issue in the description, it should also pull in the text of the linked issue

---
*Moved from All-Hands-AI/openhands-resolver#232*

**Comment by malhotra5** [comment]
I believe this issue has been resolved
