### ISSUE TITLE
[Bug]: Can't connect to the hosted app, runtime error >24h

### ISSUE THREAD

**Issue by Belzedar94** [All-Hands-AI/OpenHands#5083]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I was testing the app 2 days ago when I faced an issue (#4857). Issue was solved yesterday with the new release, but I'm getting the attached error ever since, and it's been approximately 48h from the last time I used the app (Robert pointed out timeouts are deleted every 24h).

### OpenHands Installation

app.all-hands.dev

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

![IMG-20241115-WA0009](https://github.com/user-attachments/assets/8c94fad2-c405-49fe-8026-e640f8ff45b9)

**Comment by mamoodi** [comment]
Hi @Belzedar94. Are you hoping to recover your session with all the files? Or do you want to just use the app and it's stuck like that?

**Comment by Belzedar94** [comment]
> Hi @Belzedar94. Are you hoping to recover your session with all the files? Or do you want to just use the app and it's stuck like that?

Hey buddy! I was hoping to recover my session and files, but if there is no way and creating a new project fixes that, I'll do it!

**Comment by mamoodi** [comment]
I've asked the group but there is a high chance that you have to exit the project and restart....

**Comment by mamoodi** [comment]
Yes just confirmed you have to restart a project.. sorry about this. They are thinking about making it more forgiving in the future.

Make sure you download and save your work periodically. Or better yet push it to a branch via OpenHands :)

**Comment by Belzedar94** [comment]
![image (10)](https://github.com/user-attachments/assets/e93e056c-4b08-42e5-9065-a56b44669974)
It happened again today, but for a session that was 11h old. After getting the attached runtime error for hours, it suddenly stopped popping-up, but then the client got indefinitely stuck in "Waiting for client to become ready....". Refreshing didn't solve it

**Comment by mamoodi** [comment]
This should be much better now with the changes in 0.15.0. Will leave it open but please let us know if you run into it again < 24h.

**Comment by neubig** [comment]
Hi @Belzedar94 , if you're still encountering this please tell us. But I'll close this issue for now!
