### ISSUE TITLE
[Bug]: Unable to use the grok-beta model normally.

### ISSUE THREAD

**Issue by XiaoSong2017** [All-Hands-AI/OpenHands#5085]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

![image](https://github.com/user-attachments/assets/43fef249-88d3-43dd-9e50-f9a1422fba10)
After normally configuring the parameters for the grok-beta model in the tool, whether starting a new project or pulling an existing project, a message will appear in the log file: 
![image](https://github.com/user-attachments/assets/ae97f810-5012-483a-8e54-a0be44a4e8c7)
and it will take a long time without any result.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14

### Operating System

Linux

**Comment by mamoodi** [comment]
There was a bug regarding this model but it was fixed in 0.14. That log you outlined shouldn't be a fatal log. If you give it a simple prompt like "What version of python is installed?" and let it run for a couple of minutes, does anything happen?
