### ISSUE TITLE
[Bug]: wsl中启动容器了，还是打不开

### ISSUE THREAD

**Issue by wulala-star1** [All-Hands-AI/OpenHands#5088]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

![image](https://github.com/user-attachments/assets/84ad9c85-1338-4fcd-9d52-9432ab38f40d)
![image](https://github.com/user-attachments/assets/b29c5b67-b674-4075-9716-b92dac2aa59a)

### OpenHands Installation

Docker command in README

### Operating System

WSL on Windows

**Comment by mamoodi** [comment]
Can you ensure Docker Desktop WSL2 is enabled? https://docs.docker.com/desktop/features/wsl/#turn-on-docker-desktop-wsl-2

And then go to Settings > Resources > Network and make sure `Enable host networking` is also enabled?

And then retry?

**Comment by Paste-Fried-tofu** [comment]
Firstly, you should set the wsl networkingMode=mirrored, see that at: https://learn.microsoft.com/zh-cn/windows/wsl/networking.
Then, you may need to access the 127.0.0.1:3000, rather than the 0.0.0.0:3000
