### ISSUE TITLE
[Bug]: Fix for WSL2 issue sharing files between container and host machine.

### ISSUE THREAD

**Issue by NateUE** [All-Hands-AI/OpenHands#5128]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I'd like to recommend a slight change to the Connecting to your filesystem section of the setup docs.

The existing one looks like this. The first line with /path/to/your/code is a bit vague.
I believe this may be resulting in some issues people are having with WSL2 on Windows.
```
export WORKSPACE_BASE=/path/to/your/code

docker run # ...
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    # ...
```

I believe something like this would be easier to understand.
```
export WORKSPACE_BASE=/path/to/your/code
# Examples
#
# Linux and Mac
# export WORKSPACE_BASE=$HOME/OpenHands
# Will set $WORKSPACE_BASE to /home/'username'/OpenHands
#
# WSL2 on Windows
# export WORKSPACE_BASE=/mnt/c/dev/OpenHands
# Will set $WORKSPACE_BASE to C:\dev\OpenHands


docker run # ...
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    # ...
```

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14

### Operating System

WSL on Windows

**Comment by mamoodi** [comment]
Yeah this whole bit has been modified so many times. It's hard to get right. I do like your example usage though.
If you'd like to open a PR with the proposed changes, we can get some eyes on it.
