### ISSUE TITLE
[Resolver] Create a more informative failure comment

### ISSUE THREAD

**Issue by ryx2** [All-Hands-AI/OpenHands#5137]
**What problem or use case are you trying to solve?**

When the openhands GH actions resolver fails to make a good PR, it just says 

```An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-182' has been created with the attempted changes. You can view the branch here. Manual intervention may be required.```

**Describe the UX of the solution you'd like**

Can the resolver create a summary of what was attempted, and why it failed in the comment, instead of this standard message? Otherwise, it takes way more time to dig through the github actions run / branch diff to find the issue

**Do you have thoughts on the technical implementation?**

I notice that the debug log from the send_pull_request often has information about whether or not the code changes were successful, just using these as the comments would be good

**Describe alternatives you've considered**

**Additional context**

**Comment by malhotra5** [comment]
Fixed by #5685
