### ISSUE TITLE
[Resolver] Could we get a .md of tips for the .openhands_instructions file?

### ISSUE THREAD

**Issue by ryx2** [All-Hands-AI/OpenHands#5155]
**What problem or use case are you trying to solve?**

People who work on OpenHands probably have a really good idea of what makes a good .openhands_instructions file. I've definitely thought extensively about this as well. High quality .openhands_instructions are a MUST in order to go many iterations without getting led astray for the resolver.

**Describe the UX of the solution you'd like**

Create a openhands_instructions_tips.md somewhere (root dir?)

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by enyst** [comment]
Maybe we could add them in the docs around [here](https://docs.all-hands.dev/modules/usage/prompting-best-practices)?

**Comment by neubig** [comment]
Good point, I can take a stab at this.
