### ISSUE TITLE
docs: Improve GitHub token setup documentation in UI guide

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5162]
The current documentation about GitHub token setup in the GUI mode guide is minimal and could be improved to help users better understand the process.

Needed improvements:

1. Add step-by-step instructions for setting up a GitHub token locally:
   - How to access the token settings in the UI
   - Required token scopes and permissions
   - How to enter and save the token

2. Add information about organizational token policies:
   - Note that organizational repositories may require additional setup
   - Link to GitHub's documentation about setting organizational token policies https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization
   - Instructions for checking if token policies are blocking access

3. Add troubleshooting section:
   - Common issues with token setup
   - How to verify token is working correctly
   - What to do if token is not being recognized

4. Clarify OAuth flow for online mode:
   - Explain what permissions are requested
   - How to review and approve access
   - What to do if authentication fails

This will help users better understand how to set up GitHub integration in both local and online modes, and how to handle organizational requirements.

**Comment by malhotra5** [comment]
Fixed by #5162
