### ISSUE TITLE
[Bug]: `github.py` should not be named github, circular import issue

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#5168]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Try running: `python openhands/server/listen.py` and you will get this error
```
ERROR:root:  File "/home/ubuntu/openhands/openhands/server/listen.py", line 23, in <module>
    from openhands.server.github import (
  File "/home/ubuntu/openhands/openhands/server/github.py", line 3, in <module>
    from github import Github
  File "/home/ubuntu/openhands/openhands/server/github.py", line 3, in <module>
    from github import Github

ERROR:root:<class 'ImportError'>: cannot import name 'Github' from partially initialized module 'github' (most likely due to a circular import) (/home/ubuntu/openhands/openhands/server/github.py)
```
I fixed this by renaming `github.py` to `github_utils.py`

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
Hi there! Are you able to open a PR with your change and get some 👀 on it please? If you ran into it, it's likely others will too..

**Comment by diwu-sf** [comment]
Okay will do
