### ISSUE TITLE
[Bug]: No output after input text

### ISSUE THREAD

**Issue by NonvolatileMemory** [All-Hands-AI/OpenHands#5171]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

After I launch the docker as said in tutorial and set API with GUI (ollamao/deepseek and gpt), the output still empty and stuck.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
Can you give some more information on:
* What OS you are running?
* What you have set your provider and model to exactly?
