### ISSUE TITLE
[Bug]: [Hosted version] Refresh on hosted OpenHands takes a while to re-load state

### ISSUE THREAD

**Issue by morganmcg1** [All-Hands-AI/OpenHands#5176]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

After leaving my laptop/browser for a while I find I need to refresh OpenHands (hosted version). But when I refresh it takes quite a long time to load (like 3-5min). Initially I thought my work was lost. But then after coming back to the tab I saw it had loaded.

### OpenHands Installation

app.all-hands.dev

### Operating System

MacOS

**Comment by mamoodi** [comment]
@morganmcg1 are you still finding this to be the case? There's been some big changes around refreshes.

**Comment by neubig** [comment]
My guess is that this has been resolved, it seems to be very snappy now. But @morganmcg1 please tell us if you're still encountering this!
