### ISSUE TITLE
[frontend]: Push to Github button should only push branch, but not creating a PR

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5179]
**What problem or use case are you trying to solve?**

After clicking the "push to github" button, the frontend will automatically send a message asking the agent to push stuff to github AND create a PR.

<img width="361" alt="image" src="https://github.com/user-attachments/assets/a1414090-440b-4512-ac75-2c39a86a0d8d">

![image](https://github.com/user-attachments/assets/f15ead20-8bd0-495a-bfc6-36e10dc51443)

**Describe the UX of the solution you'd like**

We should have two separate buttons for the functionality of "push to remote branch", AND, "push & create a new PR" - so we don't accidentally create new PR when not intended.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by rbren** [comment]
I actually disagree with this--I generally want it to open the PR. But I think adding some customizability here would be good

**Comment by xingyaoww** [comment]
We could also do some sort of checkbox? But it might be tricky to place it near the button.. Let's ask OpenHands try to implement the two button approach and see how it'd go! @openhands-agent
