### ISSUE TITLE
[Resolver]: Check entire body for macro invocation

### ISSUE THREAD

**Issue by malhotra5** [All-Hands-AI/OpenHands#5184]
**What problem or use case are you trying to solve?**

Allow triggering the resolver if the macro trigger is present anywhere in the comment body.

Currently this would start resolver 

> `@openhands-agent` please fix this"

We also want to support such cases 

> "please fix this `@openhands-agent`"

**Describe the UX of the solution you'd like**
N/A
**Do you have thoughts on the technical implementation?**
Edit `.github/workflows/openhands-resolver.yml` and `openhands/resolver/examples/openhands-resolver.yml`; replace the startsWith command with an alternative that checks across the entire comment body

**Describe alternatives you've considered**

**Additional context**

**Comment by enyst** [comment]
This is solved, right? Please feel free to reopen if you think it's not!
