### ISSUE TITLE
[Bug]: [Resolver] Multi-line GitHub comments break the macro

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#5230]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

It appears that the `@openhands-agent` tagging doesn't always work, the bash conditions are unhappy when the GitHub comment is multiline with random complex stuff in it.
Example: https://github.com/All-Hands-AI/OpenHands/actions/runs/11989779372/job/33426535798#step:9:2

Maybe we can restructure it into a variable first?

### OpenHands Installation

Other

### Operating System

None

**Comment by enyst** [comment]
The run above was due to this comment: https://github.com/All-Hands-AI/OpenHands/pull/5223#issuecomment-2495627037

**Comment by malhotra5** [comment]
Resolved by #5641!
