### ISSUE TITLE
[Bug]: resolver example should use "max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || 50) }}"

### ISSUE THREAD

**Issue by d-walsh** [All-Hands-AI/OpenHands#5263]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

There is a bug where the the current code evaluates as a string and results in this:
```
OpenHands Resolver
The template is not valid. .github/workflows/openhands-resolver.yml (Line: 26, Col: 23): Unexpected value '100'
```
@openhands-agent

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by malhotra5** [comment]
Resolved by #5349; thanks for the catch @d-walsh!
