### ISSUE TITLE
[Bug]: "Error fetching /config.json" error

### ISSUE THREAD

**Issue by insop** [All-Hands-AI/OpenHands#5273]
### Is there an existing issue for the same bug?

- [x] I have checked the existing issues.

### Describe the bug and reproduction steps

Followed a quick start guide to start dockers [link](https://docs.all-hands.dev/modules/usage/installation).

At the very first time, added model API key when prompted.
Then typed in github token, this token might have an error due to extra charactor.

1.  After the above steps, I am seeing this error.

![Image](https://github.com/user-attachments/assets/3bee0faf-871c-4485-b575-6eb2648c3473)

2. re-start the docker still shows the same error

3. re-install docker images still shows the same error

It is as if there is a cached config file that has an erroneous config, and I am not able to locate the the config file nor get back to the step 1.

Thank you.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

```
Error fetching /config.json

Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non IS0-8859-
```

**Comment by mamoodi** [comment]
@insop if you press `Ctrl + Shift + R` or `Cmd + Shift + R`, does it work after you re-run the docker command?
Or if you open an incognito window?

**Comment by insop** [comment]
Thank you @mamoodi, Cmd + Shift + R did not work, but incognito mode works.
So somewhere in the browser cache is corrupted and forbid the app started correctly.

This certainly is a workaround! thank you.
However, it certainly will be a nice to have a way to not to get into the failure mode :)

Feel free to change the state of the issue or update the issue for your tracking if you like.

Thank you,

**Comment by insop** [comment]
Per the suggestion above, updated the browser's localstorage's `ghToken` and it solved it.
