### ISSUE TITLE
[Bug]: The resolver label doesn't work on branches started from a fork

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#5292]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

At least I think that's what happens, for example here:

https://github.com/All-Hands-AI/OpenHands/actions/runs/12041355151/job/33573059053?pr=5178#step:6:1

Started from: https://github.com/All-Hands-AI/OpenHands/pull/5178#issuecomment-2502333342

I think it failed on that issue because it's a branch started from a fork... It just doesn't recognize the first repo secret (LLM_MODEL). @mamoodi what do you think, I seem to recall you've seen something like this recently? 

### OpenHands Installation

Other

### Operating System

None

**Comment by malhotra5** [comment]
Hey @enyst! This is an issue that we hope to resolve by addressing #5050 😀

**Comment by enyst** [comment]
Ah okay, thank you!

**Comment by mamoodi** [comment]
Yeah forks don't have access to secrets for the organization. Same problem with running eval on PRs.

**Comment by enyst** [comment]
Seems like this is a duplicate of https://github.com/All-Hands-AI/OpenHands/issues/5044
