### ISSUE TITLE
[Bug]: User must select the text of the filename for it to get selected in the workspace

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#5299]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

In the OpenHands UI workspace, the user must select the text of the filename for it to be selected.

Instead by clicking the row, the file should be selected.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14.3

### Operating System

None

**Comment by Rushikeshmagdum0379** [comment]
Can I know till where the progress was stopped or unsuccessfull .

**Comment by Rushikeshmagdum0379** [comment]
Can we connect on WhatsApp or telegram
