### ISSUE TITLE
How do I setup an environment for openhands resolver?

### ISSUE THREAD

**Issue by zachmayer** [All-Hands-AI/OpenHands#5331]
**What problem or use case are you trying to solve?**
I'm trying to use openhands with R.  Claude can program in R just fine, but it burns a boatload of tokens trying to install the R packages needed for my repo.  I already know how to do this, so I want to setup an R environment manually and install all the needed packages before running openhands.

However, the openhands resolver seems to be a reusable workflow, so I can't add steps before it to setup the environment it runs in.

**Describe the UX of the solution you'd like**
Some way to run some steps before the openhands resolver, in order to configure the environment for maximum success.

**Do you have thoughts on the technical implementation?**
no, github actions confuses the hell out of me

**Describe alternatives you've considered**
yelling at my laptop

**Additional context**
I tried adding some steps but got reusable workflows should be referenced at the top-level `jobs.*.uses' key, not within steps

**Comment by mamoodi** [comment]
Hmmm @malhotra5 is there a way to achieve this with the current functionality?

**Comment by malhotra5** [comment]
@zachmayer makes a good point! We can't support the package installations directly from the Github workflow. 

We have the following solution for this, but requires some work from the user: 
1. Setup a [custom sandbox](https://docs.all-hands.dev/modules/usage/how-to/custom-sandbox-guide), which will contain the appropriate packages.
2. Pass `sandbox_base_container_image="custom-image"` parameter through the Github workflow, which will load in the custom sandbox.

**Comment by malhotra5** [comment]
Fixed by #5348.
