### ISSUE TITLE
[Bug]: In the UI chat box, the history keeps repeating/accumulating

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#5358]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I had a conversation in the browser on app.all-hands.dev. In the next 24 hours, I kept coming back to it and doing nothing, then leaving the tab and coming back again.

Every time it restarted the runtime, it was also re-adding ALL history in duplicate, triplicate etc. in the chat box. 😅

I guess the behavior related to `latest_event_id` isn't working quite right?

Cc: @tofarr 

### OpenHands Installation

app.all-hands.dev

### Operating System

None

**Comment by enyst** [comment]
@tofarr FWIW I notice that
- the whole history kept duplicating while the tab remained open; it went up to 4x or 5x all messages
- once I closed the tab, then reopened it, the history loaded is back to 1x. (whew, so it's about displaying in the chat only 😅)

**Comment by tofarr** [comment]
Confirmed. Can duplicate this by manually disconnecting the websocket. Fix incoming.

**Comment by enyst** [comment]
This should be fixed by the linked issue.
