### ISSUE TITLE
[Bug]: Sign in to GitHub modal fails to login with correct credentials after trying incorrect ones

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#5361]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Press sign in with GitHub
2. Enter incorrect credentials -> modal reopens with error message
3. Enter correct credentials -> modal closes without signing in

### OpenHands Installation

Docker command in README

### OpenHands Version

0.14.3

### Operating System

None

**Comment by mamoodi** [comment]
This doesn't seem to be the case anymore. Locally if you type incorrect token, the modal closes and an error gets thrown. Upon clicking `Connect to Github` again, and giving correct token it connects.

We've also changed the SaaS as well so that doesn't even get used and it's automatic. Closing.
