### ISSUE TITLE
[Bug]: When Performing browser operations, output messages are repeated

### ISSUE THREAD

**Issue by tofarr** [All-Hands-AI/OpenHands#5423]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Start a new session and enter the prompt: `What is the area in square miles of the state of California?`
The response `Let me search for this information.` is repeated twice before the actual answer is received.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.15.0

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

<img width="432" alt="image" src="https://github.com/user-attachments/assets/4ecfe5ea-bdbe-4e2c-83e9-9ef792e47461">

Both of the responses have the source of `agent` and have the same `thought` - I think the first one is initiating the search and the second one is readying the resulting page.

**Comment by xingyaoww** [comment]
@openhands-agent Can you try to figure out and fix this issue

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12258866475).

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12258864306).

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Openhands failed to create any code changes.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12258864306).

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5423' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5423). Manual intervention may be required.

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5423' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5423). Manual intervention may be required.

**Comment by xingyaoww** [comment]
Fixed in #5511
