### ISSUE TITLE
[Bug]: Scrollbar for the file goes out of screen

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#5439]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Not sure if this is because the file is really large but the scroll goes beyond what's the displayed on the screen.

![Screenshot 2024-12-06 at 12 31 59 PM](https://github.com/user-attachments/assets/bcba1770-1689-456d-b082-b7f96b1fea13)

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by mamoodi** [comment]
The inner scroll can't be seen because it's passed the screen. I'm not talking about the outer scroll.

**Comment by mamoodi** [comment]
Oh wait :D 
I can obviously scroll the outer one down and then see the other scroll....why is there a double scroll here?

**Comment by enyst** [comment]
Related to https://github.com/All-Hands-AI/OpenHands/issues/5391

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12242937436).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5481 has been created. Please review the changes.

**Comment by amanape** [comment]
I believe this issue was fixed in #5488
