### ISSUE TITLE
[Bug]: Assigning label on PR doesn't kickstart resolver

### ISSUE THREAD

**Issue by malhotra5** [All-Hands-AI/OpenHands#5445]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Tried adding `fix-me`/`fix-me-experimental` label to #5342 but it didn't kickstart the resolver

### OpenHands Installation

Other

### OpenHands Version

latest,main

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12210475001).

**Comment by enyst** [comment]
😅 There we go!

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5446 has been created. Please review the changes.

**Comment by enyst** [comment]
That won't work. Possible cause?
- https://github.com/All-Hands-AI/OpenHands/pull/5278

**Comment by enyst** [comment]
It may have been just a github fluke. I think it just works now?

**Comment by mamoodi** [comment]
With the amount resolver is being used these days I think this would be pretty high up on issues lol. So I think we can close this?

**Comment by enyst** [comment]
Yes, I really think it was a github fluke. The action wasn't starting at all. Please feel free to re-open if you think.
