### ISSUE TITLE
[Bug]: [Resolver] PR (without a label?) fails workflow

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#5465]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I asked openhands-agent to do something, using the macro.
https://github.com/All-Hands-AI/OpenHands/pull/5435#issuecomment-2525041512

Action log:

> Run if [[ "" == "fix-me-experimental" ]] ||
  if [[ "" == "fix-me-experimental" ]] ||
     ([[ "issue_comment" == "issue_comment" || "issue_comment" == "pull_request_review_comment" ]] &&
      [[ "Run log:
  > AgentFinishAction(outputs={}, thought="After analyzing all the relevant code, I can see that:\n\n1. The `summarize_actions` method should be moved from ...

which fails because of the empty "".

### OpenHands Installation

Other

### OpenHands Version

0.15.1

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12242909741).

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Openhands failed to create any code changes.

**Comment by enyst** [comment]
Closing in favor of https://github.com/All-Hands-AI/OpenHands/issues/5621
