### ISSUE TITLE
Add color to the line next to "Ran a XXX Command" based on return value

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5478]
**What problem or use case are you trying to solve?**

In the interface, we have "Ran a Bash Command" or "Ran a Jupyter Command" with a line next to it.

<img width="416" alt="Screenshot 2024-12-09 at 2 30 39 PM" src="https://github.com/user-attachments/assets/87aa4a2e-6984-4f26-8c94-5140b8049260">

It would be nice to know if the command was successful or not.

**Describe the UX of the solution you'd like**

We could change the color of the line depending on the return value. If the command terminates successfully, we can make the line green, otherwise we can make it red.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12242914795).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5483 has been created. Please review the changes.
