### ISSUE TITLE
[Bug]: Cannot recover from "Agent stuck in loop"

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5480]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Once we stuck in "agent stuck in loop", we cannot send subsequent messages to the agent anymore.

<img width="484" alt="image" src="https://github.com/user-attachments/assets/fe5edfea-f3fb-4453-8f36-093c39af993b">

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by xingyaoww** [comment]
@openhands-agent any idea?

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12243048632).

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5480' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5480). Manual intervention may be required.

**Comment by enyst** [comment]
This proposal is rather tough: https://github.com/All-Hands-AI/OpenHands/compare/main...openhands-fix-issue-5480#diff-1e082f415afb40de1d5c2a3fa327326225e1da28a142ad89c9524109f35fb36eR197

@openhands-agent Can you look at how traffic control is implemented, paused in the UI when necessary, and restarting later when the user does something? That can serve as example for this issue.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12249207814).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5500 has been created. Please review the changes.

**Comment by avi12** [comment]
I also faced this issue
![image](https://github.com/user-attachments/assets/ae28a54e-e587-4be5-9511-57e07b61f333)

**Comment by enyst** [comment]
@avi12 It's fixed on `main`, please if you can, run `openhands` with `:main` instead of `:0.15`, or there will be a new release within days.

**Comment by avi12** [comment]
I'd appreciate it if you could update the [documentation](https://docs.all-hands.dev/modules/usage/installation) accordingly

**Comment by enyst** [comment]
Sorry, I should clarify, the `main` branch is the development branch. We generally recommend to run actual releases, not the development branch. When there will be a new release - within days - we may update the documentation with that new version.

It's up to you, though, if you want to get the fix earlier: you can run `openhands` from `main`. But if you don't want the risk - there is a risk other things are bugged - then please don't. I'm sure it will be released soon, and releases are tested for major functionalities working ok.

**Comment by avi12** [comment]
Thank you for the information, it's worth mentioning both `main` and the latest version in the documentation so that the user can decide for himself

**Comment by avi12** [comment]
@enyst I'm on the main branch
![image](https://github.com/user-attachments/assets/d261572e-e367-403e-a7d2-7c275e0d9a87)

**Comment by enyst** [comment]
Was the Pause/Stop button available? I'm trying to reproduce the issue.

**Comment by avi12** [comment]
As far as I can tell, whenever the agent is oscillating between two prompts and can't get to a different prompt, at some point it will tell me that the agent got stuck in a loop, which makes sense 
And then it will pause automatically so that I can send a prompt

**Comment by enyst** [comment]
Right! But when you send a message, actually typed words and send to the agent, did it restart its actions?

**Comment by avi12** [comment]
Yep, only to get stuck again
![image](https://github.com/user-attachments/assets/4f64cbc3-bdf2-4634-b8b0-97617c004b83)

**Comment by enyst** [comment]
Ah, if I see this right... it did several more steps, and got stuck later again.

What model are you using?

**Comment by CitroenGames** [comment]
![image](https://github.com/user-attachments/assets/344bb1fb-42b2-48d2-b619-d46f7c611bda)
![image](https://github.com/user-attachments/assets/f2643762-d37c-4811-999f-c5d320d62c12)

**Comment by enyst** [comment]
@CitroenGames There is another issue for that, please see here, and feel free to add your experience:
https://github.com/All-Hands-AI/OpenHands/issues/5637

I would still love to hear what model / provider are you using, when you are getting a lot of stuck cases. It does matter! The model decides what steps to perform.

**Comment by avi12** [comment]
> Ah, if I see this right... it did several more steps, and got stuck later again.
> 
> What model are you using?

https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct-GGUF running via https://lmstudio.ai

**Comment by BradKML** [comment]
I have also encountered this issue as well and could you try Phi-3/Phi-4 or DeepSeek Coder @avi12 I would like to see if this is an isolated problem

**Comment by avi12** [comment]
@BradKML Funny enough, when used https://huggingface.co/matteogeniaccio/phi-4 I encountered https://github.com/All-Hands-AI/OpenHands/issues/4586#issuecomment-2550263141

**Comment by avi12** [comment]
After trying out https://huggingface.co/lmstudio-community/Yi-Coder-9B-Chat-GGUF, I reproduced the error https://www.all-hands.dev/share?share_id=3a4846c320bba583aa836da5dcafe53712c08a42d8020f345edeaeab8b7c623f

**Comment by kasinadhsarma** [comment]
![image](https://github.com/user-attachments/assets/b3a3f60d-1ebc-4eeb-8c26-564e44edb0c1)
same got agent stuck loop again

**Comment by avi12** [comment]
@kasinadhsarma I think it partially has to do with the LLM that you choose, try the one that OH recommends, Claude 3.5 Sonnet

**Comment by BradKML** [comment]
@avi12 could it work with the OpenRouter version of Sonnet, or official only?

**Comment by avi12** [comment]
> @avi12 could it work with the OpenRouter version of Sonnet, or official only?

IDK, I haven't gone that far

**Comment by avi12** [comment]
> @avi12 could it work with the OpenRouter version of Sonnet, or official only?

IDK, I haven't gone that far
