### ISSUE TITLE
[Bug]: Refresh window kill all the history

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5490]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

In the latest release, it seems the agent lose all of the history after a page refresh

<img width="436" alt="image" src="https://github.com/user-attachments/assets/9112efd9-1348-47cd-b8dd-ea11e0d0f98b">

### OpenHands Installation

Hosted site

### Operating System

None

**Comment by mamoodi** [comment]
I've upped this up to critical. We should take a look ASAP if this is the case.

**Comment by enyst** [comment]
Was this on local or on the hosted site?

I tried to repro locally on `main`: close the tab, reopen it, it works. Will try restarting too.
<img width="385" alt="image" src="https://github.com/user-attachments/assets/a1059e86-da10-4c47-8f41-f37683c0e643">

**Comment by mamoodi** [comment]
It's on hosted but it may have been partially resolved.

**Comment by enyst** [comment]
Ouch, it seems I still can repro on the hosted version indeed. 
<img width="383" alt="image" src="https://github.com/user-attachments/assets/cdd0fe2b-8bfb-4903-ad36-de2ec5dadc68" />

**Comment by mamoodi** [comment]
Yes @enyst this should be fixed with the release.

**Comment by mamoodi** [comment]
Should be good now with 0.15.2
