### ISSUE TITLE
[Bug]: Regression on Anthropic due to empty content hack for Bedrock

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#5492]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

This fix https://github.com/All-Hands-AI/OpenHands/pull/4935 to special case empty content string for Bedrock is causing regression with Anthropic tool call that has empty output.

This is the bug:
```
message.py#_list_serializer
        # pop content if it's empty
        if not content or (
            len(content) == 1
            and content[0]['type'] == 'text'
            and content[0]['text'] == ''
        ):
            message_dict.pop('content')
```

What happens is if there's a tool for Anthropic, and the tool response empty string, the `content` will be stripped from the message request and eventually litellm hits a key error not found issue. Error is from https://github.com/BerriAI/litellm/blob/main/litellm/llms/prompt_templates/factory.py#L1166-L1199

Stack in Litellm is:
```
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 516, in _transform_request
    anthropic_messages = anthropic_messages_pt(
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/prompt_templates/factory.py", line 1457, in anthropic_messages_pt
    convert_to_anthropic_tool_result(user_message_types_block)
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/prompt_templates/factory.py", line 1166, in convert_to_anthropic_tool_result
    if isinstance(message["content"], str):
                  ~~~~~~~^^^^^^^^^^^
KeyError: 'content'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1774, in completion
    response = anthropic_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/handler.py", line 347, in completion
    data = AnthropicConfig()._transform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 522, in _transform_request
    raise AnthropicError(
litellm.llms.anthropic.common_utils.AnthropicError: 'content'
Received Messages=...
```

Example of the tool response message that end up causing this missing `content` key error:
```
   {
      "role":"tool",
      "cache_control":{
         "type":"ephemeral"
      },
      "tool_call_id":"toolu_01RxAcyKvZAHVKPQrih36y3X",
      "name":"workspace_change_summary"
   }
```

I think it's better to only apply the `pop('content')` bedrock fix if the LLM config is bedrock, otherwise, it seems like a bad idea to remove an empty content.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12249143169).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5498 has been created. Please review the changes.

**Comment by xingyaoww** [comment]
🤔 it starts to make me feel whether we should revert https://github.com/All-Hands-AI/OpenHands/pull/4935 AND handle this empty message issue for bedrock on litellm repo.

**Comment by enyst** [comment]
We could. A [temporary fix](https://github.com/All-Hands-AI/OpenHands/pull/5498) for us is almost ready, but it's temporary because this is a litellm issue. I'll see what openhands-agent can do on the litellm repo. 😅

**Comment by diwu-sf** [comment]
I think these LLM provider specific quirks are better handled inside LiteLLM, vs inside the application logic that uses LiteLLM.

The whole point of LiteLLM is to normalize the edge cases across providers, so it's a bug in their code.
