### ISSUE TITLE
[Bug]: Regression, clicking into Jupyter tab, then clicking back into Workspace tab opens up VSCode

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#5519]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Repro steps:
1. Ask the agent to `DO NOTHING`
2. Wait until the workspace is fully ready and the Open in VSCode button is blue
3. Click open the VSCode **once**, and close the vscode tab
4. Click into the Jupyter tab
5. Click back into the Workspace tab, upon clicking the workspace tab, VSCode pops open again!

I think this is a problem with `use-vscode-url.ts`
Regression is from https://github.com/All-Hands-AI/OpenHands/pull/5287 and in the old code, there was event prevent default

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
Ah we had gotten this a few times. Thanks for opening up the issue and mentioning how to reproduce!

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12285510074).

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12285510074) for more information.
