### ISSUE TITLE
Customization of repos within the OpenHands app should be documented

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5527]
**What problem or use case are you trying to solve?**

It is not obvious how to customize openhands to work well with new repos.

**Describe the UX of the solution you'd like**

The functionality for customization of prompts to specific repositories introduced in this PR should be documented in our documentation directory: https://github.com/All-Hands-AI/OpenHands/pull/4983

**Do you have thoughts on the technical implementation?**

I would suggest changing the current
```
* Prompting Best Practices
```

page to be hierarchical
```
* Prompting Best Practices
  * Characteristics of Good Prompts
  * Customizing Prompts for your Project
```

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12281122139).

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12281122139) for more information.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12281629290).

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5527' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5527). Manual intervention may be required.
