### ISSUE TITLE
[Bug]: fatal: not in a git directory (when using Dev Container)

### ISSUE THREAD

**Issue by kripper** [All-Hands-AI/OpenHands#5529]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I started the OpenHands using the `devcontainer.json` file in VSCode.
The container was created, but during `make build` (postCreateCommand) I got this error.

### OpenHands Installation

Development workflow

### Operating System

WSL on Windows

### Logs, Errors, Screenshots, and Additional Context

```
Frontend dependencies installed successfully.
Installing pre-commit hooks...
fatal: not in a git directory
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /home/codespace/.cache/pre-commit/pre-commit.log
make[1]: *** [Makefile:164: install-pre-commit-hooks] Error 1
make: *** [Makefile:28: build] Error 2
```

**Comment by mamoodi** [comment]
Hi there. Can you try the official development guide please? https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md

That devcontainer.json is not officially supported so. There is a task to remove it.

**Comment by kripper** [comment]
I had to follow the instructions for the Dev Container option to have a WSL environment where I could execute "make build" (I checked that the Dev Container also runs "make build").
To solve, I commented out the `install-pre-commit-hooks` rule in the Makefile, because it fails in the Dev Container environment:

```
install-pre-commit-hooks:
	@echo "install-pre-commit-hooks is DISABLED"
#	@echo "$(YELLOW)Installing pre-commit hooks...$(RESET)"
#	@git config --unset-all core.hooksPath || true
#	@poetry run pre-commit install --config $(PRE_COMMIT_CONFIG_PATH)
#	@echo "$(GREEN)Pre-commit hooks installed successfully.$(RESET)"
```

**Comment by mamoodi** [comment]
Closing as the devcontainer.json was removed and a warning was added to dev/containers workflow that it is not officially supported.

**Comment by kripper** [comment]
But it's working fine

**Comment by BradKML** [comment]
Having issues with WSL, how did you resolve it @kripper ?

**Comment by kripper** [comment]
The other problem of using the devcontainer approach is that OH is installing hooks into the .git folder (required by the sandbox), and they cause problems when you want to do a commit on the OH repo (outside the sandbox).

I'm currently disabling/enabling this hooks, which is not optimal either.
