### ISSUE TITLE
The turn limit should be measured from the last user interaction

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5559]
**What problem or use case are you trying to solve?**

OpenHands has a limit on the number of turns the agent can perform before it gets stopped (100 by default), but in long conversations it is frequent to hit this limit.

**Describe the UX of the solution you'd like**

We should change this limit to be extended (e.g. by 100) every time the user posts a new user message.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12300523035).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5560 has been created. Please review the changes.
