### ISSUE TITLE
[Bug]: Prompt is not deleted when the user sends a message

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5563]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

https://github.com/All-Hands-AI/OpenHands/pull/5342 seems to have introduced a regression. Now the prompt is not cleared when the user submits a message consisting of only text.

The prompt should be cleared every time the user submits a message to the agent, whether the message includes an image or not.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5564 has been created. Please review the changes.
