### ISSUE TITLE
[Bug]: Unable to Set DelegatorAgent as Default Agent

### ISSUE THREAD

**Issue by naswir** [All-Hands-AI/OpenHands#5593]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I am trying to modify the agent pipeline for my project and intend to use a custom agent (not micro agent) as the starting point. Before implementing a custom agent, I wanted to see how to use agents other than CodeActAgent. So, I am trying to use DelegatorAgent. However, I have been stuck for the last week as I am unable to enable DelegatorAgent as my default agent. No matter what I do, CodeActAgent is always triggered.

Here are a list of my failed attempts to set DelegatorAgent as the default one:

1. **Building the backend locally (without using docker for backend):**

Modified the config.toml file from the OpenHands root directory as follows:
```

[core]
workspace_base="/path/to/workspace"
default_agent = "DelegatorAgent"

[llm]
model="claude-3-5-sonnet-20241022"
api_key="myapikey"
embedding_model=""
```

Result: CodeActAgent was triggered when prompted through UI instead of DelegatorAgent.

2.**Using OpenHands Docker version for backend:**
Was unable to locate the config file to be modified.
Below are few details of my attempts:

1. Pruned all existing Docker containers, images, volumes, and cache using the command:
`docker system prune -a --volumes`

2. Built openhands docker image and containers (following ReadMe file)
3. Logged-in into openhands-app docker container and searched for config.toml. But failed to find it.

Observation:
Although I created a new docker image and container. I noticed my API keys were still autofilled in the browser OpenHands UI. I am unable to figure out where this data comes from. I suspect if I can find the source, then I can modify the same source file to set the default agent to DelegatorAgent.

Any guidance on how to set DelegatorAgent as the default agent would be greatly appreciated.

### OpenHands Installation

Both docker and local dev

### OpenHands Version

0.15

### Operating System

MacOS

**Comment by naswir** [comment]
Running the repository locally and running poetry run python -m openhands.core.cli reads the config file. Although webinterface user CodeActAgent. Closing the issue for now as it works

**Comment by enyst** [comment]
@naswir With the UI, can you open the Settings window and try to set the agent from there? It's true it doesn't read the DefaultAgent from toml when UI is active, it instead reads its own settings window value.

**Comment by enyst** [comment]
> Observation: Although I created a new docker image and container. I noticed my API keys were still autofilled in the browser OpenHands UI. I am unable to figure out where this data comes from. I suspect if I can find the source, then I can modify the same source file to set the default agent to DelegatorAgent.

They're saved by the UI in the browser local storage once you entered them in the Settings window, so autofilled after. The way to reset it is to change it in the Settings window (wheel icon on top left).

This can be confusing, but mainly the way it works now is: if a setting, like model, is available via UI Settings to customize, then that value overrides any other config file/env/etc.
