### ISSUE TITLE
[Bug]: UI regression, Jupyter tab has no vertical scroll bar, cannot see all actions

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#5605]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

This is regression from https://github.com/All-Hands-AI/OpenHands/pull/5488

The change to disable scrolling on container fixed the double scrollbar issue on the workspace tab, **but it also caused the only scroll bar on the jupyter shell tab to disappear**

Repro:
- Ask the agent to do something that involved running multiple Jupyter commands
- look on the jupyter tab, won't be able to scroll to see all actions

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by neubig** [comment]
I can confirm that this is the case.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12336324338).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5607 has been created. Please review the changes.
