### ISSUE TITLE
[Bug]: Remounting of vscode button before the container session is started causes internal error HTTP 500 to /api/vscode-url

### ISSUE THREAD

**Issue by diwu-sf** [All-Hands-AI/OpenHands#5606]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The VSCode button should be disabled before the workspace is fully initialized and ready.
However, it will pre-maturely send request to `/api/vscode-url` if you switch tab to Jupyter then back to Workspace

Repro:
1. Ask the agent to 'do nothing' to trigger a workspace
2. Immediately switch to the Jupyter tab
3. Switch back to the Workspace tab, see network API call to backend `/api/vscode-url` that causes `500 internal server error` due to container not ready yet

```
INFO:     127.0.0.1:48382 - "GET /api/vscode-url HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
```

This is might be related to https://github.com/All-Hands-AI/OpenHands/pull/5544

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by mamoodi** [comment]
Seen a couple of issues where interacting with OpenHands before things are initialized is causing issues. Might be worth it to just not allow interacting with anything until it's fully initalized.

**Comment by diwu-sf** [comment]
I agree, until the container is **past** the ready state, we shouldn't let any of the APIs hit against the runtime
