### ISSUE TITLE
Use litellm's modify_params with default True

### ISSUE THREAD

**Issue by enyst** [All-Hands-AI/OpenHands#5609]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Litellm has a parameter that the client code can set, `litellm.modify_params`. It works like `drop_params` which we are using and have set as True by default.

The idea is that litellm applies a number of transformations on the completion request, to make it compatible with the provider it needs to sent it to. But there are some transformations it doesn't make, unless the user sets modify_params.

For example, for Bedrock it transforms the messages to have the pattern user/assistant/user/assistant, by merging consecutive roles content: [code](https://github.com/BerriAI/litellm/blob/fd583e715ec1b183cade08ac29c1cbe73e5c94f6/litellm/litellm_core_utils/prompt_templates/factory.py#L2696)

However, another transformation is to insert a default message when the message was empty, but it's only doing this one if litellm.modify_params is True or the user sends their own default message:
[code](https://github.com/BerriAI/litellm/blob/fd583e715ec1b183cade08ac29c1cbe73e5c94f6/litellm/litellm_core_utils/prompt_templates/common_utils.py#L22)

Or insert an initial user message for anthropic [code](https://github.com/BerriAI/litellm/blob/fd583e715ec1b183cade08ac29c1cbe73e5c94f6/litellm/litellm_core_utils/prompt_templates/factory.py#L1539)

I think we should do with modify_params like we did with drop_params: set it to True by default and let our users configure it from us too (add it to config).

Please note though, that this one seems a little more complicated: our trajectories will not _exactly_ match what was sent to the LLM, and not just in some metadata like drop_params (e.g. drop top_p if the LLM doesn't support setting it and it would error), but the messages themselves. That may pose a question for reproducibility / accurate reporting of benchmarked trajectories? We should probably set it to False for evals.

### OpenHands Installation

Development workflow

### Operating System

None

**Comment by xingyaoww** [comment]
I agree on this. For eval, i think it should be relatively easy to do, we just hardcode `llm_config.modify_params` in `run_infer.py` files inside `evaluation/benchmarks/`

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12340431020).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5611 has been created. Please review the changes.
