### ISSUE TITLE
[Bug]: Github Resolver outputs "The workflow to fix this issue encountered an error." despite the "Overview of Changes" has been successfully commented

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5612]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

OpenHands Github resolver output "The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12340516087) for more information."

Despite the "Overview of Changes" has been successfully commented: https://github.com/All-Hands-AI/OpenHands/pull/5611#issuecomment-2543945072

This is a little confusing to the user.

### OpenHands Installation

Other

### Operating System

None

**Comment by xingyaoww** [comment]
@openhands-agent Can you investigate?

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12340630889).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5613 has been created. Please review the changes.

**Comment by malhotra5** [comment]
Closing issue, fixed by #5628
