### ISSUE TITLE
[Bug]: Decimal points in maximum iteration messages not needed

### ISSUE THREAD

**Issue by morganmcg1** [All-Hands-AI/OpenHands#5633]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The decimal points in maximum iteration messages not probably not needed.

Example with unnecessary decimal points:
```
Agent reached maximum iteration. Current iteration: 201.00, max iteration: 200.00.
```

### OpenHands Installation

app.all-hands.dev

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

Example of the chat here:

<img width="347" alt="Screenshot 2024-12-16 at 15 03 27" src="https://github.com/user-attachments/assets/49b0041c-f2f1-49e7-994f-01ee1a657218" />

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12361290747).
