### ISSUE TITLE
[Bug]: Terminal double types in the UI

### ISSUE THREAD

**Issue by mamoodi** [All-Hands-AI/OpenHands#5648]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When typing in the terminal, it double types the characters. Refreshing does not make it work.

https://github.com/user-attachments/assets/c84f6a28-27c3-4d73-8c3b-83a18feae378

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by enyst** [comment]
Two times? I see the two and I raise... seven? 😅 😹 

https://github.com/user-attachments/assets/c38ca90a-7467-414c-935c-c914aa0d3d70

Please feel free to ignore if this is, umm, unicorns on my machine.

**Comment by mamoodi** [comment]
Ooff. Some flow probably adds a character every time so you did it 6 times haha
