### ISSUE TITLE
[Bug]: Frontend Hyperlink in Chat window should open link in a new tab

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5676]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Currently, all hyperlinks in OpenHands Chat Window open in the current page when clicked. This isn't always what we want because, for example, if the AI recommends a URL or I accidentally click on a URL it's browsing, I get taken away from the AI workspace, interrupting my workflow. It would be better if there was a popup that opened links in a new tab.

### OpenHands Installation

app.all-hands.dev

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12400214924).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5677 has been created. Please review the changes.
