### ISSUE TITLE
[Bug]: Repo picker does not show all org repos

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5683]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The "Open Github Repo" repo picker does not show all repos in an organization, it seems to only show the first 30 in alphabetical order. This seems to be a problem with pagination.

We should write tests to confirm the issue and fix it.

### OpenHands Installation

app.all-hands.dev

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12402739635).

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5683' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5683). Manual intervention may be required.

**Comment by malhotra5** [comment]
Took a quick look at the current draft PR, I think it's a little off in resolving this issue

I think it may be something to do with [`extractNextPageFromLink`](https://github.com/All-Hands-AI/OpenHands/blob/main/frontend/src/utils/extract-next-page-from-link.ts), as the next page parameter might be returned in a different format from the backend

I'll investigate this further

**Comment by neubig** [comment]
Cool, thanks!

**Comment by malhotra5** [comment]
Adding critical severity as pagination is not working. All users can only see first page of repos when paginating

**Comment by mamoodi** [comment]
Fixed in main. Waiting for release.

**Comment by mamoodi** [comment]
Fixed now in 0.16.1. @neubig can you triple check this please.
