### ISSUE TITLE
[Bug]: SWE-Bench Lite Docker not found

### ISSUE THREAD

**Issue by yanismiraoui** [All-Hands-AI/OpenHands#5692]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Running the SWE-Bench Lite by following all the steps in the Markdown files. First 2 docker instances worked correctly the first time I ran the evaluation but nothing worked anymore after that. It seems like some docker instances do not exist anymore? It then retries 5 times to retrieve the docker but unsuccessfully... Is it possible to check that there are still all available? Thanks in advance!

Error message: 
`docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.47/containers/openhands-runtime-be7c2750-2b8c-48c6-b01a-fa1f18585321-17ec15d55c9a19fc/json: Not Found ("No such container: openhands-runtime-be7c2750-2b8c-48c6-b01a-fa1f18585321-17ec15d55c9a19fc")

15:35:54 - openhands:ERROR: shared.py:347 - Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.16.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-12-19T15:35:54.729360', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.16.0_o7lremih9uuceaof_swd7fszj4bcb8oyo', '--load', '--platform=linux/amd64', '/var/folders/rl/d4jq2g217cv1hy_ssxxj4k0r0000gn/T/tmp1dhxqrbo']' returned non-zero exit status 1.

ERROR:root:<class 'RuntimeError'>: Maximum error retries reached for instance astropy__astropy-12907`

### OpenHands Installation

Development workflow

### OpenHands Version

main

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

`docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.47/containers/openhands-runtime-be7c2750-2b8c-48c6-b01a-fa1f18585321-17ec15d55c9a19fc/json: Not Found ("No such container: openhands-runtime-be7c2750-2b8c-48c6-b01a-fa1f18585321-17ec15d55c9a19fc")

15:35:54 - openhands:ERROR: shared.py:347 - Command '['docker', 'buildx', 'build', '--progress=plain', '--build-arg=OPENHANDS_RUNTIME_VERSION=0.16.0', '--build-arg=OPENHANDS_RUNTIME_BUILD_TIME=2024-12-19T15:35:54.729360', '--tag=ghcr.io/all-hands-ai/runtime:oh_v0.16.0_o7lremih9uuceaof_swd7fszj4bcb8oyo', '--load', '--platform=linux/amd64', '/var/folders/rl/d4jq2g217cv1hy_ssxxj4k0r0000gn/T/tmp1dhxqrbo']' returned non-zero exit status 1.

ERROR:root:<class 'RuntimeError'>: Maximum error retries reached for instance astropy__astropy-12907`

**Comment by csmith49** [comment]
It looks like you can't find the container because the build is failing. A couple of things to try:

1. Export `DEBUG=1` when you run the evaluation script. The logs should contain more information about what is going wrong with the Docker build.
2. The build usually fails because you don't have enough space. The SWE-bench set is fairly memory-intensive, even for the Lite subset. Try `docker system prune` to clear up some unused builds.
