### ISSUE TITLE
[Question]: Development environment setups

### ISSUE THREAD

**Issue by kripper** [All-Hands-AI/OpenHands#5705]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1) For development of OpenHands, I was running VS Code on Windows and OpenHands inside a WSL container, using the "Dev Containers" extension.
I noticed that the devcontainer.json file was recently removed.
What is the current official way to develope openhands on a Windows machine?

2) When you instruct OpenHands to develope on OpenHands (to solve OpenHands github issues), are you using a special setup? Is there any documentation for this?

**Comment by mamoodi** [comment]
Hmmmm this is actually confusing me now. [The method mentioned here](https://github.com/All-Hands-AI/OpenHands/blob/main/containers/dev/README.md), is also not officially supported as far as I know. See the warning at the top.

The only official way to develop OpenHands was [the main Development guide](https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md#start-the-server-for-development) which includes installing the packages and then running `make build` and then `make run`.

Is that not working? How is "Developing on VS Code" different?

I have to circle back with the maintainers and see if anyone is using Windows as their dev environment.

**Comment by kripper** [comment]
The documentation is not clearly explaining how to create the WSL container on a windows machine where we do `make run`.
I used the `devcontainer.json` (container definition + init script), but I guess I should have used the `containers/dev/Dockerfile` (`containers/dev/compose.yml`) file?
The documentation mentions how to attach the container from VS Code which is nice, but I would suggest to enhance the documentation for new developers and provide a single section explaining how to setup the container and attach VS Code.
