### ISSUE TITLE
[Bug]: Inconsistent command line arguments in evaluation directory

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5735]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

In the evaluation directory, some benchmarks have an incorrect README file that uses snake case for command line arguments. However, in the `get_parser()` shared function, the command line arguments are written in kebab case. All READMEs and .py files in the evaluation/benchmarks directory should be fixed to standardize on kebab case.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12447191375).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5736 has been created. Please review the changes.
