### ISSUE TITLE
[Bug]: Move ./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh to general eval utils

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5739]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The functionality of `./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh` is not limited to swe-bench, so instead it should be moved to the general evaluation utils folder.

### OpenHands Installation

Docker command in README

### Operating System

None

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12448891531).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5740 has been created. Please review the changes.
