### ISSUE TITLE
[Bug]: Broken "Open in VSCode" button

### ISSUE THREAD

**Issue by avi12** [All-Hands-AI/OpenHands#5746]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When the virtual file system is ready, clicking this button doesn't do anything

https://github.com/user-attachments/assets/7fc433c8-6993-42d7-a3d4-6732916648e8

### OpenHands Installation

Docker command in README

### OpenHands Version

`main`

### Operating System

WSL on Windows

**Comment by mamoodi** [comment]
Yep. This is completely broken on main. Thanks for bringing it up.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12456763525).

**Comment by openhands-agent** [comment]
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5746' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5746). Manual intervention may be required.

**Comment by mamoodi** [comment]
This is working on main now.
