### ISSUE TITLE
Rename "Ran a Jupyter Command" to "Ran a Python Command" in UI

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5748]
**Summary**

People associate "Jupyter" strongly with data science, so it'd be better to change the UI to say "Ran a Python Command" to indicate that it's running generic commands.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12456563483).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5749 has been created. Please review the changes.
