### ISSUE TITLE
Install "jq" by default in OpenHands runtime

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5752]
**What problem or use case are you trying to solve?**

OpenHands with Claude uses the `jq` command pretty extensively, and fails when it's not available. I think it would be reasonable to add it given that it's not a very big package. It can be added to the software installed by default in the OpenHands runtime docker image.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12456990894).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5753 has been created. Please review the changes.
