### ISSUE TITLE
[Bug]: Discord & Slack links not working

### ISSUE THREAD

**Issue by UltraInstinct0x** [All-Hands-AI/OpenHands#5772]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

I couldn't find the links anywhere else, all lead to "expired" messages. Can you please update the links?
Currently not working:
- Slack
- Discord

### OpenHands Installation

Docker command in README

### Operating System

MacOS

**Comment by mamoodi** [comment]
@UltraInstinct0x can you try the links in this PR: https://github.com/All-Hands-AI/OpenHands/pull/5773/files

And see if they work for you to join Discord and Slack please?

**Comment by UltraInstinct0x** [comment]
Hi @mamoodi! Thank you very much!!! Yes I could join the Slack via that link however Discord still seems invalid. 
I think updating Readme with the slack link from the PR and a new Discord link will resolve this issue.
Or maybe updating them again and again, we can set up a flow for it.

**Comment by mamoodi** [comment]
@UltraInstinct0x how about this one: https://discord.gg/bm2gjaZYXK

**Comment by mamoodi** [comment]
Oh wait I think I'm doing something wrong.

**Comment by UltraInstinct0x** [comment]
> Oh wait I think I'm doing something wrong.

Yup, its not working :(

**Comment by mamoodi** [comment]
@UltraInstinct0x one more try. How about this: 
https://discord.gg/cVXaB6xKWD

**Comment by UltraInstinct0x** [comment]
> @UltraInstinct0x one more try. How about this: https://discord.gg/cVXaB6xKWD

Still no luck :(

**Comment by mamoodi** [comment]
Hmmmmmm that's strange.
https://discord.gg/mBuDGRzzES

If this doesn't work, something may be up with the server? I'll ask

**Comment by mamoodi** [comment]
Cause I see it says 1349 people have already joined with that and it doesn't expire.

**Comment by mamoodi** [comment]
And the original link that is on the README, most people joined with that so there might be an issue on your side....

**Comment by tobitege** [comment]
@mamoodi the link with "ESHStjSjD4" points to the moderator channel, please check that you create a link to the public channel? 😁

**Comment by mamoodi** [comment]
@tobitege that's what I thought it was at first!! But 3k+ people have joined using that link so it must be working? :D

**Comment by UltraInstinct0x** [comment]
@mamoodi @tobitege thank you for both of your help, I could finally join. 

Here what was wrong:
- Discord is banned in TR
- WARP connects to many Discord API's without issues
- However banners etc. cannot be loaded with WARP
- Likewise invite link leads to a page which says "Invite is expired" 
- I tried another VPN, same link worked.



> ...most people joined with that so there might be an issue on your side....

Given that the link is valid, the only plausible explanation that comes to mind was the possibility of a network and it worked. Thanks a lot!!!
