### ISSUE TITLE
Tooltips for navbar

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5806]
**What problem or use case are you trying to solve?**

The icons on the navbar on the left are not 100% self-explanatory.

<img width="167" alt="398408284-2eff9db9-c4e4-4b20-ad63-d26cbe3e3c7a" src="https://github.com/user-attachments/assets/4180b88d-fe0f-40e3-ad84-c0ec7653ed0f" />

**Describe the UX of the solution you'd like**

It would be good to have tooltips where if you mouse-over a navbar item (other than the user icon) it tells you what the icon stands for.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12497985007).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5807 has been created. Please review the changes.
