### ISSUE TITLE
[Bug]: Settings do not save

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#5852]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

![image](https://github.com/user-attachments/assets/943d5d20-a139-4dad-8748-65c532112161)

- Modify any setting in the config modal
- Press save

### OpenHands Installation

Docker command in README

### OpenHands Version

0.17

### Operating System

MacOS

**Comment by mamoodi** [comment]
@amanape did you check on main?

**Comment by amanape** [comment]
Yep

**Comment by mamoodi** [comment]
Dang. This is critical. Can we get it fixed ASAP please?
https://github.com/All-Hands-AI/OpenHands/issues/5837

**Comment by amanape** [comment]
Duplicate of #5837
