### ISSUE TITLE
[Bug]: Language input is broken

### ISSUE THREAD

**Issue by amanape** [All-Hands-AI/OpenHands#5856]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

1. Clear application data (or open in incognito) to simulate first time start
2. Open account settings
  ![image](https://github.com/user-attachments/assets/e73f5fdf-5d4c-45de-a8c3-ecb44a64a7c9)
3. Select any language and save
4. Notice that it is still an empty input
5. Select another different language
6. Notice that the selected language is the previous language and not the latest selection

This reflects on the actual translations too. If I first select Deutsch, I see the default (English) translations. If I then select Norsk, I see the German translations instead of Norwegian

### OpenHands Installation

Docker command in README

### OpenHands Version

0.17

### Operating System

MacOS

**Comment by mamoodi** [comment]
Hopefully with all the changes on main for settings, this will be fixed?
