### ISSUE TITLE
Add an automatic check of version consistency in documentation

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5890]
**What problem or use case are you trying to solve?**

When we update versions in documentation, they are specified in many different places across the codebase, and sometimes they get out of sync.

**Describe the UX of the solution you'd like**

It would be good to have automatic checks that our version are consistent.

**Do you have thoughts on the technical implementation?**

To do so, we can create a linting rule in lint.yml that uses a regex to search the entire codebase for all instances of `openhands:0.XX` or `runtime:0.XX` where `XX` is two digits. The linting rule should check that one and only one unique value of XX is found throughout the entire codebase.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12531220308).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5891 has been created. Please review the changes.
