### ISSUE TITLE
Make it possible to collapse the right-hand side of the openhands screen

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5894]
**What problem or use case are you trying to solve?**

Currently, OpenHands has two major components, the chat window on the left, and the workspace, terminal, etc. on the right.
<img width="1314" alt="Screenshot 2024-12-28 at 11 43 27 PM" src="https://github.com/user-attachments/assets/df50dddc-a386-4fa8-aade-90d9b00ef43b" />

**Describe the UX of the solution you'd like**

It would be nice to allow the chat component to take the entire screen, as it would allow for better viewing of generated code, changed files, etc. with your entire screen space.

**Do you have thoughts on the technical implementation?**

This can be implemented as a collapse/expand button, similar to this one from overleaf (but obviously, instead of saying "PDF" it'd say something like "workspace/terminal":

<img width="191" alt="Screenshot 2024-12-28 at 11 48 13 PM" src="https://github.com/user-attachments/assets/4d9bcc17-2ebf-4a07-8674-b4cdac5c1f7c" />

<img width="181" alt="Screenshot 2024-12-28 at 11 48 38 PM" src="https://github.com/user-attachments/assets/b05f22f3-d8da-4cbd-babf-38bf21631328" />

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12532588051).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5896 has been created. Please review the changes.
