### ISSUE TITLE
Remove runtime container after use

### ISSUE THREAD

**Issue by irishrain** [All-Hands-AI/OpenHands#5899]
**What problem or use case are you trying to solve?**
When starting a new session (either for a new prompt or for a different setting) the UI asks for confirmation before terminating the existing session. The new session then starts a new runtime container. However, the old one is still running.

**Describe the UX of the solution you'd like**
Whenever a new runtime is started, automatically stop and remove the old runtime.

**Do you have thoughts on the technical implementation?**

**Describe alternatives you've considered**

**Additional context**

**Comment by mamoodi** [comment]
This is likely as designed for now...This way you can access your previous runtime files, convos just in case.
Also the team is working on multiple conversations so you'll need more than one runtime running.
