### ISSUE TITLE
Create browsable OpenHands prompt library

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5905]
**What problem or use case are you trying to solve?**

Right now it's a little bit hard to know where to start with OpenHands, so it'd be great to have some examples.

**Describe the UX of the solution you'd like**

We could create a browsable library of prompts that have worked well with OpenHands, possibly together with the corresponding pull requests when they're available.

**Do you have thoughts on the technical implementation?**

It'd be nice to be able to have the community submit prompts.

We also have the public [feedback](https://huggingface.co/datasets/all-hands/openhands-feedback) from OpenHands, which we could use to start populating this.

**Comment by xingyaoww** [comment]
This might be duplicate of https://github.com/All-Hands-AI/OpenHands/issues/5826?

I had a proposal here: https://github.com/All-Hands-AI/OpenHands/blob/f7573cb29d4e9c2f5469be21180464f8f6dd9c1a/microagents/README.md

**Comment by neubig** [comment]
Ah, got it. It wasn't super-clear from the PR description that this was a duplicate, but I agree that it kinda is.
