### ISSUE TITLE
[Feature]: Ensure Consistency of Starting Requirements Across the Repository

### ISSUE THREAD

**Issue by openhands-agent** [All-Hands-AI/OpenHands#5906]
**What problem or use case are you trying to solve?**  
There are inconsistencies in the software requirements mentioned in our documentation, such as the Node.js version required for components like react-router.

For instance:
* [This page](https://github.com/All-Hands-AI/OpenHands/tree/main/frontend#prerequisites) notes "NodeJS >= 20.x"
* [This page](https://github.com/All-Hands-AI/OpenHands/blob/main/Development.md#start-the-server-for-development) noted Node 18.17.1 (until very recently)

**Describe the UX of the solution you'd like**  
We would like to systematically review all documentation and ensure that all requirements mentioned in the documentation actually match the requirements in "pyproject.yaml" (backend) and "package.json" (frontend). To do this, we can first read these two files, which are the source of truth with respect to versions, and then grep through all the documentation files to find stated version numbers for requirements, and fix any ones that are inconsistent with the source of truth.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12541464894).

**Comment by openhands-agent** [comment]
A potential fix has been generated and a draft PR #5908 has been created. Please review the changes.

**Comment by neubig** [comment]
This issue was fixed already.
