### ISSUE TITLE
[Bug]: "Runtime failed to return execute_action" on command timeout

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#5927]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

This is a very frequent error that I have found on the OpenHands online app, but I suspect it will affect any case where we're using the remote runtime in general. Basically what happens is that OpenHands runs a command that will take a while, and we get the following error in the UI: `Runtime failed to return execute_action before the requested timeout of 120s` and the agent stops until I send further input:

<img width="338" alt="Screenshot 2024-12-31 at 5 42 00 AM" src="https://github.com/user-attachments/assets/ed94904f-4c19-4f36-8438-f646659d21fb" />

Note that this is *not* the expected behavior when a command times out, instead the command should be interrupted with a timeout, and the agent should be able to recover from this: https://github.com/All-Hands-AI/OpenHands/blob/d7a3ec69d9006438f03f45ada6b2a7e638ad96ff/openhands/runtime/utils/bash.py#L176

This is a pretty big blocker that prevents the agent from working autonomously.

### OpenHands Installation

app.all-hands.dev

### Operating System

None

**Comment by enyst** [comment]
@neubig Sorry, are we sure this isn't a duplicate of 
- https://github.com/All-Hands-AI/OpenHands/issues/5601 ?

**Comment by neubig** [comment]
Hah, it is, sorry. For some reason I didn't remember that I actually opened this before. Closing.
