### ISSUE TITLE
Allow sandbox to interactively captures password / stdin inputs

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#892]
> This is great @xingyaoww so fast for implementing this! Thank you!
> 
> I think the `pexpect` module can also handle things like prompting to input password, as well as those Y/N prompts in the middle of a process.
> 
> Now it's using `ssh.prompt()` to look for shell prompts like `#` or `$` to determine if the previous command is finished as for when to read the output and send the input. For processes asking password like "Password:" or apt-get "Proceed? y/n" do we need to add a bit more regex to the default prompt https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.expect in order to handle those "wait-for-input", or does the current implementation works out of the box for "y/n" and "password:". I am thinking if `ssh.expect("Password:")` or `ssh.expect("y/n")` is needed?
> 
> **Not a merge-blocking comment**

As discussed by @frankxu2004 in #847, we may need something like `ssh.expect("Password:")` or `ssh.expect("y/n")`  to capture some more cases in [sandbox.py](https://github.com/OpenDevin/OpenDevin/blob/cc6626ff0da9f3c146e88c179f1e1432b9d60550/opendevin/sandbox/sandbox.py#L4)

One simple issue that requires this: Right not if you run `sudo apt-get update`, the sandbox will stuck (probably waiting for a `password:` input) - ideally our code should capture that and automatically put in the password for that `sudo` command.

<img width="1087" alt="image" src="https://github.com/OpenDevin/OpenDevin/assets/38853559/a42f56df-670f-4aa1-b13b-f9b8742558a4">

@frankxu2004 Feel free to starts a PR if you are interested :)

**Comment by Umpire2018** [comment]
```python
python opendevin/runtime/docker/exec_box.py

06:15:55 - opendevin:INFO: exec_box.py:135 - Starting Docker container with image ghcr.io/opendevin/sandbox:main, sandbox workspace dir=/workspace
06:15:55 - opendevin:INFO: exec_box.py:304 - Container stopped
06:15:55 - opendevin:INFO: exec_box.py:321 - Container started
06:15:56 - opendevin:INFO: exec_box.py:378 - Interactive Docker container started. Type 'exit' or use Ctrl+C to exit.
>>> sudo apt-get update
06:16:18 - opendevin:INFO: exec_box.py:402 - exit code: 0
06:16:18 - opendevin:INFO: exec_box.py:403 - Get:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [128 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [127 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [129 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages [1758 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse arm64 Packages [224 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports jammy/restricted arm64 Packages [24.2 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages [17.2 MB]
Get:9 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [1996 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1937 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [29.5 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [1330 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-backports/universe arm64 Packages [30.3 kB]
Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-backports/main arm64 Packages [80.6 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [1671 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [1052 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [1919 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse arm64 Packages [24.1 kB]
Fetched 29.9 MB in 15s (2055 kB/s)
Reading package lists...
06:16:18 - opendevin:INFO: exec_box.py:406 - background logs: ......................
```

I don't think this issue still exists in current version 41ddba84bd0d62f8a4bc48d08addde4b4269a687 . Just slow instead of stuck. But I think this part needs some optimization, what do you think?

**Comment by Umpire2018** [comment]
https://github.com/OpenDevin/OpenDevin/assets/138990495/6f81af19-09f1-4e81-af69-be2dae65e96e

To enhance the user experience, consider using `stream=True` for all commands to provide real-time output, allowing users to see the command results as they are generated. I have noticed that this functionality is not yet working correctly in the current code.

After that, maybe we don't need to worry about this question any more.

```
        # TODO: this timeout is actually essential - need a better way to set it
        # if it is too short, the container may still waiting for previous
        # command to finish (e.g. apt-get update)
```

**Comment by xingyaoww** [comment]
That's actually something I've hope to have for a while. But streaming to frontend (compared to streaming to stdout directly) might require us to re-write the whole event stream a bit to support token streaming, which could be pretty complicated in my understanding. I don't yet have a better idea so feel free to PR if you've got good ones ;)

**Comment by Umpire2018** [comment]
> That's actually something I've hope to have for a while. But streaming to frontend (compared to streaming to stdout directly) might require us to re-write the whole event stream a bit to support token streaming, which could be pretty complicated in my understanding. I don't yet have a better idea so feel free to PR if you've got good ones ;)

I think adding `stream` to frontend may be a tricky one. Suggest to open a new issue to address it.
