### ISSUE TITLE
Find a workaround for `network_mode='host'` not supported on Mac OS

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#897]
> @yufansong, thanks for the quick PR. I think the issue is probably because of the Allow Origin 127.0.0.1, which may cause issues for different setups. I don't think changing `network_mode='host',` to the port mapping of `2222` will have a huge impact? It may further stop the user from accessing web servers started by opendevin inside the sandbox.

Yeah, agree.

_Originally posted by @yufansong in https://github.com/OpenDevin/OpenDevin/issues/891#issuecomment-2042319369_

---

It turns out docker [does NOT currently support `network_mode='host'` on Mac](https://github.com/docker/roadmap/issues/238). Our current solution performs a port mapping (2222<->2222) so that the sandbox environment can interact with the container via `ssh`. However, we would like to be able to access *any* port inside the container because open-devin agent may want to spin up webservers on any arbitrary port.

I guess we can either:
1. Pre-allocate ports for mapping (e.g., 8000-8100) and put these in the prompt so that Devin knows to use these exposed port
2. We figure out a way to detect server patterns with port information from stdout (which would be pretty ugly and unreliable), then figure out a way to add this port mapping to the existing container
3. We figure out a way to create a proxy server on a fixed port (say 10000), then we can proxy all traffic from the host machine through this port into the container. (probably the most general solution i could think of)

**Comment by JustinLin610** [comment]
then you gave a solution yourself hahah.

**Comment by casper-hansen** [comment]
`-P` maps all ports, so you don’t need to specify literally all ports or be locked into a single port. You can also use the `docker port` command to check how ports are mapped

**Comment by rbren** [comment]
Is this still a problem in the dockerized world?

**Comment by Umpire2018** [comment]
Reference: [here](https://docs.docker.com/network/drivers/host/#docker-desktop).

> Host networking is also supported on Docker Desktop version 4.29 and later for Mac, Windows, and Linux as a [beta feature](https://docs.docker.com/release-lifecycle/#beta). To enable this feature, navigate to the Features in development tab in Settings, and then select Enable host networking.

Maybe we can close this one?

**Comment by xingyaoww** [comment]
We decided to enable host networking until this docker feature is out of beta -- maybe we can keep this PR open until we eventually did that :)

**Comment by SmartManoj** [comment]
> Host networking is also supported on Docker Desktop version 4.29 and later for Mac, Windows, and Linux as a [beta feature](https://docs.docker.com/release-lifecycle/#beta). To enable this feature, navigate to the Features in development tab in Settings, and then select Enable host networking.

One needs to sign in for this feature for now. https://github.com/docker/roadmap/issues/238#issuecomment-2044688144

**Comment by tobitege** [comment]
@SmartManoj good find your link!

What do you think about below comment on the same page to use a Powershell script to add the option to the docker settings file? Could this be a temp workaround for users here?

https://github.com/docker/roadmap/issues/238#issuecomment-2044813928

**Comment by SmartManoj** [comment]
Seems it is still not working for Windows.
https://github.com/docker/roadmap/issues/238#issuecomment-2119021074

**Comment by windemut** [comment]
I have this issue, I cannot connect to any servers started within Devin. It even warns you when it starts up and refers to this issue: "Using port forwarding for Mac OS. Server started by OpenDevin will not be accessible from the host machine at the moment. See https://github.com/OpenDevin/OpenDevin/issues/897 for more information." 

However, I have not found a workaround, here, that I could understand. If such a workaround exists, could someone please post clear instructions on what to do? I use this command to start the image:

```
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --net=host \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

**Comment by SmartManoj** [comment]
Workaround: https://github.com/docker/roadmap/issues/238#issuecomment-2044688144

**Comment by windemut** [comment]
It doesn't work for me. I have the feature enabled, I have --net=host, I added "-p 8000:8000". Still getting "refused to connect" on that port on localhost. :-(

**Comment by SmartManoj** [comment]
Sorry, need to pass USE_HOST_NETWORK also.
```
WORKSPACE_BASE=$(pwd)/workspace
docker run -it \
    --pull=always \
    -e SANDBOX_USER_ID=$(id -u) \
    -e USE_HOST_NETWORK=True
    -e WORKSPACE_MOUNT_PATH=$WORKSPACE_BASE \
    -v $WORKSPACE_BASE:/opt/workspace_base \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --net=host \
    -p 3000:3000 \
    --add-host host.docker.internal:host-gateway \
    --name opendevin-app-$(date +%Y%m%d%H%M%S) \
    ghcr.io/opendevin/opendevin:0.6.2
```

**Comment by windemut** [comment]
That's what I was missing. It works with that!
Thank you!!!

**Comment by neubig** [comment]
@xingyaoww maybe this is now fixed given that we don't use sshbox anymore?

**Comment by xingyaoww** [comment]
@neubig this is still relevant in eventstream runtime though - but I think now the network=host mode is officially supported by docker (though still in beta) - so i guess this is kinda already solved (as long as you click "enable host networking"

<img width="940" alt="image" src="https://github.com/user-attachments/assets/b47407f0-78df-4042-ae13-eb3af23c9df0">


Let's close it until the issue comes out again.

**Comment by cl-abdulla** [comment]
still not fixed?
